CREATE OR REPLACE FORCE VIEW VW_AMECO_INDICATORS
AS
    SELECT I.INDICATOR_SID, C.*, P.PROVIDER_ID, P.PROVIDER_SID, P.DATA_SOURCE, I.PERIODICITY_ID
      FROM AMECO_INDICATORS  I
           JOIN AMECO_INDICATOR_CODES C ON C.INDICATOR_CODE_SID = I.INDICATOR_CODE_SID
           JOIN AMECO_PROVIDERS P ON P.PROVIDER_SID = I.PROVIDER_SID;
