CREATE OR REPLACE FORCE VIEW VW_AMECO_INDICATOR_DATA
AS
    SELECT D.COUNTRY_ID
         , D.INDICATOR_SID
         , D.START_YEAR
         , D.TIMESERIE_DATA
         , M.HST_TIMESERIE_DATA
         , M.SRC_TIMESERIE_DATA
         , M.LEVEL_TIMESERIE_DATA
         , D.UPDATE_DATE
         , D.UPDATE_USER
         , I.INDICATOR_ID
         , G.DESCR AS COUNTRY_DESCR
         , I.DATA_SOURCE
         , I.PROVIDER_ID
         , I.PERIODICITY_ID
      FROM AMECO_INDICATOR_DATA D
      JOIN VW_AMECO_INDICATORS I
        ON D.INDICATOR_SID = I.INDICATOR_SID
      JOIN GEO_AREAS G
        ON G.GEO_AREA_ID = D.COUNTRY_ID
      LEFT OUTER JOIN AMECO_INDICATOR_METADATA M
        ON D.INDICATOR_DATA_SID = M.INDICATOR_DATA_SID;
