/* Formatted on 12/3/2019 12:52:11 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_COL_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_COL_TYPES CASCADE CONSTRAINTS;

CREATE TABLE GD_COL_TYPES
(
   COL_TYPE_SID   NUMBER (8) CONSTRAINT GD_COL_TYPES_PK PRIMARY KEY
,  COL_TYPE_ID    VARCHAR2 (10 BYTE)
                     NOT NULL
                     CONSTRAINT GD_COL_TYPES_ID_UNQ UNIQUE
,  DESCR          VARCHAR2 (50 BYTE)
);