/* Formatted on 12/3/2019 13:01:04 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_COLS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_COLS CASCADE CONSTRAINTS;
DROP SEQUENCE GD_COLS_SEQ;

CREATE TABLE GD_COLS
(
   COL_SID         NUMBER (8) CONSTRAINT GD_COLS_PK PRIMARY KEY
,  COL_TYPE_SID    NUMBER (8)
                      NOT NULL
                      CONSTRAINT GD_COLS_COL_TYPE_FK
                          REFERENCES GD_COL_TYPES (COL_TYPE_SID)
,  DESCR           VARCHAR2 (500 BYTE)
,  DATA_TYPE_SID   NUMBER (8)
                      CONSTRAINT GD_COLS_DATA_TYPE_FK
                          REFERENCES GD_DATA_TYPES (DATA_TYPE_SID)
,  YEAR_VALUE      NUMBER (4)
,  IS_ABSOLUTE     NUMBER (1)
,  HELP_MSG_SID    NUMBER (12)
                      CONSTRAINT GD_COLS_HELP_MSG_FK
                          REFERENCES HELP_MSGS (HELP_MSG_SID)
,  IS_MANDATORY    NUMBER (1)
,  WIDTH           NUMBER (8)
);

CREATE SEQUENCE GD_COLS_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER GD_COLS_TRG
   BEFORE INSERT
   ON GD_COLS
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN
   SELECT GD_COLS_SEQ.NEXTVAL INTO :NEW.col_sid FROM DUAL;
END;
/
COMMENT ON TABLE GD_COLS IS 'Columns';
COMMENT ON COLUMN GD_COLS.COL_SID IS 'Column SID';
COMMENT ON COLUMN GD_COLS.COL_TYPE_SID IS 'Column type';
COMMENT ON COLUMN GD_COLS.DESCR IS 'Description';
COMMENT ON COLUMN GD_COLS.DATA_TYPE_SID IS 'Data type';
COMMENT ON COLUMN GD_COLS.YEAR_VALUE IS 'Year';
COMMENT ON COLUMN GD_COLS.IS_ABSOLUTE IS 'Absolute year indicator';
COMMENT ON COLUMN GD_COLS.HELP_MSG_SID IS 'Help message';
COMMENT ON COLUMN GD_COLS.IS_MANDATORY IS 'Mandatory indicator';
/