/* Formatted on 12/2/2019 18:41:18 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_CONSISTENCY_STATUSES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_CONSISTENCY_STATUSES;

CREATE TABLE GD_CONSISTENCY_STATUSES
(
   CONSISTENCY_STATUS_SID   NUMBER (4)
                               CONSTRAINT GD_CONSISTENCY_STATUSES_PK PRIMARY KEY
,  CONSISTENCY_STATUS_ID    VARCHAR2 (8 BYTE)
                               NOT NULL
                               CONSTRAINT GD_CONSISTENCY_STATUSES_UNQ UNIQUE
,  DESCR                    VARCHAR2 (100 BYTE)
);

DROP SEQUENCE GD_CONSISTENCY_STATUSES_SEQ;

CREATE SEQUENCE GD_CONSISTENCY_STATUSES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_CONSISTENCY_STATUSES_TRG
   BEFORE INSERT
   ON GD_CONSISTENCY_STATUSES
   FOR EACH ROW
BEGIN
   SELECT GD_CONSISTENCY_STATUSES_SEQ.NEXTVAL
     INTO :NEW.CONSISTENCY_STATUS_SID
     FROM DUAL;
END;