/* Formatted on 12/3/2019 12:32:17 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_CTY_GRIDS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_CTY_GRIDS;
DROP SEQUENCE GD_CTY_GRIDS_SEQ;

CREATE TABLE GD_CTY_GRIDS
(
   CTY_GRID_SID                NUMBER (8) CONSTRAINT GD_CTY_GRIDS_PK PRIMARY KEY
,  CTY_VERSION_SID             NUMBER (8)
                                  NOT NULL
                                  CONSTRAINT GD_CTY_GRIDS_CTY_VERSION_FK
                                      REFERENCES GD_CTY_VERSIONS (CTY_VERSION_SID)
,  ROUND_GRID_SID              NUMBER (8)
                                  NOT NULL
                                  CONSTRAINT GD_CTY_GRIDS_ROUND_GRID_FK
                                     REFERENCES GD_ROUND_GRIDS (ROUND_GRID_SID) ON DELETE CASCADE
,  CONSISTENCY_STATUS_MS_SID   NUMBER (4)
                                  CONSTRAINT GD_CTY_GRIDS_STATUS_MS_FK
                                     REFERENCES GD_CONSISTENCY_STATUSES (CONSISTENCY_STATUS_SID)
,  CONSISTENCY_STATUS_CD_SID   NUMBER (4)
                                  CONSTRAINT GD_CTY_GRIDS_STATUS_CD_FK
                                     REFERENCES GD_CONSISTENCY_STATUSES (CONSISTENCY_STATUS_SID)
,  CONSTRAINT GD_CTY_GRIDS_UNQ UNIQUE (CTY_VERSION_SID, ROUND_GRID_SID)
);

CREATE SEQUENCE GD_CTY_GRIDS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_CTY_GRIDS_TRG
   BEFORE INSERT
   ON GD_CTY_GRIDS
   FOR EACH ROW
BEGIN
   SELECT GD_CTY_GRIDS_SEQ.NEXTVAL INTO :NEW.CTY_GRID_SID FROM DUAL;
END;