ALTER TABLE GD_CTY_ROUND_SCALES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_CTY_ROUND_SCALES;


CREATE TABLE GD_CTY_ROUND_SCALES
(
  CTY_VERSION_SID  NUMBER(8),
  ROUND_SID        NUMBER(8),
  SCALE_SID        NUMBER(8)
);

ALTER TABLE GD_CTY_ROUND_SCALES ADD (
  CONSTRAINT GD_CTY_ROUND_SCALES_PK
  PRIMARY KEY (CTY_VERSION_SID, ROUND_SID)
,  CONSTRAINT GD_CTY_ROUND_SCALES_CTY_V_FK 
  FOREIGN KEY (CTY_VERSION_SID) REFERENCES GD_CTY_VERSIONS (CTY_VERSION_SID)
  ENABLE VALIDATE
,  CONSTRAINT GD_CTY_ROUND_SCALES_ROUND_FK 
  FOREIGN KEY (ROUND_SID) REFERENCES ROUNDS (ROUND_SID)
  ENABLE VALIDATE
,  CONSTRAINT GD_CTY_ROUND_SCALES_SCALE_FK 
  FOREIGN KEY (SCALE_SID) REFERENCES SCALES (SCALE_SID)
  ENABLE VALIDATE);

