/* Formatted on 12/2/2019 18:54:00 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_CTY_VERSIONS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_CTY_VERSIONS;
DROP SEQUENCE GD_CTY_VERSIONS_SEQ;

CREATE TABLE GD_CTY_VERSIONS
(
   CTY_VERSION_SID   NUMBER (8) CONSTRAINT GD_CTY_VERSIONS_PK PRIMARY KEY
,  COUNTRY_ID        VARCHAR2 (2 BYTE)
                        NOT NULL
                        CONSTRAINT GD_CTY_VERSIONS_COUNTRY_FK
                            REFERENCES GEO_AREAS (GEO_AREA_ID)
,  VERSION           NUMBER (4) DEFAULT 1 NOT NULL
,  CONSTRAINT GD_CTY_VERSIONS_UNQ UNIQUE (COUNTRY_ID, VERSION)
);


CREATE SEQUENCE GD_CTY_VERSIONS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_CTY_VERSIONS_TRG
   BEFORE INSERT
   ON GD_CTY_VERSIONS
   FOR EACH ROW
BEGIN
   SELECT GD_CTY_VERSIONS_SEQ.NEXTVAL INTO :NEW.CTY_VERSION_SID FROM DUAL;
END;