/* Formatted on 12/3/2019 14:09:57 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_FOOTNOTES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_FOOTNOTES CASCADE CONSTRAINTS;
DROP SEQUENCE GD_FOOTNOTES_SEQ;

CREATE TABLE GD_FOOTNOTES
(
   FOOTNOTE_SID      NUMBER (8) CONSTRAINT GD_FOOTNOTES_PK PRIMARY KEY
,  CTY_GRID_SID      NUMBER (8)
                        NOT NULL
                        CONSTRAINT GD_FOOTNOTES_CTY_GRID_FK
                            REFERENCES GD_CTY_GRIDS (CTY_GRID_SID)
,  DESCR             VARCHAR2 (4000 BYTE) NOT NULL
,  VERSION_TYPE_ID   VARCHAR2 (2 CHAR)
                        NOT NULL
                        CONSTRAINT GD_FOOTNOTES_VER_TYPE_FK
                           REFERENCES GD_GRID_VERSION_TYPES (VERSION_TYPE_ID)
);

CREATE SEQUENCE GD_FOOTNOTES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_FOOTNOTES_TRG
   BEFORE INSERT
   ON GD_FOOTNOTES
   FOR EACH ROW
BEGIN
   SELECT GD_FOOTNOTES_SEQ.NEXTVAL INTO :NEW.FOOTNOTE_SID FROM DUAL;
END;