/* Formatted on 12/2/2019 18:47:00 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_GRIDS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_GRIDS;
DROP SEQUENCE GD_GRIDS_SEQ;

CREATE TABLE GD_GRIDS
(
   GRID_SID        NUMBER (8) CONSTRAINT GD_GRIDS_PK PRIMARY KEY
,  DESCR           VARCHAR2 (500 BYTE)
,  GRID_ID         VARCHAR2 (3 BYTE) NOT NULL
,  HELP_MSG_SID    NUMBER
                      CONSTRAINT GD_GRIDS_HELP_MSGS_FK
                          REFERENCES HELP_MSGS (HELP_MSG_SID)
,  GRID_STATUS     VARCHAR2 (16 BYTE) DEFAULT 'Unlocked'
,  GRID_TYPE_SID   NUMBER
                      NOT NULL
                      CONSTRAINT FK_GRID_TYPE_SID
                          REFERENCES GD_GRID_TYPES (GRID_TYPE_SID)
,  ROUTE           VARCHAR (32) DEFAULT 'grid' NOT NULL
);


CREATE SEQUENCE GD_GRIDS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_GRIDS_TRG
   BEFORE INSERT
   ON GD_GRIDS
   FOR EACH ROW
BEGIN
   SELECT GD_GRIDS_SEQ.NEXTVAL INTO :NEW.GRID_SID FROM DUAL;
END;