/* Formatted on 12/3/2019 12:28:56 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_GRID_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_GRID_TYPES CASCADE CONSTRAINTS;

CREATE TABLE GD_GRID_TYPES
(
   GRID_TYPE_SID   NUMBER (8) CONSTRAINT GD_GRID_TYPES_PK PRIMARY KEY
,  GRID_TYPE_ID    VARCHAR2 (15 BYTE)
                      NOT NULL
                      CONSTRAINT GD_GRID_TYPES_ID_UNQ UNIQUE
,  DESCR           VARCHAR2 (50 BYTE)
);