/* Formatted on 22/09/2021 17:22:47 (QP5 v5.313) */
ALTER TABLE GD_GUARANTEES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_GUARANTEES CASCADE CONSTRAINTS;
DROP SEQUENCE GD_GUARANTEES_SEQ;

CREATE TABLE GD_GUARANTEES(
   GUARANTEE_SID    NUMBER(12) CONSTRAINT GD_GUARANTEES_PK PRIMARY KEY
 , ROUND_SID        NUMBER(8)
                    NOT NULL
                    CONSTRAINT GD_GUARANTEES_ROUND_FK REFERENCES ROUNDS(ROUND_SID)
 , DESCR VARCHAR2(4000 CHAR)
 , ADOPT_DATE_YR    NUMBER(4)
                    CONSTRAINT GD_GUARANTEES_ADOPT_YR_CHK CHECK
                       (ADOPT_DATE_YR >= 1950 AND ADOPT_DATE_YR <= 2100)
 , ADOPT_DATE_MH    NUMBER(2)
                    CONSTRAINT GD_GUARANTEES_ADOPT_MH_CHK CHECK
                       (ADOPT_DATE_MH >= 1 AND ADOPT_DATE_MH <= 12)
 , MAX_CONTINGENT_LIAB NUMBER
 , ESTIMATED_TAKE_UP NUMBER
 , REASON_SID       NUMBER(8)
                    NOT NULL
                    CONSTRAINT GD_GUARANTEES_REASON_FK REFERENCES GD_GUARANTEE_REASONS(REASON_SID)
 , CTY_VERSION_SID  NUMBER(8)
                    CONSTRAINT GD_GUARANTEES_CTY_VER_FK
                    REFERENCES GD_CTY_VERSIONS(CTY_VERSION_SID)
);

CREATE SEQUENCE GD_GUARANTEES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_GUARANTEES_TRG
   BEFORE INSERT
   ON GD_GUARANTEES
   FOR EACH ROW
BEGIN
   SELECT GD_GUARANTEES_SEQ.NEXTVAL INTO :NEW.GUARANTEE_SID FROM DUAL;
END;
/