CREATE TABLE GD_LINE_INDICATOR 
(
  LINE_SID NUMBER NOT NULL
      CONSTRAINT GD_LINE_INDICATOR_LINE_FK
         REFERENCES GD_LINES (LINE_SID)
, DATA_TYPE_SID NUMBER NOT NULL 
      CONSTRAINT GD_LINE_INDICATOR_DATA_TYPE_FK
         REFERENCES GD_DATA_TYPES (DATA_TYPE_SID)
, INDICATOR_SID NUMBER NOT NULL 
      CONSTRAINT GD_LINE_INDICATOR_INDICATOR_FK
         REFERENCES INDICATORS (INDICATOR_SID)
, CONSTRAINT GD_LINE_INDICATOR_PK PRIMARY KEY (LINE_SID, DATA_TYPE_SID)
);
