/* Formatted on 12/3/2019 15:46:50 (QP5 v5.252.13127.32847) */
DROP TABLE GD_OPT_CELLS CASCADE CONSTRAINTS;

CREATE TABLE GD_OPT_CELLS
(
   LINE_SID   NUMBER
                 NOT NULL
                 CONSTRAINT OPT_CELLS_LINE_FK
                     REFERENCES GD_LINES (LINE_SID)
,  COL_SID    NUMBER
                 NOT NULL
                 CONSTRAINT OPT_CELLS_COL_FK
                     REFERENCES GD_COLS (COL_SID)
,  CONSTRAINT GD_OPT_CELLS_UNQ UNIQUE (LINE_SID, COL_SID)
);

COMMENT ON TABLE GD_OPT_CELLS IS 'Optional cells';
COMMENT ON COLUMN GD_OPT_CELLS.LINE_SID IS 'Line position';
COMMENT ON COLUMN GD_OPT_CELLS.COL_SID IS 'Column position';