/* Formatted on 12/2/2019 18:52:24 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_ROUND_GRIDS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_ROUND_GRIDS;

CREATE TABLE GD_ROUND_GRIDS
(
   ROUND_GRID_SID   NUMBER (8) CONSTRAINT GD_ROUND_GRIDS_PK PRIMARY KEY
,  ROUND_SID        NUMBER (8)
                       NOT NULL
                       CONSTRAINT GD_ROUND_GRIDS_ROUND_FK
                           REFERENCES ROUNDS (ROUND_SID)
,  GRID_SID         NUMBER (8)
                       NOT NULL
                       CONSTRAINT GD_ROUND_GRIDS_GRID_FK
                           REFERENCES GD_GRIDS (GRID_SID) ON DELETE CASCADE
,  ORDER_BY         NUMBER (3)
,  CONSTRAINT GD_ROUND_GRIDS_UNQ UNIQUE (ROUND_SID, GRID_SID)
);

DROP SEQUENCE GD_ROUND_GRIDS_SEQ;

CREATE SEQUENCE GD_ROUND_GRIDS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_ROUND_GRIDS_TRG
   BEFORE INSERT
   ON GD_ROUND_GRIDS
   FOR EACH ROW
BEGIN
   SELECT GD_ROUND_GRIDS_SEQ.NEXTVAL INTO :NEW.ROUND_GRID_SID FROM DUAL;
END;