/* Formatted on 12/3/2019 13:10:14 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_ROUND_GRID_COLS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_ROUND_GRID_COLS;
DROP SEQUENCE GD_ROUND_GRID_COLS_SEQ;

CREATE TABLE GD_ROUND_GRID_COLS
(
   ROUND_GRID_COL_SID   NUMBER (8)
                           CONSTRAINT GD_ROUND_GRID_COLS_PK PRIMARY KEY
,  ROUND_GRID_SID       NUMBER (8)
                           NOT NULL
                           CONSTRAINT GD_ROUND_GRID_COLS_RG_FK
                              REFERENCES GD_ROUND_GRIDS (ROUND_GRID_SID) ON DELETE CASCADE
,  COL_SID              NUMBER (8)
                           NOT NULL
                           CONSTRAINT GD_ROUND_GRID_COLS_COL_FK
                               REFERENCES GD_COLS (COL_SID)
,  ORDER_BY             NUMBER (3)
,  CONSTRAINT GD_ROUND_GRID_COLS_UNQ UNIQUE (ROUND_GRID_SID, COL_SID)
);

CREATE SEQUENCE GD_ROUND_GRID_COLS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_ROUND_GRID_COLS_TRG
   BEFORE INSERT
   ON GD_ROUND_GRID_COLS
   FOR EACH ROW
BEGIN
   SELECT GD_ROUND_GRID_COLS_SEQ.NEXTVAL
     INTO :NEW.ROUND_GRID_COL_SID
     FROM DUAL;
END;