/* Formatted on 9/4/2019 19:36:15 (QP5 v5.252.13127.32847) */
ALTER TABLE GD_ROUND_GRID_LINES
   DROP PRIMARY KEY CASCADE;

DROP TABLE GD_ROUND_GRID_LINES;
DROP SEQUENCE GD_ROUND_GRID_LINES_SEQ;

CREATE TABLE GD_ROUND_GRID_LINES
(
   ROUND_GRID_LINE_SID   NUMBER (8) CONSTRAINT GD_ROUND_GRID_LINES_PK PRIMARY KEY
,  ROUND_GRID_SID        NUMBER (8) NOT NULL CONSTRAINT GD_ROUND_GRID_LINES_RG_FK
       REFERENCES GD_ROUND_GRIDS (ROUND_GRID_SID) ON DELETE CASCADE
,  LINE_SID              NUMBER (8) NOT NULL CONSTRAINT GD_ROUND_GRID_LINES_LINE_FK
       REFERENCES GD_LINES (LINE_SID)
,  ORDER_BY              NUMBER (3)
,  CONSTRAINT GD_ROUND_GRID_LINES_UNQ UNIQUE (ROUND_GRID_SID, LINE_SID)
);

CREATE SEQUENCE GD_ROUND_GRID_LINES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GD_ROUND_GRID_LINES_TRG
   BEFORE INSERT
   ON GD_ROUND_GRID_LINES
   FOR EACH ROW
BEGIN
   SELECT GD_ROUND_GRID_LINES_SEQ.NEXTVAL
     INTO :NEW.ROUND_GRID_LINE_SID
     FROM DUAL;
END;