/* Formatted on 12/4/2019 14:38:29 (QP5 v5.252.13127.32847) */
DROP TABLE DRM_ARCHIVED_CTY_SCALES CASCADE CONSTRAINTS;

CREATE TABLE DRM_ARCHIVED_CTY_SCALES
(
   ROUND_SID    NUMBER (8)
                   NOT NULL
                   CONSTRAINT DRM_ARCHIVED_CTY_SCALES_RND_FK
                       REFERENCES ROUNDS (ROUND_SID)
,  COUNTRY_ID   VARCHAR2 (10 BYTE)
                   NOT NULL
                   CONSTRAINT DRM_ARCHIVED_CTY_SCALES_CTY_FK
                       REFERENCES GEO_AREAS (GEO_AREA_ID)
,  SCALE_SID    NUMBER (8)
                   NOT NULL
                   CONSTRAINT DRM_ARCHIVED_CTY_SCALES_SCL_FK
                       REFERENCES SCALES (SCALE_SID)
,  LOG_DATE     DATE DEFAULT SYSDATE NOT NULL
,  CONSTRAINT DRM_ARCHIVED_CTY_SCALES_PK PRIMARY KEY (ROUND_SID, COUNTRY_ID)
);