/* Formatted on 12/4/2019 12:37:26 (QP5 v5.252.13127.32847) */
DROP TABLE DRM_CTY_SCALES CASCADE CONSTRAINTS;

CREATE TABLE DRM_CTY_SCALES
(
   COUNTRY_ID   VARCHAR2 (10 BYTE)
                   NOT NULL
                   CONSTRAINT DRM_CTY_SCALES_UNQ UNIQUE
                   CONSTRAINT DRM_CTY_SCALES_CTY_FK
                       REFERENCES GEO_AREAS (GEO_AREA_ID)
,  SCALE_SID    NUMBER (8)
                   NOT NULL
                   CONSTRAINT DRM_CTY_SCALES_SCALE_FK
                       REFERENCES SCALES (SCALE_SID)
);