/* Formatted on 06-09-2021 12:14:24 (QP5 v5.313) */
DROP TABLE DRM_MEASURE_LABELS CASCADE CONSTRAINTS;

CREATE TABLE DRM_MEASURE_LABELS(
   MEASURE_SID  NUMBER(8)
                CONSTRAINT DRM_MEASURE_LABELS_MEASURE_FK
                REFERENCES DRM_MEASURES(MEASURE_SID) ON DELETE CASCADE
                NOT NULL
 , LABEL_SID    NUMBER(4)
                CONSTRAINT DRM_MEASURE_LABELS_LABEL_FK REFERENCES DFM_LABELS(LABEL_SID)
                NOT NULL
 , CONSTRAINT DRM_MEASURE_LABELS_UNQ UNIQUE(MEASURE_SID, LABEL_SID)
);
/