CREATE OR REPLACE FORCE VIEW VW_ADDIN_ACTIVE_APPS
AS
    SELECT A.*,
               (SELECT LISTAGG (R.ROLE_ID, ',') WITHIN GROUP (ORDER BY P.DASHBOARD_SID)
                  FROM ADDIN_PERMISSIONS P
             LEFT JOIN SECUNDA_ROLES R
                    ON P.ROLE_SID = R.ROLE_SID
                 WHERE P.DASHBOARD_SID = A.DASHBOARD_SID
               ) AS ROLES
      FROM ADDIN_DASHBOARD A
     WHERE A.IS_ACTIVE = 1;
