/* Formatted on 12/4/2019 12:58:24 (QP5 v5.252.13127.32847) */
ALTER TABLE DBP_ACC_PRINCIP
   DROP PRIMARY KEY CASCADE;

DROP TABLE DBP_ACC_PRINCIP CASCADE CONSTRAINTS;
DROP SEQUENCE DBP_ACC_PRINCIP_SEQ;

CREATE TABLE DBP_ACC_PRINCIP
(
   ACC_PRINCIP_SID   NUMBER CONSTRAINT DBP_ACC_PRINCIP_PK PRIMARY KEY
,  DESCR             VARCHAR2 (100 CHAR)
,  ORDER_BY          NUMBER
);

CREATE SEQUENCE DBP_ACC_PRINCIP_SEQ;

CREATE OR REPLACE TRIGGER DBP_ACC_PRINCIP_TRG
   BEFORE INSERT
   ON DBP_ACC_PRINCIP
   FOR EACH ROW
BEGIN
   SELECT DBP_ACC_PRINCIP_SEQ.NEXTVAL INTO :NEW.ACC_PRINCIP_SID FROM DUAL;
END;