/* Formatted on 12/4/2019 13:00:36 (QP5 v5.252.13127.32847) */
ALTER TABLE DBP_ADOPT_STATUS
   DROP PRIMARY KEY CASCADE;

DROP TABLE DBP_ADOPT_STATUS CASCADE CONSTRAINTS;
DROP SEQUENCE DBP_ADOPT_STATUS_SEQ;

CREATE TABLE DBP_ADOPT_STATUS
(
   ADOPT_STATUS_SID   NUMBER (8) CONSTRAINT DBP_ADOPT_STATUS_PK PRIMARY KEY
,  DESCR              VARCHAR2 (100 CHAR)
,  ORDER_BY           NUMBER (8)
);

CREATE SEQUENCE DBP_ADOPT_STATUS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DBP_ADOPT_STATUS_TRG
   BEFORE INSERT
   ON DBP_ADOPT_STATUS
   FOR EACH ROW
BEGIN
   SELECT DBP_ADOPT_STATUS_SEQ.NEXTVAL INTO :NEW.ADOPT_STATUS_SID FROM DUAL;
END;