/* Formatted on 12/17/2019 13:22:59 (QP5 v5.252.13127.32847) */
DROP TABLE DBP_CTY_ROUND_SCALES CASCADE CONSTRAINTS;

CREATE TABLE DBP_CTY_ROUND_SCALES
(
   CTY_VERSION_SID   NUMBER (8)
                        CONSTRAINT DBP_CTY_ROUND_SCALES_CTY_V_FK
                            REFERENCES GD_CTY_VERSIONS (CTY_VERSION_SID)
,  ROUND_SID         NUMBER (8)
                        CONSTRAINT DBP_CTY_ROUND_SCALES_ROUND_FK
                            REFERENCES ROUNDS (ROUND_SID)
,  SCALE_SID         NUMBER (8)
                        NOT NULL
                        CONSTRAINT DBP_CTY_ROUND_SCALES_SCALE_FK
                            REFERENCES SCALES (SCALE_SID)
,  CONSTRAINT DBP_CTY_ROUND_SCALES_PK PRIMARY KEY
      (CTY_VERSION_SID, ROUND_SID)
);