/* Formatted on 12/4/2019 12:53:12 (QP5 v5.252.13127.32847) */
ALTER TABLE DBP_ESA
   DROP PRIMARY KEY CASCADE;

DROP TABLE DBP_ESA CASCADE CONSTRAINTS;
DROP SEQUENCE DBP_ESA_SEQ;

CREATE TABLE DBP_ESA
(
   ESA_SID       NUMBER (8) CONSTRAINT DBP_ESA_PK PRIMARY KEY
,  ESA_ID        VARCHAR2 (50 BYTE) CONSTRAINT DBP_ESA_ID_UNQ UNIQUE
,  DESCR         VARCHAR2 (200 BYTE)
,  REV_EXP_SID   NUMBER (8)
                    CONSTRAINT DBP_ESA_REV_EXP_FK
                        REFERENCES DFM_REV_EXP (REV_EXP_SID)
,  ORDER_BY      NUMBER (8)
);

CREATE SEQUENCE DBP_ESA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DBP_ESA_TRG
   BEFORE INSERT
   ON DBP_ESA
   FOR EACH ROW
BEGIN
   SELECT DBP_ESA_SEQ.NEXTVAL INTO :NEW.ESA_SID FROM DUAL;
END;