/* Formatted on 12/4/2019 12:55:42 (QP5 v5.252.13127.32847) */
ALTER TABLE DBP_SOURCES
   DROP PRIMARY KEY CASCADE;

DROP TABLE DBP_SOURCES CASCADE CONSTRAINTS;
DROP SEQUENCE DBP_SOURCES_SEQ;

CREATE TABLE DBP_SOURCES
(
   SOURCE_SID   NUMBER (8) CONSTRAINT DBP_SOURCES_PK PRIMARY KEY
,  DESCR        VARCHAR2 (100 CHAR)
,  ORDER_BY     NUMBER (8)
);

CREATE SEQUENCE DBP_SOURCES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DBP_SOURCES_TRG
   BEFORE INSERT
   ON DBP_SOURCES
   FOR EACH ROW
BEGIN
   SELECT DBP_SOURCES_SEQ.NEXTVAL INTO :NEW.SOURCE_SID FROM DUAL;
END;