INSERT INTO CFG_DYNAMIC_LOV_TYPES(DYN_SID, DESCR) VALUES (0, 'List of Values without any dependencies');
INSERT INTO CFG_DYNAMIC_LOV_TYPES(DYN_SID, DESCR) VALUES (1, 'List of Values dependent on another List of Values');
INSERT INTO CFG_DYNAMIC_LOV_TYPES(DYN_SID, DESCR) VALUES (2, 'List of Values dependent on answers/entries/scores/indices from another APP');
COMMIT;
INSERT INTO CFG_QSTNNR_STATUS SELECT * FROM FGD_CFG_STATUS;
COMMIT;
INSERT INTO CFG_RESPONSE_TYPES(CFG_TYPE, DESCR) VALUES (1, 'Regular');
INSERT INTO CFG_RESPONSE_TYPES(CFG_TYPE, DESCR) VALUES (2, 'Other');
INSERT INTO CFG_RESPONSE_TYPES(CFG_TYPE, DESCR) VALUES (3, 'All');
INSERT INTO CFG_RESPONSE_TYPES(CFG_TYPE, DESCR) VALUES (4, 'Exclusion');
COMMIT;
Insert into CFG_COMPLIANCE_SOURCES (COMPLIANCE_SOURCE_SID,COMPLIANCE_SOURCE_ID,YEAR,DESCR,APP_SID,IS_PRIVATE) values (1,'DBP',-1,'SCOPAX Draft Budgetary plans ',2,0);
Insert into CFG_COMPLIANCE_SOURCES (COMPLIANCE_SOURCE_SID,COMPLIANCE_SOURCE_ID,YEAR,DESCR,APP_SID,IS_PRIVATE) values (2,'SCP1',1,'SCOPAX Stability and convergence programmes module for current year',1,0);
Insert into CFG_COMPLIANCE_SOURCES (COMPLIANCE_SOURCE_SID,COMPLIANCE_SOURCE_ID,YEAR,DESCR,APP_SID,IS_PRIVATE) values (3,'ESTA1',0,'Eurostat for current year',1,1);
Insert into CFG_COMPLIANCE_SOURCES (COMPLIANCE_SOURCE_SID,COMPLIANCE_SOURCE_ID,YEAR,DESCR,APP_SID,IS_PRIVATE) values (4,'ESTAT',-1,'Eurostat for prev year',1,1);
Insert into CFG_COMPLIANCE_SOURCES (COMPLIANCE_SOURCE_SID,COMPLIANCE_SOURCE_ID,YEAR,DESCR,APP_SID,IS_PRIVATE) values (5,'AMECO',-1,'AMECO Autumn forecast of previous year ?',1,1);
Insert into CFG_COMPLIANCE_SOURCES (COMPLIANCE_SOURCE_SID,COMPLIANCE_SOURCE_ID,YEAR,DESCR,APP_SID,IS_PRIVATE) values (6,'AMECO',1,'AMECO spring forecast of next year ?',1,1);
COMMIT;
INSERT INTO CFG_EUROSTAT_COVERAGE SELECT * FROM FGD_EUROSTAT_COVERAGE;
COMMIT;

INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, NULL, 202, 1, 'LG_VALUE', ':EUROSTAT_CFG');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, NULL, 203, 1, 'RG_VALUE', ':EUROSTAT_CFG');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, NULL, 204, 1, 'CG_VALUE', ':EUROSTAT_CFG');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, NULL, 205, 1, 'SS_VALUE', ':EUROSTAT_CFG');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, NULL, 207, 0, NULL, '1');

INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, 1, 202, 1, 'LG_VALUE', ':EUROSTAT_CFG * (1 - :NUMERIC_VALUE / 100)');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, 1, 203, 1, 'RG_VALUE', ':EUROSTAT_CFG * (1 - :NUMERIC_VALUE / 100)');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, 1, 204, 1, 'CG_VALUE', ':EUROSTAT_CFG * (1 - :NUMERIC_VALUE / 100)');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, 1, 205, 1, 'SS_VALUE', ':EUROSTAT_CFG * (1 - :NUMERIC_VALUE / 100)');
INSERT INTO CFG_COVERAGE_CONDITIONS(QUESTION_VERSION_SID, NUMERIC_VALUE, LOV_SID, NEED_EUROSTAT_CFG, EUROSTAT_CFG, DESCR)
VALUES (5, 1, 207, 0, NULL, '1 - :NUMERIC_VALUE / 100');
COMMIT;