/* Formatted on 11/28/2019 19:09:07 (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW VW_ROUNDS
AS
   SELECT R.ROUND_SID
,         R.YEAR
,         R.DESCR
,         R.PERIOD_SID
,         R.VERSION
,         R.ACTIVATED
,         PER.DESCR AS PERIOD_DESCR
,         PER.ORDER_PERIOD
,         PER.PERIOD_ID
,         PER.ROUND_TYPE
,         PER.IS_FULL
     FROM ROUNDS R
          LEFT JOIN PERIODS PER ON PER.PERIOD_SID = R.PERIOD_SID;
