CREATE OR REPLACE FORCE VIEW VW_FDMS_INDICATORS_MAPPINGS
AS
    SELECT M.*
         , I.INDICATOR_ID
         , I.PROVIDER_ID
         , I.PERIODICITY_ID
         , S.SCALE_ID
         , S.DESCR AS "SCALE_DESCR"
         , S.EXPONENT AS "SCALE_EXPONENT"
      FROM FDMS_INDICATOR_MAPPINGS M
      JOIN VW_FDMS_INDICATORS I
        ON M.INDICATOR_SID = I.INDICATOR_SID
      JOIN FDMS_SCALES S
        ON M.SCALE_SID = S.SCALE_SID;
