/* Formatted on 15-09-2020 13:00:08 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_AMECO_PH_DATA
AS
   SELECT I.INDICATOR_ID, D.*, I.PERIODICITY_ID, COALESCE(S.SCALE_ID, 'UNIT') SCALE_ID
     FROM FDMS_AMECO_PH_DATA  D
          JOIN VW_FDMS_INDICATORS I ON I.INDICATOR_SID = D.INDICATOR_SID
          LEFT JOIN
          (
             SELECT CS.COUNTRY_ID, CS.INDICATOR_SID, S.SCALE_ID
               FROM FDMS_CTY_INDICATOR_SCALES CS JOIN FDMS_SCALES S ON S.SCALE_SID = CS.SCALE_SID
          ) S
             ON S.COUNTRY_ID = D.COUNTRY_ID AND S.INDICATOR_SID = I.INDICATOR_SID;