/* Formatted on 25-09-2020 19:03:27 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_CTY_INDICATOR_SCALES
AS
   SELECT CS.*
        , I.INDICATOR_ID
        , I.PERIODICITY_ID
        , I.PROVIDER_ID
        , S.SCALE_ID
        , S.DESCR AS SCALE_DESCR
     FROM FDMS_CTY_INDICATOR_SCALES  CS
          JOIN VW_FDMS_INDICATORS I ON I.INDICATOR_SID = CS.INDICATOR_SID
          JOIN FDMS_SCALES S ON S.SCALE_SID = CS.SCALE_SID;
