/* Formatted on 08-10-2020 17:13:04 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_DT_LINE_HEADERS
AS
   SELECT *
     FROM (SELECT LH.LINE_SID, LH.HEADER, CT.COL_TYPE_ID
             FROM FDMS_DT_LINE_HEADERS  LH
                  JOIN FDMS_DT_COL_TYPES CT ON CT.COL_TYPE_SID = LH.COL_TYPE_SID)
          PIVOT
             (MIN(HEADER)
             FOR COL_TYPE_ID
             IN ('DATA' DATA, 'ALT_DATA' ALT_DATA, 'ALT2_DATA' ALT2_DATA));