/* Formatted on 08-10-2020 17:27:18 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_DT_TABLE_LINES
AS
   SELECT T.TABLE_SID
        , T.TABLE_ID
        , LT.LINE_TYPE_ID
        , L.*
        , TL.LINE_ID
        , TL.STYLES
        , TL.LINE_SPAN
        , CT.COL_TYPE_ID                       COL_TYPE_SPAN
        , TL.SPAN_YEARS_OFFSET
        , TL.USE_CTY_SCALE
        , TL.ORDER_BY
        , COALESCE(LI.DATA, LH.DATA)           DATA
        , COALESCE(LI.ALT_DATA, LH.ALT_DATA)   ALT_DATA
        , COALESCE(LI.ALT2_DATA, LH.ALT2_DATA) ALT2_DATA
     FROM FDMS_DT_TABLE_LINES  TL
          JOIN FDMS_DT_TABLES T ON T.TABLE_SID = TL.TABLE_SID
          JOIN FDMS_DT_LINES L ON L.LINE_SID = TL.LINE_SID
          JOIN FDMS_DT_LINE_TYPES LT ON LT.LINE_TYPE_SID = L.LINE_TYPE_SID
          LEFT JOIN FDMS_DT_COL_TYPES CT ON CT.COL_TYPE_SID = TL.COL_TYPE_SID_SPAN
          LEFT JOIN VW_FDMS_DT_LINE_HEADERS LH ON LH.LINE_SID = L.LINE_SID
          LEFT JOIN VW_FDMS_DT_LINE_INDICATORS LI ON LI.TABLE_LINE_SID = TL.TABLE_LINE_SID;