/* Formatted on 01-09-2020 13:40:54 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_DT_TABLE_COLS
AS
   SELECT T.TABLE_SID
        , T.TABLE_ID
        , CT.COL_TYPE_ID
        , C.YEAR_VALUE
        , C.QUARTER
        , COALESCE(C.DESCR, CT.DESCR) DESCR
        , TC.USE_CTY_SCALE
        , TC.ORDER_BY
     FROM FDMS_DT_TABLE_COLS  TC
          JOIN FDMS_DT_TABLES T ON T.TABLE_SID = TC.TABLE_SID
          JOIN FDMS_DT_COLS C ON C.COL_SID = TC.COL_SID
          JOIN FDMS_DT_COL_TYPES CT ON CT.COL_TYPE_SID = C.COL_TYPE_SID;