/* Formatted on 08-10-2020 17:19:38 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_DT_LINE_INDICATORS
AS
   SELECT *
     FROM (
             SELECT LI.TABLE_LINE_SID, I.INDICATOR_ID, CT.COL_TYPE_ID
               FROM FDMS_DT_LINE_INDICATORS  LI
                    JOIN FDMS_DT_COL_TYPES CT ON CT.COL_TYPE_SID = LI.COL_TYPE_SID
                    JOIN VW_FDMS_INDICATORS I ON I.INDICATOR_SID = LI.INDICATOR_SID
          )
          PIVOT
             (MIN(INDICATOR_ID)
             FOR COL_TYPE_ID
             IN ('DATA' DATA, 'ALT_DATA' ALT_DATA, 'ALT2_DATA' ALT2_DATA));