/* Formatted on 27-01-2020 16:31:40 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_FDMS_INDICATORS
AS
    SELECT I.INDICATOR_SID, C.*, P.PROVIDER_ID, P.PROVIDER_SID, P.DATA_SOURCE, I.PERIODICITY_ID, I.TRANSFORMATION_SID
      FROM FDMS_INDICATORS  I
           JOIN FDMS_INDICATOR_CODES C ON C.INDICATOR_CODE_SID = I.INDICATOR_CODE_SID
           JOIN FDMS_PROVIDERS P ON P.PROVIDER_SID = I.PROVIDER_SID;
