CREATE OR REPLACE FORCE VIEW VW_FDMS_REPORT_INDICATORS
AS
    SELECT I.*, C.INDICATOR_ID, R.REPORT_ID, C.DESCR
      FROM FDMS_REPORT_INDICATORS I
           JOIN FDMS_INDICATOR_CODES C ON C.INDICATOR_CODE_SID = I.INDICATOR_CODE_SID
           JOIN FDMS_REPORTS R ON R.REPORT_SID = I.REPORT_SID;
