ALTER TABLE AGG_INDICATOR_DATA
   DROP PRIMARY KEY CASCADE;
/
DROP TABLE AGG_INDICATOR_DATA CASCADE CONSTRAINTS;
/
DROP SEQUENCE AGG_INDICATOR_DATA_SEQ;
/
CREATE TABLE AGG_INDICATOR_DATA
(
    AGG_INDICATOR_DATA_SID   NUMBER(8)
                                CONSTRAINT AGG_IND_DATA_PK PRIMARY KEY,
	ROUND_SID                NUMBER(8) NOT NULL
	                             CONSTRAINT AGG_IND_DATA_ROUND_FK
                                                        REFERENCES ROUNDS (ROUND_SID),
	INDICATOR_SID            NUMBER(8) NOT NULL
	                             CONSTRAINT AGG_IND_DATA_INDICATOR_FK
                                                        REFERENCES INDICATORS (INDICATOR_SID),
	COUNTRY_ID               VARCHAR2(12 BYTE) NOT NULL
	                             CONSTRAINT AGG_IND_DATA_COUNTRY_FK
                                                        REFERENCES GEO_AREAS (GEO_AREA_ID),
	START_YEAR               NUMBER(4,0) NOT NULL,
	VECTOR                   VARCHAR2(4000 BYTE) NOT NULL,
	LAST_CHANGE_USER         VARCHAR2(20 BYTE),
	LAST_CHANGE_DATE         DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT AGG_IND_DATA_UNQ UNIQUE ( ROUND_SID, INDICATOR_SID, COUNTRY_ID)
);
/
CREATE SEQUENCE AGG_INDICATOR_DATA_SEQ;
/
CREATE OR REPLACE TRIGGER AGG_INDICATOR_DATA_TRG
   BEFORE INSERT
   ON AGG_INDICATOR_DATA
   FOR EACH ROW
BEGIN
   SELECT AGG_INDICATOR_DATA_SEQ.NEXTVAL INTO :NEW.AGG_INDICATOR_DATA_SID FROM DUAL;
END;
/
