ALTER TABLE AGG_LINE_DATA
   DROP PRIMARY KEY CASCADE;
/
DROP TABLE AGG_LINE_DATA CASCADE CONSTRAINTS;
/
DROP SEQUENCE AGG_LINE_DATA_SEQ;
/
CREATE TABLE AGG_LINE_DATA
(
    AGG_LINE_DATA_SID        NUMBER(8)
                                CONSTRAINT AGG_LINE_DATA_PK PRIMARY KEY,
	ROUND_SID                NUMBER(8) NOT NULL
	                             CONSTRAINT AGG_LINE_DATA_ROUND_FK
                                                        REFERENCES ROUNDS (ROUND_SID),
	LINE_ID                  VARCHAR2(10 BYTE) NOT NULL,
	COUNTRY_ID               VARCHAR2(12 BYTE) NOT NULL
	                             CONSTRAINT AGG_INDICATOR_DATA_COUNTRY_FK
                                                        REFERENCES GEO_AREAS (GEO_AREA_ID),
	START_YEAR               NUMBER(4,0) NOT NULL,
	VECTOR                   VARCHAR2(4000 BYTE) NOT NULL,
	LAST_CHANGE_USER         VARCHAR2(20 BYTE),
	LAST_CHANGE_DATE         DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT AGG_LINE_DATA_UNQ UNIQUE ( ROUND_SID, LINE_ID, COUNTRY_ID)
);
/
CREATE SEQUENCE AGG_LINE_DATA_SEQ;
/
CREATE OR REPLACE TRIGGER AGG_LINE_DATA_TRG
   BEFORE INSERT
   ON AGG_LINE_DATA
   FOR EACH ROW
BEGIN
   SELECT AGG_LINE_DATA_SEQ.NEXTVAL INTO :NEW.AGG_LINE_DATA_SID FROM DUAL;
END;
/
