/* Formatted on 11/28/2019 17:32:25 (QP5 v5.252.13127.32847) */
ALTER TABLE APPLICATIONS
   DROP PRIMARY KEY CASCADE;

DROP TABLE APPLICATIONS CASCADE CONSTRAINTS;
DROP SEQUENCE APPLICATIONS_SEQ;

CREATE TABLE APPLICATIONS
(
   APP_SID            NUMBER (8) CONSTRAINT APPLICATIONS_PK PRIMARY KEY
,  APP_ID             VARCHAR2 (10 BYTE)
                         NOT NULL
                         CONSTRAINT APPLICATIONS_ID_UNQ UNIQUE
,  DESCR              VARCHAR2 (500 BYTE)
,  STATUS_SID         NUMBER (8)
                         CONSTRAINT APPLICATIONS_STATUS_FK
                             REFERENCES ST_STATUS_REPO (STATUS_SID)
,  STATUS_DATE        DATE
,  COUNTRY_GROUP_ID   VARCHAR2 (8 BYTE)
,  YEARS_RANGE        NUMBER (8) DEFAULT 0
,  EXTERNAL_ACCESS    NUMBER (1) DEFAULT NULL
,  LINK               VARCHAR2 (500 BYTE) DEFAULT NULL
);

CREATE SEQUENCE APPLICATIONS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER APPLICATIONS_TRG
   BEFORE INSERT
   ON APPLICATIONS
   FOR EACH ROW
BEGIN
   SELECT APPLICATIONS_SEQ.NEXTVAL INTO :NEW.APP_SID FROM DUAL;
END;
