/* Formatted on 07/07/2021 13:35:33 (QP5 v5.313) */
DROP TABLE COUNTRY_GROUPS CASCADE CONSTRAINTS;

CREATE TABLE COUNTRY_GROUPS(
   COUNTRY_GROUP_ID  VARCHAR2(8 BYTE)
                     NOT NULL
                     CONSTRAINT COUNTRY_GROUPS_CTY_GRP_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , COUNTRY_ID        VARCHAR2(12 BYTE)
                     NOT NULL
                     CONSTRAINT COUNTRY_GROUPS_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , ORDER_BY NUMBER(4)
 , IS_ACTIVE         NUMBER(1)
                     DEFAULT 1
                     CONSTRAINT COUNTRY_GROUPS_IS_ACTIVE_CHECK CHECK(IS_ACTIVE IN (0, 1))
 , CONSTRAINT COUNTRY_GROUPS_U01 UNIQUE(COUNTRY_GROUP_ID, COUNTRY_ID)
);

COMMENT ON TABLE COUNTRY_GROUPS IS 'Composition Country Groups';

COMMENT ON COLUMN COUNTRY_GROUPS.COUNTRY_GROUP_ID IS 'Country Group';

COMMENT ON COLUMN COUNTRY_GROUPS.COUNTRY_ID IS 'Country ISO code';
