/* Formatted on 11/29/2019 15:08:36 (QP5 v5.252.13127.32847) */
ALTER TABLE CUST_STORAGE_TEXTS
   DROP PRIMARY KEY CASCADE;

DROP TABLE CUST_STORAGE_TEXTS CASCADE CONSTRAINTS;
DROP SEQUENCE CUST_STORAGE_TEXTS_SEQ;

CREATE TABLE CUST_STORAGE_TEXTS
(
   CUST_STORAGE_TEXT_SID   NUMBER (8)
                              CONSTRAINT CUST_STORAGE_TEXTS_PK PRIMARY KEY
,  ROUND_SID               NUMBER (8)
                              NOT NULL
                              CONSTRAINT CUST_STORAGE_TEXTS_ROUND_FK
                                  REFERENCES ROUNDS (ROUND_SID)
,  TITLE                   VARCHAR2 (50 BYTE)
,  DESCR                   VARCHAR2 (4000 BYTE)
,  OLD_ROUND_SID           NUMBER (8)
);

CREATE SEQUENCE CUST_STORAGE_TEXTS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER CUST_STORAGE_TEXTS_TRG
   BEFORE INSERT
   ON CUST_STORAGE_TEXTS
   FOR EACH ROW
BEGIN
   SELECT CUST_STORAGE_TEXTS_SEQ.NEXTVAL
     INTO :new.CUST_STORAGE_TEXT_SID
     FROM DUAL;
END;