ALTER TABLE GEO_AREA_MAPPINGS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GEO_AREA_MAPPINGS CASCADE CONSTRAINTS;
DROP SEQUENCE GEO_AREA_MAPPINGS_SEQ;

CREATE TABLE GEO_AREA_MAPPINGS
(
   MAPPING_SID          NUMBER NOT NULL CONSTRAINT GEO_AREA_MAPPINGS_PK PRIMARY KEY
,  SOURCE_DESCR         VARCHAR2 (100 BYTE) NOT NULL
,  GEO_AREA_ID          VARCHAR2 (8 BYTE)
                         NOT NULL
                         CONSTRAINT GEO_AREA_MAP_GEO_AREA_ID_FK
                             REFERENCES GEO_AREAS (GEO_AREA_ID)
,  MAPPING_ID            VARCHAR2(30 BYTE)
                              CONSTRAINT GEO_AREA_MPNGS_MAPPING_ID_CHECK CHECK
                              (MAPPING_ID IS NULL OR MAPPING_ID IN ('NEER', 'FDMS'))
,  CONSTRAINT GEO_AREA_MAPPINGS_SRC_UNQ UNIQUE (SOURCE_DESCR, MAPPING_ID)
);

CREATE SEQUENCE GEO_AREA_MAPPINGS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER GEO_AREA_MAPPINGS_TRG
   BEFORE INSERT
   ON GEO_AREA_MAPPINGS
   FOR EACH ROW
BEGIN
   SELECT GEO_AREA_MAPPINGS_SEQ.NEXTVAL INTO :NEW.MAPPING_SID FROM DUAL;
END;
