/* Formatted on 11/27/2019 16:57:52 (QP5 v5.252.13127.32847) */
ALTER TABLE GEO_AREAS
   DROP PRIMARY KEY CASCADE;

DROP TABLE GEO_AREAS CASCADE CONSTRAINTS;

CREATE TABLE GEO_AREAS
(
   GEO_AREA_ID          VARCHAR2 (12 BYTE)
                           CONSTRAINT GEO_AREAS_PK PRIMARY KEY
,  CODEISO3             VARCHAR2 (12 BYTE) NOT NULL CONSTRAINT GEO_AREAS_U01 UNIQUE
,  DESCR                VARCHAR2 (200 BYTE) NOT NULL
,  IS_DISPLAYED         VARCHAR2 (1 BYTE)
                           CONSTRAINT GEO_AREAS_IS_DISPLAYED_CHECK CHECK
                              (IS_DISPLAYED IN ('Y', 'N'))
,  IS_AMECO_REQUESTED   VARCHAR2 (1 BYTE)
                           CONSTRAINT GEO_AREAS_IS_AMECO_CHECK CHECK
                              (IS_AMECO_REQUESTED IN ('Y', 'N'))
,  GEO_AREA_TYPE        VARCHAR2 (20 BYTE)
                           CONSTRAINT GEO_AREAS_TYPE_VALUES CHECK
                              (GEO_AREA_TYPE IN ('COUNTRY', 'COUNTRY_GROUP'))
,  ORDER_BY             NUMBER (4) NOT NULL
,  AMECO_ORDER          NUMBER (4)
,  NEER_ORDER           NUMBER (4)
,  CODE_FGD             NUMBER (4)
,  CODE_IMF             NUMBER (4)
,  CURRENCY             VARCHAR2(3 BYTE)
);

COMMENT ON TABLE GEO_AREAS IS 'Geo Areas Codes';
COMMENT ON COLUMN GEO_AREAS.GEO_AREA_ID IS 'Country ISO code';
COMMENT ON COLUMN GEO_AREAS.CODEISO3 IS 'Country ISO code 3 characters';
COMMENT ON COLUMN GEO_AREAS.DESCR IS 'Country Description';
COMMENT ON COLUMN GEO_AREAS.IS_DISPLAYED IS
   'Display or not this specific Geo Area';
COMMENT ON COLUMN GEO_AREAS.IS_AMECO_REQUESTED IS
   'Country code requested to be retrieved from Ameco';
COMMENT ON COLUMN GEO_AREAS.GEO_AREA_TYPE IS 'Type of the Geo Area';
COMMENT ON COLUMN GEO_AREAS.ORDER_BY IS 'Order for the display of data';
COMMENT ON COLUMN GEO_AREAS.CURRENCY IS 'GEO AREA CURRENCY CODE';
