/* Formatted on 12/2/2019 13:16:06 (QP5 v5.252.13127.32847) */
ALTER TABLE HELP_MSGS
   DROP PRIMARY KEY CASCADE;

DROP TABLE HELP_MSGS CASCADE CONSTRAINTS;
DROP SEQUENCE HELP_MSGS_SEQ;

CREATE TABLE HELP_MSGS
(
   HELP_MSG_SID        NUMBER CONSTRAINT HELP_MSGS_PK PRIMARY KEY
,  DESCR               VARCHAR2 (30 CHAR) DEFAULT 'Default'
,  MESS                VARCHAR2 (4000 CHAR) DEFAULT 'Default'
,  HELP_MSG_TYPE_ID    VARCHAR2 (15 CHAR) NULL
                           CONSTRAINT HELP_MSG_TYPE_FK
                                      REFERENCES HELP_MSG_TYPE (HELP_MSG_TYPE_ID)
);

CREATE SEQUENCE HELP_MSGS_SEQ START WITH 50;
/
CREATE OR REPLACE TRIGGER HELP_MSGS_TRG
   BEFORE INSERT
   ON HELP_MSGS
   FOR EACH ROW
BEGIN
   SELECT HELP_MSGS_SEQ.NEXTVAL INTO :NEW.HELP_MSG_SID FROM DUAL;
END;
/
COMMENT ON TABLE HELP_MSGS IS 'Help messages';
COMMENT ON COLUMN HELP_MSGS.HELP_MSG_SID IS 'Help message SID';
COMMENT ON COLUMN HELP_MSGS.DESCR IS 'Description';
COMMENT ON COLUMN HELP_MSGS.MESS IS 'Message';
/