ALTER TABLE HELP_MSG_TYPE
   DROP PRIMARY KEY CASCADE;

DROP TABLE HELP_MSG_TYPE CASCADE CONSTRAINTS;

CREATE TABLE HELP_MSG_TYPE
(
   HELP_MSG_TYPE_ID        VARCHAR2 (15 CHAR) CONSTRAINT HELP_MSG_TYPE_PK PRIMARY KEY
,  DESCR                   VARCHAR2 (30 CHAR) NOT NULL
);
