/* Formatted on 11/28/2019 12:43:09 (QP5 v5.252.13127.32847) */
ALTER TABLE PARAMS
   DROP PRIMARY KEY CASCADE;

DROP TABLE PARAMS CASCADE CONSTRAINTS;
DROP SEQUENCE PARAMS_SEQ;

CREATE TABLE PARAMS
(
   PARAM_SID    NUMBER NOT NULL CONSTRAINT PARAMS_PK PRIMARY KEY
,  PARAM_ID     VARCHAR2 (30 CHAR) NOT NULL
,  DESCR        VARCHAR2 (100 CHAR)
,  VALUE        VARCHAR2 (100 CHAR)
,  LONG_DESCR   VARCHAR2 (4000 CHAR)
);

CREATE SEQUENCE PARAMS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PARAMS_TRG
   BEFORE INSERT
   ON PARAMS
   FOR EACH ROW
BEGIN
   SELECT PARAMS_SEQ.NEXTVAL INTO :NEW.PARAM_SID FROM DUAL;
END;
