/* Formatted on 01/24/2020 16:33:59 (QP5 v5.252.13127.32847) */
DROP TABLE PERIOD_APPLICATIONS CASCADE CONSTRAINTS;

CREATE TABLE PERIOD_APPLICATIONS
(
  PERIOD_SID       NUMBER (8)
                       NOT NULL
                       CONSTRAINT PERIOD_APPS_ROUND_FK
                           REFERENCES PERIODS (PERIOD_SID)
,  APP_SID          NUMBER
                       NOT NULL
                       CONSTRAINT PERIOD_APPS_APP_FK
                           REFERENCES APPLICATIONS (APP_SID)
, CONSTRAINT PERIOD_APPLICATIONS_UNQ UNIQUE(PERIOD_SID, APP_SID)
);
