/* Formatted on 11/28/2019 16:56:18 (QP5 v5.252.13127.32847) */
ALTER TABLE PERIODS
   DROP PRIMARY KEY CASCADE;

DROP TABLE PERIODS;
DROP SEQUENCE PERIODS_SEQ;

CREATE TABLE PERIODS
(
   PERIOD_SID     NUMBER (8) CONSTRAINT PERIODS_PK PRIMARY KEY
,  PERIOD_ID      VARCHAR2 (3 BYTE) NOT NULL CONSTRAINT PERIODS_ID_UNQ UNIQUE
,  DESCR          VARCHAR2 (50 BYTE) NOT NULL
,  ORDER_PERIOD   NUMBER (4)
,  ROUND_TYPE     CHAR (1 BYTE)
                     CONSTRAINT PERIODS_ROUND_TYPE_CHECK CHECK
                        (ROUND_TYPE IN ('N', 'C'))
,  IS_FULL         VARCHAR2 (1 BYTE) DEFAULT 'N'
                     CONSTRAINT PERIODS_IS_FULL_CHECK CHECK
                        (IS_FULL IN ('Y', 'N'))
,  START_DATE     VARCHAR2 (6 BYTE)
,  END_DATE       VARCHAR2 (6 BYTE)
);

CREATE SEQUENCE PERIODS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PERIODS_TRG
   BEFORE INSERT
   ON PERIODS
   FOR EACH ROW
BEGIN
   SELECT PERIODS_SEQ.NEXTVAL INTO :NEW.PERIOD_SID FROM DUAL;
END;
