/* Formatted on 11/28/2019 17:07:31 (QP5 v5.252.13127.32847) */
ALTER TABLE ROUNDS
   DROP PRIMARY KEY CASCADE;

DROP TABLE ROUNDS;
DROP SEQUENCE ROUNDS_SEQ;

CREATE TABLE ROUNDS
(
   ROUND_SID           NUMBER (8) CONSTRAINT ROUNDS_PK PRIMARY KEY
,  YEAR                NUMBER (4) NOT NULL
,  PERIOD_SID          NUMBER (8)
                          NOT NULL
                          CONSTRAINT ROUNDS_PERIOD_FK
                              REFERENCES PERIODS (PERIOD_SID)
,  DESCR               VARCHAR2 (4000 BYTE)
,  ACTIVATED           NUMBER (1)
                          DEFAULT -1
                          NOT NULL
                          CONSTRAINT ROUNDS_ACTIVED_CHECK CHECK
                             (ACTIVATED IN (-1, 0, 1))
,  ACTIVATION_DATE     DATE
,  ACTIVATION_USER     VARCHAR2 (20 CHAR)
,  VERSION             NUMBER (4) DEFAULT 1 NOT NULL
,  CONSTRAINT ROUNDS_YEAR_PERIOD_VERSION_UNQ UNIQUE ( YEAR, PERIOD_SID, VERSION )
);

CREATE SEQUENCE ROUNDS_SEQ START WITH 200;

CREATE OR REPLACE TRIGGER ROUNDS_TRG
   BEFORE INSERT
   ON ROUNDS
   FOR EACH ROW
BEGIN
   SELECT ROUNDS_SEQ.NEXTVAL INTO :NEW.ROUND_SID FROM DUAL;
END;
