/* Formatted on 11/28/2019 17:33:59 (QP5 v5.252.13127.32847) */
DROP TABLE ROUND_APPLICATIONS CASCADE CONSTRAINTS;

CREATE TABLE ROUND_APPLICATIONS
(
  ROUND_SID       NUMBER (8)
                      NOT NULL
                      CONSTRAINT ROUND_APPS_ROUND_FK
                          REFERENCES ROUNDS (ROUND_SID)
,  APP_SID         NUMBER
                      NOT NULL
                      CONSTRAINT ROUND_APPS_APP_FK
                          REFERENCES APPLICATIONS (APP_SID)
, CONSTRAINT ROUND_APPLICATIONS_UNQ UNIQUE(ROUND_SID, APP_SID)
);
