/* Formatted on 11/28/2019 17:37:54 (QP5 v5.252.13127.32847) */
ALTER TABLE SCALES
   DROP PRIMARY KEY CASCADE;

DROP TABLE SCALES CASCADE CONSTRAINTS;
DROP SEQUENCE SCALES_SEQ;

CREATE TABLE SCALES
(
   SCALE_SID   NUMBER (8) CONSTRAINT SCALES_PK PRIMARY KEY
,  SCALE_ID    VARCHAR2 (100 BYTE) NOT NULL CONSTRAINT SCALES_ID_UNQ UNIQUE
,  DESCR       VARCHAR2 (100 BYTE) NOT NULL
,  ORDER_BY    NUMBER (8) NOT NULL
);

CREATE SEQUENCE SCALES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER SCALES_TRG
   BEFORE INSERT
   ON SCALES
   FOR EACH ROW
BEGIN
   SELECT SCALES_SEQ.NEXTVAL INTO :new.SCALE_SID FROM DUAL;
END;