/* Formatted on 11/28/2019 17:26:26 (QP5 v5.252.13127.32847) */
ALTER TABLE ST_STATUS_REPO
   DROP PRIMARY KEY CASCADE;

DROP TABLE ST_STATUS_REPO CASCADE CONSTRAINTS;
DROP SEQUENCE ST_STATUS_REPO_SEQ;

CREATE TABLE ST_STATUS_REPO
(
   STATUS_SID   NUMBER (8) CONSTRAINT ST_STATUS_REPO_PK PRIMARY KEY
,  STATUS_ID    VARCHAR2 (10 BYTE)
                   NOT NULL
                   CONSTRAINT ST_STATUS_REPO_ID_UNQ UNIQUE
,  DESCR        VARCHAR2 (30 BYTE)
,  APP_DESCR    VARCHAR2 (30 BYTE)
,  TR_DESCR     VARCHAR2 (30 BYTE)
);

CREATE SEQUENCE ST_STATUS_REPO_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ST_STATUS_REPO_TRG
   BEFORE INSERT
   ON ST_STATUS_REPO
   FOR EACH ROW
BEGIN
   SELECT ST_STATUS_REPO_SEQ.NEXTVAL INTO :NEW.STATUS_SID FROM DUAL;
END;