/* Formatted on 11/28/2019 18:16:16 (QP5 v5.252.13127.32847) */
ALTER TABLE STORAGES
   DROP PRIMARY KEY CASCADE;

DROP TABLE STORAGES CASCADE CONSTRAINTS;
DROP SEQUENCE STORAGES_SEQ;

CREATE TABLE STORAGES
(
   STORAGE_SID        NUMBER (8) CONSTRAINT STORAGES_PK PRIMARY KEY
,  STORAGE_ID         VARCHAR2 (8 BYTE) NOT NULL CONSTRAINT STORAGES_ID_UNQ UNIQUE
,  DESCR              VARCHAR2 (100 BYTE)
,  ALT_DESCR          VARCHAR2 (100 BYTE)
,  IS_PERMANENT       VARCHAR2 (1 BYTE)
,  ORDER_BY           NUMBER (8)
,  NEXT_STORAGE_SID   NUMBER (8)
                         CONSTRAINT STORAGES_NEXT_FK
                             REFERENCES STORAGES (STORAGE_SID)
,  IS_CUSTOM          VARCHAR2 (1 BYTE) DEFAULT 'N'
                        CONSTRAINT STORAGES_IS_CUSTOM_CHECK CHECK
                           (IS_CUSTOM IN ('Y', 'N'))
,  IS_FULL            VARCHAR2 (1 BYTE) DEFAULT 'N'
                        CONSTRAINT STORAGES_IS_FULL_CHECK CHECK
                           (IS_FULL IN ('Y', 'N'))
);

CREATE SEQUENCE STORAGES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER STORAGES_TRG
   BEFORE INSERT
   ON STORAGES
   FOR EACH ROW
BEGIN
   SELECT STORAGES_SEQ.NEXTVAL INTO :new.STORAGE_SID FROM DUAL;
END;