/* Formatted on 02/07/2020 14:00:59 (QP5 v5.252.13127.32847) */
ALTER TABLE STORAGE_APPLICATIONS
   DROP PRIMARY KEY CASCADE;

DROP TABLE STORAGE_APPLICATIONS;
DROP SEQUENCE STORAGE_APPLICATIONS_SEQ;

CREATE TABLE STORAGE_APPLICATIONS
(
   STORAGE_APP_SID   NUMBER (8) CONSTRAINT STORAGE_APPLICATIONS_PK PRIMARY KEY
,  STORAGE_SID       NUMBER (8)
                       NOT NULL
                       CONSTRAINT STORAGE_APPS_STORAGE_FK
                           REFERENCES STORAGES (STORAGE_SID)
,  APP_SID           NUMBER (8)
                       NOT NULL
                       CONSTRAINT STORAGE_APPS_APP_FK
                           REFERENCES APPLICATIONS (APP_SID)
);


CREATE SEQUENCE STORAGE_APPLICATIONS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER STORAGE_APPLICATIONS_TRG
   BEFORE INSERT
   ON STORAGE_APPLICATIONS
   FOR EACH ROW
BEGIN
   SELECT STORAGE_APPLICATIONS_SEQ.NEXTVAL INTO :new.STORAGE_APP_SID FROM DUAL;
END;