/* Formatted on 11/28/2019 18:41:12 (QP5 v5.252.13127.32847) */
ALTER TABLE TEMPLATE_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE TEMPLATE_TYPES CASCADE CONSTRAINTS;
DROP SEQUENCE TEMPLATE_TYPES_SEQ;

CREATE TABLE TEMPLATE_TYPES
(
   TEMPLATE_TYPE_SID   NUMBER (8) CONSTRAINT TEMPLATE_TYPES_PK PRIMARY KEY
,  TEMPLATE_TYPE_ID    VARCHAR2 (30 BYTE)
                          NOT NULL
                          CONSTRAINT TEMPLATE_TYPES_IN_UNQ UNIQUE
,  DESCR               VARCHAR2 (150 BYTE)
);

COMMENT ON TABLE TEMPLATE_TYPES IS 'Templates';
COMMENT ON COLUMN TEMPLATE_TYPES.TEMPLATE_TYPE_SID IS 'Template SID';
COMMENT ON COLUMN TEMPLATE_TYPES.TEMPLATE_TYPE_ID IS 'Template ID';
COMMENT ON COLUMN TEMPLATE_TYPES.DESCR IS 'Template type description';


CREATE SEQUENCE TEMPLATE_TYPES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TEMPLATE_TYPES_TRG
   BEFORE INSERT
   ON TEMPLATE_TYPES
   FOR EACH ROW
BEGIN
   SELECT TEMPLATE_TYPES_SEQ.NEXTVAL INTO :NEW.TEMPLATE_TYPE_SID FROM DUAL;
END;