CREATE OR REPLACE FORCE VIEW VW_HICP_INDICATORS_DATA
AS
               SELECT I.*, D.COUNTRY_ID, D.START_YEAR, D.TIMESERIE_DATA
                 FROM VW_HICP_INDICATORS I
      LEFT OUTER JOIN HICP_INDICATOR_DATA D
                   ON D.INDICATOR_SID = I.INDICATOR_SID;
