/* Formatted on 25-11-2020 17:06:22 (QP5 v5.313) */
DROP TABLE TASK_COUNTRIES CASCADE CONSTRAINTS;

CREATE TABLE TASK_COUNTRIES(
   TASK_SID      NUMBER(8) CONSTRAINT TASK_COUNTRIES_TASK_FK REFERENCES TASKS(TASK_SID)
 , COUNTRY_ID    VARCHAR2(12) CONSTRAINT TASK_COUNTRIES_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , ROUND_SID     NUMBER(8) CONSTRAINT TASK_COUNTRIES_ROUND_FK REFERENCES ROUNDS(ROUND_SID)
 , STORAGE_SID   NUMBER(8)
                 CONSTRAINT TASK_COUNTRIES_STORAGE_FK REFERENCES STORAGES(STORAGE_SID)
 , TASK_RUN_SID  NUMBER(8)
                 NOT NULL
                 CONSTRAINT TASK_COUNTRIES_RUN_FK REFERENCES TASK_RUNS(TASK_RUN_SID)
 , CONSTRAINT TASK_COUNTRIES_UNQ PRIMARY KEY(TASK_SID, COUNTRY_ID, ROUND_SID, STORAGE_SID)
);
