ALTER TABLE TASK_STATUSES
   DROP PRIMARY KEY CASCADE;
   
DROP TABLE TASK_STATUSES CASCADE CONSTRAINTS;
DROP SEQUENCE TASK_STATUSES_SEQ;

CREATE TABLE TASK_STATUSES
(
   TASK_STATUS_SID  NUMBER (8) CONSTRAINT TASK_STATUSES_PK PRIMARY KEY
,  TASK_STATUS_ID   VARCHAR2 (16) NOT NULL CONSTRAINT TASK_STATUSES_ID_UNQ UNIQUE
,  DESCR            VARCHAR2 (128)
);

CREATE SEQUENCE TASK_STATUSES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TASK_STATUSES_TRG
   BEFORE INSERT
   ON TASK_STATUSES
   FOR EACH ROW
BEGIN
   SELECT TASK_STATUSES_SEQ.NEXTVAL INTO :NEW.TASK_STATUS_SID FROM DUAL;
END;