/* Formatted on 07-05-2020 13:21:00 (QP5 v5.313) */
ALTER TABLE TASKS
   DROP PRIMARY KEY CASCADE;

DROP TABLE TASKS CASCADE CONSTRAINTS;
DROP SEQUENCE TASKS_SEQ;

CREATE TABLE TASKS(
   TASK_SID  NUMBER(8) CONSTRAINT TASKS_PK PRIMARY KEY
 , TASK_ID   VARCHAR2(32) NOT NULL CONSTRAINT TASKS_ID_UNQ UNIQUE
 , DESCR VARCHAR2(128)
);

CREATE SEQUENCE TASKS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TASKS_TRG
   BEFORE INSERT
   ON TASKS
   FOR EACH ROW
BEGIN
   SELECT TASKS_SEQ.NEXTVAL INTO :NEW.TASK_SID FROM DUAL;
END;