/* Formatted on 07-07-2020 17:12:16 (QP5 v5.313) */
ALTER TABLE TASK_STEP_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE TASK_STEP_TYPES CASCADE CONSTRAINTS;
DROP SEQUENCE TASK_STEP_TYPES_SEQ;

CREATE TABLE TASK_STEP_TYPES(
   TASK_STEP_TYPE_SID  NUMBER(8) CONSTRAINT TASK_STEP_TYPES_PK PRIMARY KEY
 , TASK_STEP_TYPE_ID   VARCHAR2(16) NOT NULL CONSTRAINT TASK_STEP_TYPES_ID_UNQ UNIQUE
 , DESCR VARCHAR2(128)
);

CREATE SEQUENCE TASK_STEP_TYPES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER TASK_STEP_TYPES_TRG
   BEFORE INSERT
   ON TASK_STEP_TYPES
   FOR EACH ROW
BEGIN
   SELECT TASK_STEP_TYPES_SEQ.NEXTVAL INTO :NEW.TASK_STEP_TYPE_SID FROM DUAL;
END;