ALTER TABLE HICP_INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE HICP_INDICATORS CASCADE CONSTRAINTS;
DROP SEQUENCE HICP_INDICATORS_SEQ;

CREATE TABLE HICP_INDICATORS(
   INDICATOR_SID       NUMBER(8) CONSTRAINT HICP_INDICATORS_PK PRIMARY KEY
 , INDICATOR_CODE_SID  NUMBER(8)
                       NOT NULL
                       CONSTRAINT HICP_INDICATORS_CODE_FK
                       REFERENCES HICP_INDICATOR_CODES(INDICATOR_CODE_SID) ON DELETE CASCADE
 , PERIODICITY_ID      VARCHAR2(1)
                       NOT NULL
                       CONSTRAINT HICP_INDICATORS_PERIOD_CHECK CHECK (PERIODICITY_ID IN ('A', 'Q', 'M'))
 , DATA_TYPE           VARCHAR2(2)
                       NOT NULL
                       CONSTRAINT HICP_INDICATORS_TYPE_CHECK CHECK (DATA_TYPE IN ('I', 'T', 'W'))
 , EUROSTAT_CODE       VARCHAR2(100 BYTE)
 , CONSTRAINT HICP_INDICATORS_UNQ UNIQUE(INDICATOR_CODE_SID, PERIODICITY_ID, DATA_TYPE)
);
/
CREATE SEQUENCE HICP_INDICATORS_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER HICP_INDICATORS_TRG
   BEFORE INSERT
   ON HICP_INDICATORS
   FOR EACH ROW
BEGIN
   SELECT HICP_INDICATORS_SEQ.NEXTVAL INTO :NEW.INDICATOR_SID FROM DUAL;
END;
/
COMMENT ON TABLE HICP_INDICATORS IS 'HICP indicators';
COMMENT ON COLUMN HICP_INDICATORS.PERIODICITY_ID IS 'A = Annual, M = Monthly, Q = Quarterly';
COMMENT ON COLUMN HICP_INDICATORS.DATA_TYPE IS 'I = Index, T = constant tax rate, W = weight';
COMMENT ON COLUMN HICP_INDICATORS.EUROSTAT_CODE IS 'data set name|query key';
/
