DROP TABLE HICP_INDICATOR_CODE_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE HICP_INDICATOR_CODE_CATEGORY(
      INDICATOR_ID            VARCHAR2(35 BYTE) NOT NULL
    , CATEGORY_SID            NUMBER(8) NOT NULL
                                        CONSTRAINT HICP_IND_CAT_CATEGORY_FK REFERENCES HICP_CATEGORY(CATEGORY_SID)
    , CONSTRAINT HICP_INDICATOR_CODE_CATEGORY_UQ UNIQUE  (INDICATOR_ID, CATEGORY_SID)
);
