DROP TABLE HICP_CATEGORY_REL CASCADE CONSTRAINTS;

CREATE TABLE HICP_CATEGORY_REL(
    PARENT_CATEGORY_SID  NUMBER(8) NOT NULL
	                           CONSTRAINT HICP_PARENT_CATEGORY_SID_FK REFERENCES HICP_CATEGORY(CATEGORY_SID)
,   CHILD_CATEGORY_SID   NUMBER(8) NULL
	                           CONSTRAINT HICP_CHILD_CATEGORY_SID_FK REFERENCES HICP_CATEGORY(CATEGORY_SID)
,   CONSTRAINT HICP_CATEGORY_REL_UNQ UNIQUE (PARENT_CATEGORY_SID, CHILD_CATEGORY_SID)
);
