ALTER TABLE HICP_CATEGORY
DROP PRIMARY KEY CASCADE;

DROP TABLE HICP_CATEGORY CASCADE CONSTRAINTS;
DROP SEQUENCE HICP_CATEGORY_SEQ;

CREATE TABLE HICP_CATEGORY(
      CATEGORY_SID        NUMBER(12) CONSTRAINT HICP_CATEGORY_PK PRIMARY KEY
    , CATEGORY_ID         VARCHAR2(20) NOT NULL CONSTRAINT HICP_CATEGORY_ID_UNQ UNIQUE
    , DESCR               VARCHAR2(100)
    , ROOT_INDICATOR_ID   VARCHAR2(35 BYTE) NULL
                          CONSTRAINT HICP_CATEGORY_ROOT_CHECK CHECK (ROOT_INDICATOR_ID IN ('CP00', '_AGG'))
    , BASE_INDICATOR_ID   VARCHAR2(35 BYTE) NULL
    , OWNER               VARCHAR2(35 BYTE) DEFAULT 'DEFAULT'
    , ORDER_BY            NUMBER(8)
    , CONSTRAINT HICP_CATEGORY_UNIQUE UNIQUE(CATEGORY_ID, OWNER)
);

CREATE SEQUENCE HICP_CATEGORY_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER HICP_CATEGORY_TRG
   BEFORE INSERT
   ON HICP_CATEGORY
   FOR EACH ROW
BEGIN
   SELECT HICP_CATEGORY_SEQ.NEXTVAL INTO :NEW.CATEGORY_SID FROM DUAL;
END;
/
COMMENT ON COLUMN HICP_CATEGORY.ROOT_INDICATOR_ID IS 'Root indicator of the indicators tree, CP00 or _AGG';
COMMENT ON COLUMN HICP_CATEGORY.BASE_INDICATOR_ID IS 'The base indicator used for calculation';
COMMENT ON COLUMN HICP_CATEGORY.OWNER IS 'Default categories have predefined owner: "Default"';
/
