DROP TABLE HICP_INDICATOR_CODE_REL CASCADE CONSTRAINTS;

CREATE TABLE HICP_INDICATOR_CODE_REL(
    PARENT_CODE_SID  NUMBER(8) NOT NULL
	                           CONSTRAINT HICP_PARENT_SID_FK REFERENCES HICP_INDICATOR_CODES(INDICATOR_CODE_SID)
,   CHILD_CODE_SID   NUMBER(8) NULL
	                           CONSTRAINT HICP_CHILD_SID_FK REFERENCES HICP_INDICATOR_CODES(INDICATOR_CODE_SID)
,   CONSTRAINT HICP_INDICATOR_CODE_REL_UNQ UNIQUE (PARENT_CODE_SID, CHILD_CODE_SID)
);
