/* Formatted on 30-09-2021 15:58:00 (QP5 v5.313) */
DROP TYPE "GUARANTEEARRAY";
/

CREATE OR REPLACE TYPE "GUARANTEEOBJECT" AS OBJECT(
   COUNTRY_ID VARCHAR2(8)
 , GUARANTEE_SID NUMBER(12)
 , REASON_SID NUMBER(8)
 , DESCR VARCHAR2(4000)
 , ADOPT_DATE_YR NUMBER(4)
 , ADOPT_DATE_MH NUMBER(2)
 , MAX_CONTINGENT_LIAB NUMBER
 , ESTIMATED_TAKE_UP NUMBER
);
/

CREATE OR REPLACE TYPE "GUARANTEEARRAY" IS TABLE OF "GUARANTEEOBJECT";
/