DROP TYPE "VARCHAROBJECT_LIST" FORCE;
/
DROP TYPE "VARCHAROBJECT" FORCE;
/
CREATE OR REPLACE TYPE "VARCHAROBJECT" AS OBJECT (val VARCHAR2(50), num NUMBER);
/
CREATE OR REPLACE TYPE "VARCHAROBJECT_LIST" AS TABLE OF VARCHAROBJECT;
/
