DROP TYPE "VECTOROBJECT" FORCE;
/
CREATE OR REPLACE TYPE "VECTOROBJECT" AS OBJECT (
      VARIABLE_ID              VARCHAR2 (40 BYTE)
,     START_YEAR               NUMBER (4, 0)
,     VECTOR                   VARCHAR2 (4000 BYTE)
);
/
DROP TYPE "VECTORARRAY" FORCE;
/
CREATE OR REPLACE  TYPE "VECTORARRAY" IS TABLE OF "VECTOROBJECT";
/

