/* Formatted on 17-08-2020 13:26:43 (QP5 v5.313) */
DROP TABLE ST_ACTION_ALLOWED_STATUSES CASCADE CONSTRAINTS;

CREATE TABLE ST_ACTION_ALLOWED_STATUSES(
   ACTION_SID  NUMBER(8)
               NOT NULL
               CONSTRAINT ST_ACTION_ALLOWED_STS_ACT_FK REFERENCES ST_ACTIONS(ACTION_SID)
 , STATUS_SID  NUMBER(8)
               NOT NULL
               CONSTRAINT ST_ACTION_ALLOWED_STS_ST_FK REFERENCES ST_STATUS_REPO(STATUS_SID)
 , CONSTRAINT ST_ACTION_ALLOWED_STATUSES_UNQ UNIQUE(ACTION_SID, STATUS_SID)
);