/* Formatted on 11-05-2020 13:02:12 (QP5 v5.313) */
ALTER TABLE ST_CTY_STATUS_CURR
   DROP PRIMARY KEY CASCADE;

DROP TABLE ST_CTY_STATUS_CURR CASCADE CONSTRAINTS;
DROP SEQUENCE ST_CTY_STATUS_CURR_SEQ;

CREATE TABLE ST_CTY_STATUS_CURR(
   CTY_STATUS_CURR_SID  NUMBER(12) CONSTRAINT ST_CTY_STATUS_CURR_PK PRIMARY KEY
 , ROUND_SID            NUMBER(8)
                        NOT NULL
                        CONSTRAINT ST_CTY_STATUS_CURR_ROUND_FK REFERENCES ROUNDS(ROUND_SID)
 , APP_SID              NUMBER(8)
                        NOT NULL
                        CONSTRAINT ST_CTY_STATUS_CURR_APP_FK
                        REFERENCES APPLICATIONS(APP_SID)
 , COUNTRY_ID           VARCHAR2(8)
                        NOT NULL
                        CONSTRAINT ST_CTY_STATUS_CURR_CTY_FK
                        REFERENCES GEO_AREAS(GEO_AREA_ID)
 , STATUS_SID           NUMBER(8)
                        NOT NULL
                        CONSTRAINT ST_CTY_STATUS_CURR_STATUS_FK
                        REFERENCES ST_STATUS_REPO(STATUS_SID)
 , STORAGE_SID          NUMBER(8)
                        CONSTRAINT ST_CTY_STATUS_CURR_STORAGE_FK
                        REFERENCES STORAGES(STORAGE_SID)
 , CUST_TEXT_SID        NUMBER(8)
                        CONSTRAINT ST_CTY_STATUS_CURR_TEXT_FK
                        REFERENCES CUST_STORAGE_TEXTS(CUST_STORAGE_TEXT_SID)
 , LAST_CHANGE_DATE DATE
 , UPDATE_USER VARCHAR2(16 BYTE)
 , CONSTRAINT ST_CTY_STATUS_CURR_UNQ UNIQUE
      (APP_SID
     , COUNTRY_ID
     , ROUND_SID
     , STORAGE_SID
     , CUST_TEXT_SID)
);

CREATE SEQUENCE ST_CTY_STATUS_CURR_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ST_CTY_STATUS_CURR_TRG
   BEFORE INSERT
   ON ST_CTY_STATUS_CURR
   FOR EACH ROW
BEGIN
   SELECT ST_CTY_STATUS_CURR_SEQ.NEXTVAL INTO :NEW.CTY_STATUS_CURR_SID FROM DUAL;
END;