/* Formatted on 17-08-2020 13:46:41 (QP5 v5.313) */
ALTER TABLE ST_MAIL_NOTIFICATIONS
   DROP PRIMARY KEY CASCADE;

DROP TABLE ST_MAIL_NOTIFICATIONS CASCADE CONSTRAINTS;
DROP SEQUENCE ST_MAIL_NOTIFICATIONS_SEQ;

CREATE TABLE ST_MAIL_NOTIFICATIONS(
   MAIL_NOTIFICATION_SID  NUMBER(8) CONSTRAINT ST_MAIL_NOTIFICATIONS_PK PRIMARY KEY
 , APP_SID                NUMBER(8)
                          NOT NULL
                          CONSTRAINT ST_MAIL_NOTIFICATIONS_APP_FK REFERENCES APPLICATIONS(APP_SID)
 , COUNTRY_ID             VARCHAR2(8)
                          CONSTRAINT ST_MAIL_NOTIFICATIONS_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , ACTION_SID             NUMBER(8)
                          NOT NULL
                          CONSTRAINT ST_MAIL_NOTIFICATIONS_ACT_FK REFERENCES ST_ACTIONS(ACTION_SID)
 , CONSTRAINT ST_MAIL_NOTIFICATIONS_UNQ UNIQUE(APP_SID, COUNTRY_ID, ACTION_SID)
);

CREATE SEQUENCE ST_MAIL_NOTIFICATIONS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ST_MAIL_NOTIFICATIONS_TRG
   BEFORE INSERT
   ON ST_MAIL_NOTIFICATIONS
   FOR EACH ROW
BEGIN
   SELECT ST_MAIL_NOTIFICATIONS_SEQ.NEXTVAL INTO :NEW.MAIL_NOTIFICATION_SID FROM DUAL;
END;