/* Formatted on 04-08-2020 16:11:00 (QP5 v5.313) */
DROP TABLE ST_MAIL_RECIPIENTS CASCADE CONSTRAINTS;

CREATE TABLE ST_MAIL_RECIPIENTS(
   MAIL_NOTIFICATION_SID  NUMBER(8)
                          NOT NULL
                          CONSTRAINT ST_MAIL_RECIPIENTS_FK
                          REFERENCES ST_MAIL_NOTIFICATIONS(MAIL_NOTIFICATION_SID)
 , RECIPIENT_EMAIL        VARCHAR2(100) NOT NULL
 , CONSTRAINT ST_MAIL_RECIPIENTS_UNQ UNIQUE(MAIL_NOTIFICATION_SID, RECIPIENT_EMAIL)
);