/* Formatted on 26-05-2020 11:53:20 (QP5 v5.313) */
ALTER TABLE CYCLICAL_ADJUSTMENT_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE CYCLICAL_ADJUSTMENT_TYPES CASCADE CONSTRAINTS;
DROP SEQUENCE CYCLICAL_ADJUSTMENT_TYPES_SEQ;

CREATE TABLE CYCLICAL_ADJUSTMENT_TYPES(
   CYCLICAL_ADJUSTMENT_TYPE_SID  NUMBER(4)
                                 CONSTRAINT CYCLICAL_ADJUSTMENT_TYPES_PK PRIMARY KEY
 , DESCR                         VARCHAR2(100 BYTE)
                                 NOT NULL
                                 CONSTRAINT CYCLICAL_ADJUSTMENT_TYPES_UNQ UNIQUE
);

CREATE SEQUENCE CYCLICAL_ADJUSTMENT_TYPES_SEQ START WITH 1;
/

CREATE OR REPLACE TRIGGER CYCLICAL_ADJUSTMENT_TYPES_TRG
   BEFORE INSERT
   ON CYCLICAL_ADJUSTMENT_TYPES
   FOR EACH ROW
BEGIN
   SELECT CYCLICAL_ADJUSTMENT_TYPES_SEQ.NEXTVAL
     INTO :NEW.CYCLICAL_ADJUSTMENT_TYPE_SID
     FROM DUAL;
END;
/