/* Formatted on 14-08-2020 13:07:51 (QP5 v5.313) */
ALTER TABLE FP_TPL_INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE FP_TPL_INDICATORS CASCADE CONSTRAINTS;

DROP SEQUENCE FP_TPL_INDICATORS_SEQ;

CREATE TABLE FP_TPL_INDICATORS(
   TPL_IND_SID    NUMBER(8) CONSTRAINT FP_TPL_INDICATORS_PK PRIMARY KEY
 , TITLE VARCHAR2(20 CHAR)
 , WORKSHEET_SID  NUMBER(8)
                  NOT NULL
                  CONSTRAINT FP_TPL_IND_WSHEET_FK REFERENCES FP_TPL_WORKSHEET(WORKSHEET_SID)
 , INDICATOR_SID  NUMBER(8)
                  NOT NULL
                  CONSTRAINT FP_TPL_IND_IND_FK REFERENCES INDICATORS(INDICATOR_SID)
 , GLOSSARY_SID   NUMBER(8) CONSTRAINT FP_TPL_IND_GLSRY_FK REFERENCES FP_TPL_GLOSSARY(GLOSSARY_SID)
 , ORDER_BY NUMBER(8)
);

COMMENT ON TABLE FP_TPL_INDICATORS IS 'Fiscal Params Template Indicators';
COMMENT ON COLUMN FP_TPL_INDICATORS.TPL_IND_SID IS 'Template indicator SID';
COMMENT ON COLUMN FP_TPL_INDICATORS.TITLE IS 'Worksheet second column title';
COMMENT ON COLUMN FP_TPL_INDICATORS.WORKSHEET_SID IS 'Worksheet SID';
COMMENT ON COLUMN FP_TPL_INDICATORS.INDICATOR_SID IS 'Indicator SID';
COMMENT ON COLUMN FP_TPL_INDICATORS.GLOSSARY_SID IS 'Glossary SID';
COMMENT ON COLUMN FP_TPL_INDICATORS.ORDER_BY IS 'Ordering';

CREATE SEQUENCE FP_TPL_INDICATORS_SEQ START WITH 1;
/

CREATE OR REPLACE TRIGGER SET_FP_TPL_INDICATORS
   BEFORE INSERT
   ON FP_TPL_INDICATORS
   FOR EACH ROW
BEGIN
   SELECT FP_TPL_INDICATORS_SEQ.NEXTVAL INTO :NEW.TPL_IND_SID FROM DUAL;
END;
/