/* Formatted on 29-03-2021 17:14:39 (QP5 v5.313) */
ALTER TABLE INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE INDICATORS CASCADE CONSTRAINTS;

DROP SEQUENCE INDICATORS_SEQ;

CREATE TABLE INDICATORS(
   INDICATOR_SID    NUMBER(8) CONSTRAINT INDICATORS_PK PRIMARY KEY
 , INDICATOR_ID     VARCHAR2(35 BYTE) NOT NULL CONSTRAINT INDICATORS_ID_UNQ UNIQUE
 , SOURCE           VARCHAR2(20 BYTE)
 , DESCR            VARCHAR2(1000 BYTE)
 , AMECO_CODE       VARCHAR2(40 BYTE)
 , RATS_ID          VARCHAR2(40 BYTE)
 , IN_LT            VARCHAR2(40 BYTE)
 , IS_CONFIDENTIAL  VARCHAR2(1 BYTE) CHECK(IS_CONFIDENTIAL IN ('Y', 'N'))
 , SOURCE_SID       NUMBER(8) CONSTRAINT INDICATORS_SOURCE_FK REFERENCES SOURCES(SOURCE_SID)
 , WEIGHT           VARCHAR2(3 BYTE)
 , WEIGHT_YEAR      NUMBER(1) CHECK(WEIGHT_YEAR IN (0, -1))
 , SCALE_SID        NUMBER(8) CONSTRAINT INDICATORS_SCALE_FK REFERENCES SCALES(SCALE_SID)
);

COMMENT ON TABLE INDICATORS IS 'Indicators';
COMMENT ON COLUMN INDICATORS.INDICATOR_SID IS 'Indicator SID';
COMMENT ON COLUMN INDICATORS.INDICATOR_ID IS 'Indicator ID';
COMMENT ON COLUMN INDICATORS.SOURCE IS 'Source of the indicator';
COMMENT ON COLUMN INDICATORS.DESCR IS 'Description';
COMMENT ON COLUMN INDICATORS.AMECO_CODE IS 'AMECO Code';
COMMENT ON COLUMN INDICATORS.RATS_ID IS 'RATS ID';
COMMENT ON COLUMN INDICATORS.IN_LT IS 'Link Table Code';
COMMENT ON COLUMN INDICATORS.IS_CONFIDENTIAL IS 'Is the coefficient confidential?';
COMMENT ON COLUMN INDICATORS.SOURCE_SID IS 'Source of the indicator SID';
COMMENT ON COLUMN INDICATORS.WEIGHT IS 'Weighting factor for Aggregates';
COMMENT ON COLUMN INDICATORS.WEIGHT_YEAR IS 'Usage year of Weight for Aggregates';


CREATE SEQUENCE INDICATORS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER INDICATORS_TRG
   BEFORE INSERT
   ON INDICATORS
   FOR EACH ROW
BEGIN
   SELECT INDICATORS_SEQ.NEXTVAL INTO :NEW.INDICATOR_SID FROM DUAL;
END;