ALTER TABLE OG_BASELINE_VARIABLES
   DROP PRIMARY KEY CASCADE;

DROP TABLE OG_BASELINE_VARIABLES CASCADE CONSTRAINTS;
DROP SEQUENCE OG_BASELINE_VARIABLES_SEQ;

CREATE TABLE OG_BASELINE_VARIABLES
(
   VARIABLE_SID       NUMBER (8) CONSTRAINT OG_BASELINE_VARIABLES_PK PRIMARY KEY
,  VARIABLE_ID        VARCHAR2 (10 BYTE) NOT NULL
,  COUNTRY_ID           VARCHAR2 (5 BYTE)
                           CONSTRAINT OG_BLNE_VAR_COUNTRY_FK
                               REFERENCES GEO_AREAS (GEO_AREA_ID)
,  ORDER_BY           NUMBER (4) NOT NULL
,  GROUP_BY_COUNTRY   NUMBER (1,0) DEFAULT 0 NOT NULL
);
/
CREATE SEQUENCE OG_BASELINE_VARIABLES_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER OG_BASELINE_VARIABLES_TRG
   BEFORE INSERT
   ON OG_BASELINE_VARIABLES
   FOR EACH ROW
BEGIN
   SELECT OG_BASELINE_VARIABLES_SEQ.NEXTVAL
     INTO :NEW.VARIABLE_SID
     FROM DUAL;
END;
/
