ALTER TABLE OG_COUNTRY_PARAMS
   DROP PRIMARY KEY CASCADE;

DROP TABLE OG_COUNTRY_PARAMS CASCADE CONSTRAINTS;
DROP SEQUENCE OG_COUNTRY_PARAMS_SEQ;

CREATE TABLE OG_COUNTRY_PARAMS
(
   PARAM_SID       NUMBER (8) CONSTRAINT OG_COUNTRY_PARAMS_PK PRIMARY KEY
,  PARAM_ID        VARCHAR2 (30 BYTE) NOT NULL
,  DATA_TYPE       VARCHAR2 (10 BYTE) NOT NULL
,  DEFAULT_VALUE   VARCHAR2(1 BYTE)
,  DESCR1          VARCHAR2(1000 BYTE)
,  DESCR2          VARCHAR2(1000 BYTE)
,  ORDER_BY        NUMBER (4) NOT NULL
,  CONSTRAINT OG_COUNTRY_PARAMS_UNQ UNIQUE (PARAM_ID)
,  CONSTRAINT OG_CTRY_PRMS_DT_CHECK CHECK (DATA_TYPE IN ('BOOL', 'BOOLNUM', 'STR', 'NUMERIC'))
);
/
CREATE SEQUENCE OG_COUNTRY_PARAMS_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER OG_COUNTRY_PARAMS_TRG
   BEFORE INSERT
   ON OG_COUNTRY_PARAMS
   FOR EACH ROW
BEGIN
   SELECT OG_COUNTRY_PARAMS_SEQ.NEXTVAL
     INTO :NEW.PARAM_SID
     FROM DUAL;
END;
/
