ALTER TABLE OG_COUNTRY_PARAMS_DATA
   DROP PRIMARY KEY CASCADE;

DROP TABLE OG_COUNTRY_PARAMS_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE OG_COUNTRY_PARAMS_DATA_SEQ;

CREATE TABLE OG_COUNTRY_PARAMS_DATA
(
   DATA_SID              NUMBER (8) CONSTRAINT OG_CTRY_PARAMS_DATA_PK PRIMARY KEY
,  ROUND_SID             NUMBER (8)
                            NOT NULL
                            CONSTRAINT OG_CTY_PARAMS_DATA_ROUND_FK
                                REFERENCES ROUNDS (ROUND_SID)
,  COUNTRY_ID            VARCHAR2 (5 BYTE)
                            NOT NULL
                            CONSTRAINT OG_CTRY_PARAMS_DATA_COUNTRY_FK
                                REFERENCES GEO_AREAS (GEO_AREA_ID)
,  COUNTRY_PARAM_SID     NUMBER(8)
                            NOT NULL
                            CONSTRAINT OG_CTRY_PARAMS_PARAM_SID_FK
                                REFERENCES OG_COUNTRY_PARAMS (PARAM_SID)
,  VALUE                 VARCHAR2(100 BYTE)
,  CONSTRAINT OG_CTRY_PARAMS_DATA_UNQ UNIQUE (ROUND_SID, COUNTRY_ID, COUNTRY_PARAM_SID)
);
/
CREATE SEQUENCE OG_COUNTRY_PARAMS_DATA_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER OG_COUNTRY_PARAMS_DATA_TRG
   BEFORE INSERT
   ON OG_COUNTRY_PARAMS_DATA
   FOR EACH ROW
BEGIN
   SELECT OG_COUNTRY_PARAMS_DATA_SEQ.NEXTVAL
     INTO :NEW.DATA_SID
     FROM DUAL;
END;
/

