/* Formatted on 12/2/2019 15:42:45 (QP5 v5.252.13127.32847) */
DROP TABLE OG_INDIC_ORDER;

CREATE TABLE OG_INDIC_ORDER
(
   INDICATOR_SID   NUMBER (8)
                      NOT NULL
                      CONSTRAINT OG_INDIC_ORDER_INDIC_UNQ UNIQUE
                      CONSTRAINT OG_INDIC_ORDER_INDIC_FK
                          REFERENCES INDICATORS (INDICATOR_SID)
,  ORDER_BY        NUMBER (4) NOT NULL
);

COMMENT ON TABLE OG_INDIC_ORDER IS 'Output gap table indicators ordering';
COMMENT ON COLUMN OG_INDIC_ORDER.INDICATOR_SID IS 'Indicator SID';
COMMENT ON COLUMN OG_INDIC_ORDER.ORDER_BY IS 'Ordering';