ALTER TABLE OG_PARAMS
   DROP PRIMARY KEY CASCADE;

DROP TABLE OG_PARAMS CASCADE CONSTRAINTS;
DROP SEQUENCE OG_PARAMS_SEQ;

CREATE TABLE OG_PARAMS
(
   PARAM_SID       NUMBER (8) CONSTRAINT OG_PARAMS_PK PRIMARY KEY
,  ROUND_SID       NUMBER (8)
                     NOT NULL
                     CONSTRAINT OG_PARAMS_ROUND_FK
                         REFERENCES ROUNDS (ROUND_SID)
,  PARAM_ID        VARCHAR2 (30 BYTE) NOT NULL
,  VALUE           VARCHAR2(100 BYTE)
,  CONSTRAINT OG_PARAMS_UNQ UNIQUE (ROUND_SID, PARAM_ID)
);
/
CREATE SEQUENCE OG_PARAMS_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER OG_PARAMS_TRG
   BEFORE INSERT
   ON OG_PARAMS
   FOR EACH ROW
BEGIN
   SELECT OG_PARAMS_SEQ.NEXTVAL
     INTO :NEW.PARAM_SID
     FROM DUAL;
END;
/
