/* Formatted on 11/28/2019 17:43:59 (QP5 v5.252.13127.32847) */
ALTER TABLE SEMI_ELASTICS
   DROP PRIMARY KEY CASCADE;

DROP TABLE SEMI_ELASTICS CASCADE CONSTRAINTS;
DROP SEQUENCE SEMI_ELASTICS_SEQ;

CREATE TABLE SEMI_ELASTICS
(
   SEMI_ELASTICS_SID   NUMBER (8) CONSTRAINT SEMI_ELASTICS_PK PRIMARY KEY
,  ROUND_SID           NUMBER (8)
                          NOT NULL
                          CONSTRAINT SEMI_ELASTICS_ROUND_FK
                              REFERENCES ROUNDS (ROUND_SID)
,  COUNTRY_ID          VARCHAR2 (5 BYTE)
                          NOT NULL
                          CONSTRAINT SEMI_ELASTICS_CTY_FK
                              REFERENCES GEO_AREAS (GEO_AREA_ID)
,  VALUE               NUMBER (17, 15) NOT NULL
,  CONSTRAINT SEMI_ELASTICS_UQ UNIQUE (ROUND_SID, COUNTRY_ID)
);

CREATE SEQUENCE SEMI_ELASTICS_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER SEMI_ELASTICS_TRG
   BEFORE INSERT
   ON SEMI_ELASTICS
   FOR EACH ROW
BEGIN
   SELECT SEMI_ELASTICS_SEQ.NEXTVAL
     INTO :NEW.SEMI_ELASTICS_SID
     FROM DUAL;
END;
/
COMMENT ON TABLE SEMI_ELASTICS IS 'Semi Elasticities';
COMMENT ON COLUMN SEMI_ELASTICS.SEMI_ELASTICS_SID IS 'Semi Elasticity SID';
COMMENT ON COLUMN SEMI_ELASTICS.ROUND_SID IS 'Round SID';
COMMENT ON COLUMN SEMI_ELASTICS.COUNTRY_ID IS 'Country ISO code';
COMMENT ON COLUMN SEMI_ELASTICS.VALUE IS
   'Semi Elasticity Value on Forecast period';
/