/* Formatted on 11/28/2019 16:42:35 (QP5 v5.252.13127.32847) */
ALTER TABLE SOURCES
   DROP PRIMARY KEY CASCADE;

DROP TABLE SOURCES CASCADE CONSTRAINTS;
DROP SEQUENCE SOURCES_SEQ;

CREATE TABLE SOURCES
(
   SOURCE_SID   NUMBER (8) CONSTRAINT SOURCES_PK PRIMARY KEY
,  SOURCE_ID    VARCHAR2 (20 BYTE) NOT NULL CONSTRAINT SOURCES_ID_UNQ UNIQUE
,  DESCR        VARCHAR2 (100 BYTE)
);

COMMENT ON TABLE SOURCES IS 'Sources';
COMMENT ON COLUMN SOURCES.SOURCE_SID IS 'Source SID';
COMMENT ON COLUMN SOURCES.SOURCE_ID IS 'Source ID';
COMMENT ON COLUMN SOURCES.DESCR IS 'Source description';


CREATE SEQUENCE SOURCES_SEQ START WITH 1;


CREATE OR REPLACE TRIGGER SOURCES_TRG
   BEFORE INSERT
   ON SOURCES
   FOR EACH ROW
BEGIN
   SELECT SOURCES_SEQ.NEXTVAL INTO :NEW.SOURCE_SID FROM DUAL;
END;