/* Formatted on 12/2/2019 15:16:57 (QP5 v5.252.13127.32847) */
ALTER TABLE WORKBOOK_GROUPS
   DROP PRIMARY KEY CASCADE;

DROP TABLE WORKBOOK_GROUPS CASCADE CONSTRAINTS;

DROP SEQUENCE WORKBOOK_GROUPS_SEQ;

CREATE TABLE WORKBOOK_GROUPS
(
   WORKBOOK_GROUP_SID   NUMBER (8) CONSTRAINT WORKBOOK_GROUPS_PK PRIMARY KEY
,  WORKBOOK_GROUP_ID    VARCHAR2 (40 BYTE)
                           NOT NULL
                           CONSTRAINT WORKBOOK_GROUPS_ID_UNQ UNIQUE
,  DESCR                VARCHAR2 (1000 BYTE)
);

CREATE SEQUENCE WORKBOOK_GROUPS_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER WORKBOOK_GROUPS_TRG
   BEFORE INSERT
   ON WORKBOOK_GROUPS
   FOR EACH ROW
BEGIN
   SELECT WORKBOOK_GROUPS_SEQ.NEXTVAL INTO :NEW.WORKBOOK_GROUP_SID FROM DUAL;
END;
/
COMMENT ON TABLE WORKBOOK_GROUPS IS 'Workbook Groups';
COMMENT ON COLUMN WORKBOOK_GROUPS.WORKBOOK_GROUP_SID IS
   'Workbook Group SID';
COMMENT ON COLUMN WORKBOOK_GROUPS.WORKBOOK_GROUP_ID IS
   'Workbook Group ID';
COMMENT ON COLUMN WORKBOOK_GROUPS.DESCR IS 'Description';
/