/* Formatted on 12/3/2019 15:56:28 (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW VW_GD_COLS
AS
   SELECT C.*
,         DT.DATA_TYPE_ID
,         DT.DESCR data_type_descr
,         CT.COL_TYPE_ID
,         HM.MESS
     FROM GD_COLS C
          LEFT JOIN GD_COL_TYPES CT ON CT.COL_TYPE_SID = C.COL_TYPE_SID
          LEFT JOIN GD_DATA_TYPES DT ON DT.DATA_TYPE_SID = C.DATA_TYPE_SID
          LEFT JOIN HELP_MSGS HM ON HM.HELP_MSG_SID = C.HELP_MSG_SID;