/* Formatted on 12/3/2019 15:53:32 (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW VW_GD_GRIDS
AS
   SELECT G.*
,         T.GRID_TYPE_ID
,         RG.ROUND_GRID_SID
,         RG.ROUND_SID
,         RG.ORDER_BY
,         R.YEAR
     FROM GD_GRIDS G
          JOIN GD_ROUND_GRIDS RG ON RG.GRID_SID = G.GRID_SID
          JOIN ROUNDS R ON RG.ROUND_SID = R.ROUND_SID
          JOIN GD_GRID_TYPES T ON G.GRID_TYPE_SID = T.GRID_TYPE_SID;