/* Formatted on 12/3/2019 15:55:00 (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW VW_GD_LINES
AS
   SELECT L.*
,         (SELECT LISTAGG (COUNTRY_ID, ',')
                     WITHIN GROUP (ORDER BY COUNTRY_ID)
             FROM COUNTRY_GROUPS
            WHERE COUNTRY_GROUP_ID = L.MANDATORY_CTY_GROUP_ID)
             AS MANDATORY_CTY_GRP_CTY_IDS
,         LT.LINE_TYPE_ID
,         HM.MESS
     FROM GD_LINES L
          JOIN GD_LINE_TYPES LT ON LT.LINE_TYPE_SID = L.LINE_TYPE_SID
          LEFT JOIN HELP_MSGS HM ON HM.HELP_MSG_SID = L.HELP_MSG_SID;