ALTER TABLE DSLOAD_STATUSES
   DROP PRIMARY KEY CASCADE;
   
DROP TABLE DSLOAD_STATUSES CASCADE CONSTRAINTS;
DROP SEQUENCE DSLOAD_STATUSES_SEQ;

CREATE TABLE DSLOAD_STATUSES
(
   STATUS_SID    NUMBER (8) CONSTRAINT DSLOAD_STATUSES_PK PRIMARY KEY
,  STATUS_ID     VARCHAR2 (16) NOT NULL CONSTRAINT DSLOAD_STATUSES_ID_UNQ UNIQUE
,  DESCR         VARCHAR2 (128)
,  STATE_CHANGE  NUMBER(1) DEFAULT 0 NOT NULL
,  ORDER_BY      NUMBER (3)
);

CREATE SEQUENCE DSLOAD_STATUSES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DSLOAD_STATUSES_TRG
   BEFORE INSERT
   ON DSLOAD_STATUSES
   FOR EACH ROW
BEGIN
   SELECT DSLOAD_STATUSES_SEQ.NEXTVAL INTO :NEW.STATUS_SID FROM DUAL;
END;
