DROP TABLE DSLOAD_VALID_STATUSES;

CREATE TABLE DSLOAD_VALID_STATUSES
(
    STATUS_SID         NUMBER(8)
                       NOT NULL
                       CONSTRAINT DSLOAD_VALID_STATUSES_STATUS_FK
                       REFERENCES DSLOAD_STATUSES(STATUS_SID)
   , VALID_STATUS_SID  NUMBER (8)
                       NOT NULL
                       CONSTRAINT DSLOAD_VALID_STATUSES_VALID_STATUS_FK
                       REFERENCES DSLOAD_STATUSES(STATUS_SID)
   , CONSTRAINT DSLOAD_VALID_STATUSES_UNIQUE UNIQUE(STATUS_SID, VALID_STATUS_SID)
);
