DROP TABLE EER_PUBLICATION_GEO_AREAS CASCADE CONSTRAINTS;

CREATE TABLE EER_PUBLICATION_GEO_AREAS(
      GEO_GROUP_SID             NUMBER(12)
                                NOT NULL
                                CONSTRAINT EER_PUBLICATION_GEO_AREAS_GEO_GROUP_FK REFERENCES EER_GEO_GROUP(GEO_GROUP_SID)
    , GEO_AREA_ID               VARCHAR2(12)
                                NOT NULL
                                CONSTRAINT EER_PUBLICATION_GEO_AREAS_GEO_AREA_ID_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
    , ORDER_BY                  NUMBER(8)
    , CONSTRAINT EER_PUBLICATION_GEO_AREAS_UNIQUE UNIQUE(GEO_GROUP_SID, GEO_AREA_ID)
);
