ALTER TABLE EER_INDICATOR_CODES
    DROP PRIMARY KEY CASCADE;

DROP TABLE EER_INDICATOR_CODES CASCADE CONSTRAINTS;
DROP SEQUENCE EER_INDICATOR_CODES_SEQ;

CREATE TABLE EER_INDICATOR_CODES(
      INDICATOR_CODE_SID  NUMBER(8) CONSTRAINT EER_INDICATOR_CODES_PK PRIMARY KEY
    , INDICATOR_ID        VARCHAR2(35 BYTE)
                          NOT NULL
                          CONSTRAINT EER_INDICATOR_CODES_ID_UNQ UNIQUE
    , DESCR VARCHAR2(1000 BYTE)
);

CREATE SEQUENCE EER_INDICATOR_CODES_SEQ;

CREATE OR REPLACE TRIGGER EER_INDICATOR_CODES_TRG
    BEFORE INSERT
    ON EER_INDICATOR_CODES
    FOR EACH ROW
BEGIN
    SELECT EER_INDICATOR_CODES_SEQ.NEXTVAL INTO :NEW.INDICATOR_CODE_SID FROM DUAL;
END;
