ALTER TABLE EER_MATRIX_DATA
    DROP PRIMARY KEY CASCADE;

DROP TABLE EER_MATRIX_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE EER_MATRIX_DATA_SEQ;

CREATE TABLE EER_MATRIX_DATA(
      MATRIX_DATA_SID      NUMBER(12)       CONSTRAINT EER_MATRIX_DATA_PK PRIMARY KEY
    , PROVIDER_SID         NUMBER(12)
                           NOT NULL
                           CONSTRAINT EER_MATRIX_DATA_PROVIDER_SID_FK
                           REFERENCES EER_PROVIDERS(PROVIDER_SID) ON DELETE CASCADE
    , GEO_GRP_SID          NUMBER(12)
                           CONSTRAINT EER_MATRIX_DATA_GEO_GRP_SID_FK
                           REFERENCES EER_GEO_GROUP(GEO_GROUP_SID) ON DELETE CASCADE
    , EXPORTER_CTY_ID      VARCHAR2(12)
                           NOT NULL
                           CONSTRAINT EER_MATRIX_DATA_EXPORTER_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
    , IMPORTER_CTY_ID      VARCHAR2(12)
                           NOT NULL
                           CONSTRAINT EER_MATRIX_DATA_IMPORTER_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
    , YEAR                 NUMBER(4)
                           NOT NULL
    , VALUE                VARCHAR2(200 BYTE)
    , UPDATE_DATE          DATE DEFAULT SYSDATE
    , UPDATE_USER          VARCHAR2(16)
    , CONSTRAINT EER_MATRIX_DATA_UNQ UNIQUE(PROVIDER_SID, YEAR, EXPORTER_CTY_ID, IMPORTER_CTY_ID, GEO_GRP_SID)
);
/
CREATE SEQUENCE EER_MATRIX_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER EER_MATRIX_DATA_TRG
    BEFORE INSERT
    ON EER_MATRIX_DATA
    FOR EACH ROW
BEGIN
    SELECT EER_MATRIX_DATA_SEQ.NEXTVAL INTO :NEW.MATRIX_DATA_SID FROM DUAL;
END;
/
