ALTER TABLE EER_PROVIDERS
    DROP PRIMARY KEY CASCADE;

DROP TABLE EER_PROVIDERS CASCADE CONSTRAINTS;
DROP SEQUENCE EER_PROVIDERS_SEQ;

CREATE TABLE EER_PROVIDERS(
      PROVIDER_SID         NUMBER(8) CONSTRAINT EER_PROVIDERS_PK PRIMARY KEY
    , PROVIDER_ID          VARCHAR2(30 BYTE) NOT NULL CONSTRAINT EER_PROVIDERS_ID_UNQ UNIQUE
    , DESCR                VARCHAR2(100 BYTE)
    , DATA_LOCATION        VARCHAR2(30 BYTE)
                              CONSTRAINT EER_PROVIDERS_DTA_LOCATION_CHECK CHECK
                              (DATA_LOCATION IS NULL OR DATA_LOCATION IN ('EER_MATRIX_DATA', 'EER_INDICATOR_DATA'))
    , DATA_SOURCE          VARCHAR2(30 BYTE)
    , IS_INPUT_DATA_UPLOAD NUMBER (1) NOT NULL
                           CONSTRAINT EER_PROVIDERS_IS_UPLOAD_CHECK CHECK (IS_INPUT_DATA_UPLOAD IN (0, 1))
    , ORDER_BY             NUMBER(8)
);

CREATE SEQUENCE EER_PROVIDERS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER EER_PROVIDERS_TRG
    BEFORE INSERT
    ON EER_PROVIDERS
    FOR EACH ROW
BEGIN
    SELECT EER_PROVIDERS_SEQ.NEXTVAL INTO :NEW.PROVIDER_SID FROM DUAL;
END;
