ALTER TABLE EER_INDICATOR_DATA
    DROP PRIMARY KEY CASCADE;

DROP TABLE EER_INDICATOR_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE EER_INDICATOR_DATA_SEQ;

CREATE TABLE EER_INDICATOR_DATA(
      INDICATOR_DATA_SID   NUMBER(12)       CONSTRAINT EER_INDICATOR_DATA_PK PRIMARY KEY
    , INDICATOR_SID        NUMBER(12)
                           NOT NULL
                           CONSTRAINT EER_INDICATOR_DATA_SID_FK
                           REFERENCES EER_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
    , GEO_GRP_SID          NUMBER(12)
                           CONSTRAINT EER_INDICATOR_DATA_GEO_GRP_SID_FK
                           REFERENCES EER_GEO_GROUP(GEO_GROUP_SID) ON DELETE CASCADE
    , COUNTRY_ID           VARCHAR2(12)
                           NOT NULL
                           CONSTRAINT EER_INDICATOR_DATA_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
    , START_YEAR           NUMBER(4)
                           NOT NULL
    , TIMESERIE_DATA       CLOB
    , UPDATE_DATE          DATE DEFAULT SYSDATE
    , UPDATE_USER          VARCHAR2(16)
    , CONSTRAINT EER_INDICATOR_DATA_UNQ UNIQUE(INDICATOR_SID, COUNTRY_ID, GEO_GRP_SID)
);
/
CREATE SEQUENCE EER_INDICATOR_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER EER_INDICATOR_DATA_TRG
    BEFORE INSERT
    ON EER_INDICATOR_DATA
    FOR EACH ROW
BEGIN
    SELECT EER_INDICATOR_DATA_SEQ.NEXTVAL INTO :NEW.INDICATOR_DATA_SID FROM DUAL;
END;
/
