DROP TABLE EER_DATA_UPLOADS CASCADE CONSTRAINTS;

CREATE TABLE EER_DATA_UPLOADS(
      PROVIDER_SID  NUMBER(8) NOT NULL
                    CONSTRAINT EER_DATA_UPLOADS_PRVDR_FK REFERENCES EER_PROVIDERS(PROVIDER_SID)
    , UPDATE_DATE   DATE
    , UPDATE_USER   VARCHAR2(16)
    , CONSTRAINT EER_DATA_UPLOADS_UNQ UNIQUE(PROVIDER_SID)
);
