ALTER TABLE EER_GEO_GROUP
    DROP PRIMARY KEY CASCADE;

DROP TABLE EER_GEO_GROUP CASCADE CONSTRAINTS;
DROP SEQUENCE EER_GEO_GROUP_SEQ;

CREATE TABLE EER_GEO_GROUP(
       GEO_GROUP_SID      NUMBER(12) CONSTRAINT EER_GEO_GROUP_PK PRIMARY KEY
    ,  GEO_GROUP_ID       VARCHAR2(12)
                          NOT NULL
    , DESCR               VARCHAR2(100) NOT NULL
    , ALIAS               VARCHAR2(12)
    , IS_ACTIVE           NUMBER(1) DEFAULT 0 NOT NULL
    , IS_DEFAULT          NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE EER_GEO_GROUP_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER EER_GEO_GROUP_TRG
    BEFORE INSERT
    ON EER_GEO_GROUP
    FOR EACH ROW
BEGIN
    SELECT EER_GEO_GROUP_SEQ.NEXTVAL INTO :NEW.GEO_GROUP_SID FROM DUAL;
END;
