DROP TABLE EER_GEO_GROUP_MEMBER CASCADE CONSTRAINTS;

CREATE TABLE EER_GEO_GROUP_MEMBER(
      GEO_GROUP_SID             NUMBER(12)
                                NOT NULL
                                CONSTRAINT EER_GEO_GROUP_MEMBER_GEO_GROUP_FK REFERENCES EER_GEO_GROUP(GEO_GROUP_SID)
    , GEO_AREA_ID               VARCHAR2(12)
                                NOT NULL
                                CONSTRAINT EER_GEO_GROUP_MEMBER_GEO_AREA_ID_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
    , ORDER_BY                  NUMBER(8)
    , CONSTRAINT EER_GEO_GROUP_MEMBER_UNIQUE UNIQUE(GEO_GROUP_SID, GEO_AREA_ID)
);
