ALTER TABLE EER_INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE EER_INDICATORS CASCADE CONSTRAINTS;
DROP SEQUENCE EER_INDICATORS_SEQ;

CREATE TABLE EER_INDICATORS(
   INDICATOR_SID       NUMBER(8) CONSTRAINT EER_INDICATORS_PK PRIMARY KEY
 , INDICATOR_CODE_SID  NUMBER(8)
                       NOT NULL
                       CONSTRAINT EER_INDICATORS_CODE_FK
                       REFERENCES EER_INDICATOR_CODES(INDICATOR_CODE_SID) ON DELETE CASCADE
 , PROVIDER_SID        NUMBER(8)
                       NOT NULL
                       CONSTRAINT EER_INDICATORS_PRVDR_FK REFERENCES EER_PROVIDERS(PROVIDER_SID)
 , PERIODICITY_ID      VARCHAR2(1)
                       NOT NULL
                       CONSTRAINT EER_INDICATORS_PERIOD_CHECK CHECK
                          (PERIODICITY_ID IN ('A', 'M', 'Q'))
 , CONSTRAINT EER_INDICATORS_UNQ UNIQUE(INDICATOR_CODE_SID, PROVIDER_SID, PERIODICITY_ID)
);

CREATE SEQUENCE EER_INDICATORS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER EER_INDICATORS_TRG
   BEFORE INSERT
   ON EER_INDICATORS
   FOR EACH ROW
BEGIN
   SELECT EER_INDICATORS_SEQ.NEXTVAL INTO :NEW.INDICATOR_SID FROM DUAL;
END;
