# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

# FASTOP configuration
export FASTOP=/ec/prod/app/webroot/home/fastop
if [ -f $FASTOP/etc/fastop_profile ]; then
        . $FASTOP/etc/fastop_profile
fi
