/* Formatted on 25-09-2020 15:19:45 (QP5 v5.313) */
DROP TABLE FDMS_AMECO_PH_DATA CASCADE CONSTRAINTS;

CREATE TABLE FDMS_AMECO_PH_DATA(
   COUNTRY_ID     VARCHAR2(12)
                  CONSTRAINT FDMS_AMECO_PH_DATA_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , ROUND_SID      NUMBER(8) CONSTRAINT FDMS_AMECO_PH_DATA_RND_FK REFERENCES ROUNDS(ROUND_SID)
 , INDICATOR_SID  NUMBER(8)
                  CONSTRAINT FDMS_AMECO_PH_DATA_IND_FK
                  REFERENCES FDMS_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
 , START_YEAR     NUMBER(4) NOT NULL
 , TIMESERIE_DATA VARCHAR2(4000)
 , UPDATE_DATE DATE
 , UPDATE_USER VARCHAR2(16)
 , CONSTRAINT FDMS_AMECO_PH_DATA_PK PRIMARY KEY(COUNTRY_ID, ROUND_SID, INDICATOR_SID)
);
