/* Formatted on 22/01/2020 10:14:38 (QP5 v5.313) */
DROP TABLE FDMS_CTY_INDICATOR_SCALES CASCADE CONSTRAINTS;

CREATE TABLE FDMS_CTY_INDICATOR_SCALES(
    COUNTRY_ID     VARCHAR2(12)
                   NOT NULL
                   CONSTRAINT FDMS_CTY_IND_SCALES_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
  , INDICATOR_SID  NUMBER
                   NOT NULL
                   CONSTRAINT FDMS_CTY_IND_SCALES_IND_FK
                   REFERENCES FDMS_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
  , SCALE_SID      NUMBER
                   NOT NULL
                   CONSTRAINT FDMS_CTY_IND_SCALES_SCL_FK REFERENCES FDMS_SCALES(SCALE_SID)
  , CONSTRAINT FDMS_CTY_IND_SCALES_UNQ UNIQUE(COUNTRY_ID, INDICATOR_SID, SCALE_SID)
);
