/* Formatted on 25-08-2020 21:16:43 (QP5 v5.313) */
ALTER TABLE FDMS_DT_COL_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_DT_COL_TYPES CASCADE CONSTRAINTS;

CREATE TABLE FDMS_DT_COL_TYPES(
   COL_TYPE_SID  NUMBER(8) CONSTRAINT FDMS_DT_COL_TYPES_PK PRIMARY KEY
 , COL_TYPE_ID   VARCHAR2(16) NOT NULL CONSTRAINT FDMS_DT_COL_TYPES_ID_UNQ UNIQUE
 , DESCR VARCHAR2(100)
);