/* Formatted on 24-08-2020 17:19:43 (QP5 v5.313) */
ALTER TABLE FDMS_DT_COLS
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_DT_COLS CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_DT_COLS_SEQ;

CREATE TABLE FDMS_DT_COLS(
   COL_SID       NUMBER(8) CONSTRAINT FDMS_DT_COLS_PK PRIMARY KEY
 , COL_ID        VARCHAR2(20) NOT NULL CONSTRAINT FDMS_DT_COLS_ID_UNQ UNIQUE
 , COL_TYPE_SID  NUMBER(8)
                 NOT NULL
                 CONSTRAINT FDMS_DT_COLS_COL_TYPE_FK REFERENCES FDMS_DT_COL_TYPES(COL_TYPE_SID)
 , DESCR VARCHAR2(200)
 , YEAR_VALUE NUMBER(4)
 , QUARTER NUMBER(1)
);

CREATE SEQUENCE FDMS_DT_COLS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_DT_COLS_TRG
   BEFORE INSERT
   ON FDMS_DT_COLS
   FOR EACH ROW
BEGIN
   SELECT FDMS_DT_COLS_SEQ.NEXTVAL INTO :NEW.col_sid FROM DUAL;
END;