/* Formatted on 26-08-2020 11:02:31 (QP5 v5.313) */
DROP TABLE FDMS_DT_LINE_HEADERS CASCADE CONSTRAINTS;

CREATE TABLE FDMS_DT_LINE_HEADERS(
   LINE_SID      NUMBER(8) CONSTRAINT FDMS_DT_LH_LINE_FK REFERENCES FDMS_DT_LINES(LINE_SID)
 , COL_TYPE_SID  NUMBER(8)
                 CONSTRAINT FDMS_DT_LH_COL_TYPE_FK REFERENCES FDMS_DT_COL_TYPES(COL_TYPE_SID)
 , HEADER        VARCHAR2(100) NOT NULL
 , CONSTRAINT FDMS_DT_LINE_HEADERS_PK PRIMARY KEY(LINE_SID, COL_TYPE_SID)
);