/* Formatted on 25-08-2020 21:17:14 (QP5 v5.313) */
ALTER TABLE FDMS_DT_LINE_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_DT_LINE_TYPES CASCADE CONSTRAINTS;

CREATE TABLE FDMS_DT_LINE_TYPES(
   LINE_TYPE_SID  NUMBER(8) CONSTRAINT FDMS_DT_LINE_TYPES_PK PRIMARY KEY
 , LINE_TYPE_ID   VARCHAR2(16) NOT NULL CONSTRAINT FDMS_DT_LINE_TYPES_ID_UNQ UNIQUE
 , DESCR VARCHAR2(100)
);