/* Formatted on 02-09-2020 19:15:45 (QP5 v5.313) */
ALTER TABLE FDMS_DT_LINES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_DT_LINES CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_DT_LINES_SEQ;

CREATE TABLE FDMS_DT_LINES(
   LINE_SID       NUMBER(8) CONSTRAINT FDMS_DT_LINES_PK PRIMARY KEY
 , LINE_TYPE_SID  NUMBER(8)
                  NOT NULL
                  CONSTRAINT FDMS_DT_LINES_LINE_TYPE_FK
                  REFERENCES FDMS_DT_LINE_TYPES(LINE_TYPE_SID)
 , DESCR VARCHAR2(200)
 , ESA_CODE VARCHAR2(200)
);

CREATE SEQUENCE FDMS_DT_LINES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_DT_LINES_TRG
   BEFORE INSERT
   ON FDMS_DT_LINES
   FOR EACH ROW
BEGIN
   SELECT FDMS_DT_LINES_SEQ.NEXTVAL INTO :NEW.LINE_SID FROM DUAL;
END;