/* Formatted on 18-09-2020 16:16:53 (QP5 v5.313) */
ALTER TABLE FDMS_DT_TABLE_LINES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_DT_TABLE_LINES CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_DT_TABLE_LINES_SEQ;

CREATE TABLE FDMS_DT_TABLE_LINES(
   TABLE_LINE_SID     NUMBER(8) CONSTRAINT FDMS_DT_TABLE_LINES_PK PRIMARY KEY
 , TABLE_SID          NUMBER(8)
                      NOT NULL
                      CONSTRAINT FDMS_DT_TABLE_LINES_TABLE_FK REFERENCES FDMS_DT_TABLES(TABLE_SID)
 , LINE_SID           NUMBER(8)
                      NOT NULL
                      CONSTRAINT FDMS_DT_TABLE_LINES_LINE_FK REFERENCES FDMS_DT_LINES(LINE_SID)
 , LINE_ID VARCHAR2(16)
 , STYLES VARCHAR(64)
 , LINE_SPAN          NUMBER(2) DEFAULT 1
 , COL_TYPE_SID_SPAN  NUMBER(8)
                      CONSTRAINT FDMS_DT_TABLE_LINES_COL_T_FK
                      REFERENCES FDMS_DT_COL_TYPES(COL_TYPE_SID)
 , SPAN_YEARS_OFFSET NUMBER(4)
 , USE_CTY_SCALE      NUMBER(1)
                      CONSTRAINT FDMS_DT_TABLE_LINES_SCALE_CHK CHECK(USE_CTY_SCALE IN (0, 1, 2))
 , ORDER_BY NUMBER(4)
);

CREATE SEQUENCE FDMS_DT_TABLE_LINES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_DT_TABLE_LINES_TRG
   BEFORE INSERT
   ON FDMS_DT_TABLE_LINES
   FOR EACH ROW
BEGIN
   SELECT FDMS_DT_TABLE_LINES_SEQ.NEXTVAL INTO :NEW.TABLE_LINE_SID FROM DUAL;
END;
