/* Formatted on 16/09/2020 11:05:33 (QP5 v5.313) */
DROP TABLE FDMS_DT_TABLE_COLS CASCADE CONSTRAINTS;

CREATE TABLE FDMS_DT_TABLE_COLS(
   TABLE_SID      NUMBER(8)
                  NOT NULL
                  CONSTRAINT FDMS_DT_TABLE_COLS_TABLE_FK REFERENCES FDMS_DT_TABLES(TABLE_SID)
 , COL_SID        NUMBER(8)
                  NOT NULL
                  CONSTRAINT FDMS_DT_TABLE_COLS_COL_FK REFERENCES FDMS_DT_COLS(COL_SID)
 , USE_CTY_SCALE  NUMBER(1)
                  CONSTRAINT FDMS_DT_TABLE_COLS_SCALE_CHECK CHECK(USE_CTY_SCALE IN (0, 1, 2))
 , ORDER_BY NUMBER(4)
);
