/* Formatted on 21-09-2020 11:23:36 (QP5 v5.313) */
ALTER TABLE FDMS_DT_TABLES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_DT_TABLES CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_DT_TABLES_SEQ;

CREATE TABLE FDMS_DT_TABLES(
   TABLE_SID  NUMBER(8) CONSTRAINT FDMS_DT_TABLES_PK PRIMARY KEY
 , TABLE_ID   VARCHAR2(16) CONSTRAINT FDMS_DT_TABLES_ID_UNQ UNIQUE
 , DESCR VARCHAR2(200)
 , FOOTER VARCHAR2(500)
 , ORDER_BY NUMBER(4)
);

CREATE SEQUENCE FDMS_DT_TABLES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_DT_TABLES_TRG
   BEFORE INSERT
   ON FDMS_DT_TABLES
   FOR EACH ROW
BEGIN
   SELECT FDMS_DT_TABLES_SEQ.NEXTVAL INTO :NEW.TABLE_SID FROM DUAL;
END;