ALTER TABLE FDMS_FORECASTS
    DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_FORECASTS CASCADE CONSTRAINTS;

CREATE TABLE FDMS_FORECASTS(
    FORECAST_ID         VARCHAR2(35 BYTE) CONSTRAINT FORECAST_ID_PK PRIMARY KEY
  , DESCR               VARCHAR2(1000 BYTE)
  , ROUND_SID           NUMBER(8)
                        NULL
                        CONSTRAINT FDMS_FORECAST_ROUND_FK REFERENCES ROUNDS(ROUND_SID)
  , STORAGE_SID         NUMBER(8)
                        NULL
                        CONSTRAINT FDMS_FORECAST_STORAGE_FK REFERENCES STORAGES(STORAGE_SID)
  , LAST_CHANGE_USER    VARCHAR2 (20 CHAR)
  , LAST_CHANGE_DATE    DATE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
