/* Formatted on 25-09-2020 15:39:22 (QP5 v5.313) */
ALTER TABLE FDMS_INDICATOR_DATA
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_INDICATOR_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_INDICATOR_DATA_SEQ;

CREATE TABLE FDMS_INDICATOR_DATA(
   INDICATOR_DATA_SID  NUMBER(12) CONSTRAINT FDMS_INDICATOR_DATA_PK PRIMARY KEY
 , INDICATOR_SID       NUMBER(8)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATOR_DATA_IND_FK
                       REFERENCES FDMS_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
 , COUNTRY_ID          VARCHAR2(12)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATOR_DATA_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , ROUND_SID           NUMBER(8)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATOR_DATA_RND_FK REFERENCES ROUNDS(ROUND_SID)
 , STORAGE_SID         NUMBER(8)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATOR_DATA_STRG_FK REFERENCES STORAGES(STORAGE_SID)
 , CUST_TEXT_SID       NUMBER (8) REFERENCES CUST_STORAGE_TEXTS (CUST_STORAGE_TEXT_SID)
 , START_YEAR          NUMBER(4) NOT NULL
 , END_YEAR            NUMBER(4)
 , TIMESERIE_DATA      VARCHAR2(4000)
 , OG_FULL             NUMBER (1)
 , UPDATE_DATE         DATE
 , UPDATE_USER         VARCHAR2(16)
 , CONSTRAINT FDMS_INDICATOR_DATA_UNQ UNIQUE(INDICATOR_SID, COUNTRY_ID, ROUND_SID, STORAGE_SID, CUST_TEXT_SID)
);

CREATE SEQUENCE FDMS_INDICATOR_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_INDICATOR_DATA_TRG
   BEFORE INSERT
   ON FDMS_INDICATOR_DATA
   FOR EACH ROW
BEGIN
   SELECT FDMS_INDICATOR_DATA_SEQ.NEXTVAL INTO :NEW.INDICATOR_DATA_SID FROM DUAL;
END;
/
CREATE INDEX FDMS_INDICATOR_DATA_ARCHIVE_INDEX ON FDMS_INDICATOR_DATA(ROUND_SID,STORAGE_SID);
/
