DROP TABLE FDMS_INDICATOR_DATA_UPLOADS CASCADE CONSTRAINTS;

CREATE TABLE FDMS_INDICATOR_DATA_UPLOADS(
      ROUND_SID     NUMBER(8)
                        NOT NULL
                        CONSTRAINT FDMS_IND_DATA_UPLOADS_RND_FK REFERENCES ROUNDS(ROUND_SID)
    , STORAGE_SID   NUMBER(8)
                        NOT NULL
                        CONSTRAINT FDMS_IND_DATA_UPLOADS_STRG_FK
                            REFERENCES STORAGES(STORAGE_SID)
    , PROVIDER_SID  NUMBER(8)
                        NOT NULL
                        CONSTRAINT FDMS_IND_DATA_UPLOADS_PRVDR_FK
                            REFERENCES FDMS_PROVIDERS(PROVIDER_SID)
    , COUNTRY_ID    VARCHAR2(12)
                        CONSTRAINT FDMS_IND_DATA_UPLOADS_CTY_FK
                            REFERENCES GEO_AREAS(GEO_AREA_ID)
    , UPDATE_DATE   DATE
    , UPDATE_USER   VARCHAR2(16)
    , CONSTRAINT FDMS_IND_DATA_UPLOADS_UNQ UNIQUE(ROUND_SID, STORAGE_SID, PROVIDER_SID, COUNTRY_ID)
);
