DROP TABLE FDMS_INDICATOR_MAPPINGS CASCADE CONSTRAINTS;

CREATE TABLE FDMS_INDICATOR_MAPPINGS(
      SOURCE_CODE         VARCHAR2(30 BYTE)
                          NOT NULL
    , SOURCE_DESCR        VARCHAR2(100 BYTE)
    , INDICATOR_SID       NUMBER(8)
                          NOT NULL
                          CONSTRAINT FDMS_INDICATOR_MAPPINGS_IND_FK
                          REFERENCES FDMS_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
    , SCALE_SID           NUMBER
                          NOT NULL
                          CONSTRAINT FDMS_INDICATOR_MAPPINGS_SCL_FK REFERENCES FDMS_SCALES(SCALE_SID)
    , CONSTRAINT FDMS_INDICATOR_MAPPINGS_UNQ UNIQUE(SOURCE_CODE, INDICATOR_SID)
);
