/* Formatted on 25-09-2020 15:13:47 (QP5 v5.313) */
ALTER TABLE FDMS_INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_INDICATORS CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_INDICATORS_SEQ;

CREATE TABLE FDMS_INDICATORS(
   INDICATOR_SID       NUMBER(8) CONSTRAINT FDMS_INDICATORS_PK PRIMARY KEY
 , INDICATOR_CODE_SID  NUMBER(8)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATORS_CODE_FK
                       REFERENCES FDMS_INDICATOR_CODES(INDICATOR_CODE_SID) ON DELETE CASCADE
 , PROVIDER_SID        NUMBER(8)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATORS_PRVDR_FK REFERENCES FDMS_PROVIDERS(PROVIDER_SID)
 , PERIODICITY_ID      VARCHAR2(1)
                       NOT NULL
                       CONSTRAINT FDMS_INDICATORS_PERIOD_CHECK CHECK
                          (PERIODICITY_ID IN ('A', 'M', 'Q'))
 , TRANSFORMATION_SID NUMBER(8) REFERENCES FDMS_TRANSFORMATIONS(TRANSFORMATION_SID)
 , CONSTRAINT FDMS_INDICATORS_UNQ UNIQUE(INDICATOR_CODE_SID, PROVIDER_SID, PERIODICITY_ID)
);

CREATE SEQUENCE FDMS_INDICATORS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_INDICATORS_TRG
   BEFORE INSERT
   ON FDMS_INDICATORS
   FOR EACH ROW
BEGIN
   SELECT FDMS_INDICATORS_SEQ.NEXTVAL INTO :NEW.INDICATOR_SID FROM DUAL;
END;
