ALTER TABLE FDMS_INDICATOR_TREE
DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_INDICATOR_TREE CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_INDICATOR_TREE_SEQ;

CREATE TABLE FDMS_INDICATOR_TREE(
      TREE_SID            NUMBER(8) CONSTRAINT FDMS_INDICATOR_TREE_PK PRIMARY KEY
    , CODE                VARCHAR2(20 BYTE)
                          NOT NULL
                          CONSTRAINT FDMS_INDICATOR_TREE_CODE_UNQ UNIQUE
    , DESCR               VARCHAR2(1000 BYTE)
    , INDICATOR_ID        VARCHAR2(35 BYTE)
    , ORDER_BY            NUMBER(8)
    , PARENT_CODE         VARCHAR2(20 BYTE)
);

CREATE SEQUENCE FDMS_INDICATOR_TREE_SEQ;

CREATE OR REPLACE TRIGGER FDMS_INDICATOR_TREE_TRG
    BEFORE INSERT
    ON FDMS_INDICATOR_TREE
    FOR EACH ROW
BEGIN
    SELECT FDMS_INDICATOR_TREE_SEQ.NEXTVAL INTO :NEW.TREE_SID FROM DUAL;
END;
