/* Formatted on 23/01/2020 11:23:11 (QP5 v5.313) */
ALTER TABLE FDMS_PROVIDERS
    DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_PROVIDERS CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_PROVIDERS_SEQ;

CREATE TABLE FDMS_PROVIDERS(
    PROVIDER_SID         NUMBER(8) CONSTRAINT FDMS_PROVIDERS_PK PRIMARY KEY
  , PROVIDER_ID          VARCHAR2(10 BYTE) NOT NULL CONSTRAINT FDMS_PROVIDERS_ID_UNQ UNIQUE
  , DESCR                VARCHAR2(100 BYTE)
  , IS_COUNTRY_UPLOAD    NUMBER (1) DEFAULT 0 NOT NULL
                            CONSTRAINT FDMS_PROVIDERS_IS_CTY_CHECK CHECK (IS_COUNTRY_UPLOAD IN (0, 1))
  , IS_INPUT_DATA_UPLOAD NUMBER (1) DEFAULT 1 NOT NULL
                            CONSTRAINT FDMS_PRVDRS_IS_UPLOAD_CHECK CHECK (IS_INPUT_DATA_UPLOAD IN (0, 1))
  , DATA_LOCATION        VARCHAR2(30 BYTE)
                            CONSTRAINT FDMS_PROVIDERS_DTA_LOCATION_CHECK CHECK
                            (DATA_LOCATION IS NULL OR DATA_LOCATION IN ('FDMS_INDICATOR_DATA', 'FDMS_TCE_RESULTS', 'FDMS_AMECO_DATA'))
  , DATA_SOURCE          VARCHAR2(30 BYTE)
  , USE_LATEST_DATA      NUMBER (1)
);

CREATE SEQUENCE FDMS_PROVIDERS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_PROVIDERS_TRG
    BEFORE INSERT
    ON FDMS_PROVIDERS
    FOR EACH ROW
BEGIN
    SELECT FDMS_PROVIDERS_SEQ.NEXTVAL INTO :NEW.PROVIDER_SID FROM DUAL;
END;
