ALTER TABLE FDMS_REPORTS
DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_REPORTS CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_REPORTS_SEQ;

CREATE TABLE FDMS_REPORTS(
      REPORT_SID         NUMBER(8) CONSTRAINT FDMS_REPORTS_PK PRIMARY KEY
    , REPORT_ID          VARCHAR2(10 BYTE) NOT NULL CONSTRAINT FDMS_REPORTS_ID_UNQ UNIQUE
);

CREATE SEQUENCE FDMS_REPORTS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_REPORTS_TRG
    BEFORE INSERT
    ON FDMS_REPORTS
    FOR EACH ROW
BEGIN
    SELECT FDMS_REPORTS_SEQ.NEXTVAL INTO :NEW.REPORT_SID FROM DUAL;
END;
