DROP TABLE FDMS_REPORT_INDICATORS CASCADE CONSTRAINTS;

CREATE TABLE FDMS_REPORT_INDICATORS(
     INDICATOR_CODE_SID  NUMBER(8)
                         NOT NULL
                         CONSTRAINT FDMS_REPORT_INDICATORS_CODE_FK
                         REFERENCES FDMS_INDICATOR_CODES(INDICATOR_CODE_SID) ON DELETE CASCADE
    , REPORT_SID         NUMBER(8)
                         NOT NULL
                         CONSTRAINT FDMS_REPORT_INDICATORS_REPORT_FK
                         REFERENCES FDMS_REPORTS(REPORT_SID) ON DELETE CASCADE
    , ORDER_BY           NUMBER(4)
    , CONSTRAINT FDMS_REPORT_INDICATORS_UNQ UNIQUE(INDICATOR_CODE_SID, REPORT_SID)
);
