/* Formatted on 15-09-2020 13:48:47 (QP5 v5.313) */
ALTER TABLE FDMS_SCALES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_SCALES CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_SCALES_SEQ;

CREATE TABLE FDMS_SCALES(
   SCALE_SID  NUMBER(8) CONSTRAINT FDMS_SCALES_PK PRIMARY KEY
 , SCALE_ID   VARCHAR2(32) NOT NULL CONSTRAINT FDMS_SCALES_ID_UNQ UNIQUE
 , DESCR      VARCHAR2(100 BYTE) NOT NULL
 , ORDER_BY   NUMBER(4) NOT NULL
 , EXPONENT NUMBER(2)
);

CREATE SEQUENCE FDMS_SCALES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_SCALES_TRG
   BEFORE INSERT
   ON FDMS_SCALES
   FOR EACH ROW
BEGIN
   SELECT FDMS_SCALES_SEQ.NEXTVAL INTO :NEW.SCALE_SID FROM DUAL;
END;