ALTER TABLE FDMS_TCE_MATRICES
    DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_TCE_MATRICES CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_TCE_MATRICES_SEQ;

CREATE TABLE FDMS_TCE_MATRICES (
    TCE_MATRIX_SID      NUMBER(38) CONSTRAINT FDMS_TCE_MATRICES_PK PRIMARY KEY
  , PROVIDER_SID        NUMBER(8)
                        NOT NULL
                        CONSTRAINT FDMS_TCE_MATRICES_PRVDR_FK REFERENCES FDMS_PROVIDERS(PROVIDER_SID)
  , ROUND_SID           NUMBER(8)
                        NOT NULL
                        CONSTRAINT FDMS_TCE_MATRICES_RND_FK REFERENCES ROUNDS(ROUND_SID)
  , STORAGE_SID         NUMBER(8)
                        NOT NULL
                        CONSTRAINT FDMS_TCE_MATRICES_STRG_FK
                        REFERENCES STORAGES(STORAGE_SID)
  , CONSTRAINT FDMS_TCE_MATRICES_UNQ UNIQUE(PROVIDER_SID, ROUND_SID, STORAGE_SID)
);

CREATE SEQUENCE FDMS_TCE_MATRICES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_TCE_MATRICES_TRG
    BEFORE INSERT
    ON FDMS_TCE_MATRICES
    FOR EACH ROW
BEGIN
    SELECT FDMS_TCE_MATRICES_SEQ.NEXTVAL INTO :NEW.TCE_MATRIX_SID FROM DUAL;
END;
