ALTER TABLE FDMS_TCE_MATRIX_DATA
    DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_TCE_MATRIX_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_TCE_MATRIX_DATA_SEQ;

CREATE TABLE FDMS_TCE_MATRIX_DATA (
    TCE_MATRIX_DATA_SID      NUMBER(38) CONSTRAINT FDMS_TCE_MATRIX_DATA_PK PRIMARY KEY
  , TCE_MATRIX_SID           NUMBER(38)
                             NOT NULL
                             CONSTRAINT FDMS_TCE_MATRIX_DATA_TCE_FK REFERENCES FDMS_TCE_MATRICES(TCE_MATRIX_SID)
  , EXPORTER_LINE_INDEX      NUMBER(8)
                             NOT NULL
  , EXPORTER_CTY_ID          VARCHAR2(8 BYTE)
                             NOT NULL
                             CONSTRAINT FDMS_TCE_MTRX_DT_EXP_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
  , PARTNER_COL_INDEX        NUMBER(8)
                             NOT NULL
  , PARTNER_CTY_ID           VARCHAR2(8 BYTE)
                             NOT NULL
                             CONSTRAINT FDMS_TCE_MTRX_DT_PRT_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
  , VALUE                    VARCHAR2(200 BYTE)
  , CONSTRAINT FDMS_TCE_MTRX_DT_UNQ UNIQUE(TCE_MATRIX_SID, EXPORTER_CTY_ID, PARTNER_CTY_ID)
);

CREATE SEQUENCE FDMS_TCE_MATRIX_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_TCE_MATRIX_DATA_TRG
    BEFORE INSERT
    ON FDMS_TCE_MATRIX_DATA
    FOR EACH ROW
BEGIN
    SELECT FDMS_TCE_MATRIX_DATA_SEQ.NEXTVAL INTO :NEW.TCE_MATRIX_DATA_SID FROM DUAL;
END;
