ALTER TABLE FDMS_TCE_REPORT_DEFINITION
    DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_TCE_REPORT_DEFINITION CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_TCE_REPORT_DEFINITION_SEQ;

CREATE TABLE FDMS_TCE_REPORT_DEFINITION (
    TCE_REPORT_SID         NUMBER(38) CONSTRAINT FDMS_TCE_REPORT_DEFINITION_PK PRIMARY KEY
  , DESCR                  VARCHAR2(1000 BYTE)
  , GN_INDICATOR_SID       NUMBER(8)
                           CONSTRAINT FDMS_TCE_REPORT_DEF_GN_IND_FK
                           REFERENCES FDMS_INDICATORS(INDICATOR_SID)
  , GN_DATA_TYPE           VARCHAR2(2 BYTE)
  , SN_INDICATOR_SID       NUMBER(8)
                           CONSTRAINT FDMS_TCE_REPORT_DEF_SN_IND_FK
                           REFERENCES FDMS_INDICATORS(INDICATOR_SID)
  , SN_DATA_TYPE           VARCHAR2(2 BYTE)
  , GS_INDICATOR_SID       NUMBER(8)
                           CONSTRAINT FDMS_TCE_REPORT_DEF_GS_IND_FK
                           REFERENCES FDMS_INDICATORS(INDICATOR_SID)
  , GS_DATA_TYPE           VARCHAR2(2 BYTE)
  , ORDER_BY               NUMBER
                           NOT NULL
  , IS_SEARCHABLE          NUMBER (1) DEFAULT 0 NOT NULL
                           CONSTRAINT FDMS_TCE_REPORT_DEF_IS_SEARCHABLE_CHECK CHECK (IS_SEARCHABLE IN (0, 1))
);

CREATE SEQUENCE FDMS_TCE_REPORT_DEFINITION_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_TCE_REPORT_DEFINITION_TRG
    BEFORE INSERT
    ON FDMS_TCE_REPORT_DEFINITION
    FOR EACH ROW
BEGIN
    SELECT FDMS_TCE_REPORT_DEFINITION_SEQ.NEXTVAL INTO :NEW.TCE_REPORT_SID FROM DUAL;
END;

