ALTER TABLE FDMS_TRANSFORMATIONS
DROP PRIMARY KEY CASCADE;

DROP TABLE FDMS_TRANSFORMATIONS CASCADE CONSTRAINTS;
DROP SEQUENCE FDMS_TRANSFORMATIONS_SEQ;

CREATE TABLE FDMS_TRANSFORMATIONS(
      TRANSFORMATION_SID  NUMBER(8) CONSTRAINT FDMS_TRANSFORMATIONS_PK PRIMARY KEY
    , TRANSFORMATION_ID   VARCHAR2(32) NOT NULL CONSTRAINT FDMS_TRANSFORMATIONS_ID_UNQ UNIQUE
    , DESCR VARCHAR2(128)
);

CREATE SEQUENCE FDMS_TRANSFORMATIONS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FDMS_TRANSFORMATIONS_TRG
   BEFORE INSERT
   ON FDMS_TRANSFORMATIONS
   FOR EACH ROW
BEGIN
SELECT FDMS_TRANSFORMATIONS_SEQ.NEXTVAL INTO :NEW.TRANSFORMATION_SID FROM DUAL;
END;
