ALTER TABLE AMECO_INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE AMECO_INDICATORS CASCADE CONSTRAINTS;
DROP SEQUENCE AMECO_INDICATORS_SEQ;

CREATE TABLE AMECO_INDICATORS(
   INDICATOR_SID       NUMBER(8) CONSTRAINT AMECO_INDICATORS_PK PRIMARY KEY
 , INDICATOR_CODE_SID  NUMBER(8)
                       NOT NULL
                       CONSTRAINT AMECO_INDICATORS_CODE_FK
                       REFERENCES AMECO_INDICATOR_CODES(INDICATOR_CODE_SID) ON DELETE CASCADE
 , PROVIDER_SID        NUMBER(8)
                       NOT NULL
                       CONSTRAINT AMECO_INDICATORS_PRVDR_FK REFERENCES AMECO_PROVIDERS(PROVIDER_SID)
 , PERIODICITY_ID      VARCHAR2(1)
                       NOT NULL
                       CONSTRAINT AMECO_INDICATORS_PERIOD_CHECK CHECK
                          (PERIODICITY_ID IN ('A', 'M', 'Q'))
 , CONSTRAINT AMECO_INDICATORS_UNQ UNIQUE(INDICATOR_CODE_SID, PROVIDER_SID, PERIODICITY_ID)
);

CREATE SEQUENCE AMECO_INDICATORS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER AMECO_INDICATORS_TRG
   BEFORE INSERT
   ON AMECO_INDICATORS
   FOR EACH ROW
BEGIN
   SELECT AMECO_INDICATORS_SEQ.NEXTVAL INTO :NEW.INDICATOR_SID FROM DUAL;
END;
