ALTER TABLE AMECO_INDICATOR_DATA
DROP PRIMARY KEY CASCADE;

DROP TABLE AMECO_INDICATOR_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE AMECO_INDICATOR_DATA_SEQ;

CREATE TABLE AMECO_INDICATOR_DATA(
      INDICATOR_DATA_SID  NUMBER(12)      CONSTRAINT AMECO_INDICATOR_DATA_PK PRIMARY KEY
    , INDICATOR_SID       NUMBER(8)
                                          NOT NULL
                                          CONSTRAINT AMECO_INDICATOR_DATA_IND_FK
                                          REFERENCES AMECO_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
    , COUNTRY_ID          VARCHAR2(12)
                                          NOT NULL
                                          CONSTRAINT AMECO_INDICATOR_DATA_CTY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
    , START_YEAR          NUMBER(4)       NOT NULL
    , TIMESERIE_DATA      VARCHAR2(4000)
    , UPDATE_DATE         DATE
                                          DEFAULT SYSDATE
    , UPDATE_USER         VARCHAR2(16)
    , CONSTRAINT AMECO_INDICATOR_DATA_UNQ UNIQUE(INDICATOR_SID, COUNTRY_ID)
);

CREATE SEQUENCE AMECO_INDICATOR_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER AMECO_INDICATOR_DATA_TRG
   BEFORE INSERT
   ON AMECO_INDICATOR_DATA
   FOR EACH ROW
BEGIN
   SELECT AMECO_INDICATOR_DATA_SEQ.NEXTVAL INTO :NEW.INDICATOR_DATA_SID FROM DUAL;
END;
/
