ALTER TABLE AMECO_INDICATOR_METADATA
DROP PRIMARY KEY CASCADE;

DROP TABLE AMECO_INDICATOR_METADATA CASCADE CONSTRAINTS;

CREATE TABLE AMECO_INDICATOR_METADATA(
      INDICATOR_DATA_SID    NUMBER(12)       CONSTRAINT AMECO_INDICATOR_METADATA_PK PRIMARY KEY
                                             REFERENCES AMECO_INDICATOR_DATA(INDICATOR_DATA_SID) ON DELETE CASCADE
    , HST_TIMESERIE_DATA    VARCHAR2(4000)
    , SRC_TIMESERIE_DATA    VARCHAR2(4000)
    , LEVEL_TIMESERIE_DATA  VARCHAR2(4000)
);
/
COMMENT ON COLUMN AMECO_INDICATOR_METADATA.SRC_TIMESERIE_DATA IS 'Series data references to definitions from table: AMECO_INDICATOR_INPUT_SOURCE';
/
