DROP TABLE AMECO_INDICATOR_INPUT_SOURCE;

CREATE TABLE AMECO_INDICATOR_INPUT_SOURCE(
    SOURCE_SID  NUMBER(12)     CONSTRAINT AMECO_IND_INPUT_SOURCE_PK PRIMARY KEY
  , CODE        VARCHAR2(100)  NOT NULL
);
