ALTER TABLE AMECO_NSI_INDICATOR_DATA
DROP PRIMARY KEY CASCADE;

DROP TABLE AMECO_NSI_INDICATOR_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE AMECO_NSI_INDICATOR_DATA_SEQ;

CREATE TABLE AMECO_NSI_INDICATOR_DATA(
      NSI_INDICATOR_DATA_SID   NUMBER(12)       CONSTRAINT AMECO_NSI_INDICATOR_DATA_PK PRIMARY KEY
    , NSI_INDICATOR_SID        NUMBER(12)
                               NOT NULL
                                                CONSTRAINT AMECO_NSI_INDICATOR_DATA_SID_FK
                                                REFERENCES AMECO_NSI_INDICATORS(NSI_INDICATOR_SID) ON DELETE CASCADE
    , TIMESERIE_DATA            VARCHAR2(4000)
    , ORDER_BY                  NUMBER(4)
                                NOT NULL
);
/
CREATE SEQUENCE AMECO_NSI_INDICATOR_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER AMECO_NSI_INDICATOR_DATA_TRG
   BEFORE INSERT
   ON AMECO_NSI_INDICATOR_DATA
   FOR EACH ROW
BEGIN
SELECT AMECO_NSI_INDICATOR_DATA_SEQ.NEXTVAL INTO :NEW.NSI_INDICATOR_DATA_SID FROM DUAL;
END;
/
