ALTER TABLE AMECO_PROVIDERS
    DROP PRIMARY KEY CASCADE;

DROP TABLE AMECO_PROVIDERS CASCADE CONSTRAINTS;
DROP SEQUENCE AMECO_PROVIDERS_SEQ;

CREATE TABLE AMECO_PROVIDERS(
    PROVIDER_SID         NUMBER(8) CONSTRAINT AMECO_PROVIDERS_PK PRIMARY KEY
  , PROVIDER_ID          VARCHAR2(10 BYTE) NOT NULL CONSTRAINT AMECO_PROVIDERS_ID_UNQ UNIQUE
  , DESCR                VARCHAR2(100 BYTE)
  , DATA_SOURCE          VARCHAR2(30 BYTE)
);

CREATE SEQUENCE AMECO_PROVIDERS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER AMECO_PROVIDERS_TRG
    BEFORE INSERT
    ON AMECO_PROVIDERS
    FOR EACH ROW
BEGIN
    SELECT AMECO_PROVIDERS_SEQ.NEXTVAL INTO :NEW.PROVIDER_SID FROM DUAL;
END;
