/* Formatted on 17-08-2021 15:51:00 (QP5 v5.313) */
ALTER TABLE DFM_ARCHIVED_MEASURES
   DROP PRIMARY KEY CASCADE;

DROP TABLE DFM_ARCHIVED_MEASURES CASCADE CONSTRAINTS;
DROP SEQUENCE DFM_ARCHIVED_MEASURES_SEQ;

CREATE TABLE DFM_ARCHIVED_MEASURES(
   ARCHIVED_MEASURE_SID  NUMBER(12) CONSTRAINT DFM_ARCHIVED_MEASURES_PK PRIMARY KEY
 , ROUND_SID             NUMBER(8)
                         NOT NULL
                         CONSTRAINT DFM_ARCH_MEASURES_ROUND_FK REFERENCES ROUNDS(ROUND_SID)
 , STORAGE_SID           NUMBER(4)
                         NOT NULL
                         CONSTRAINT DFM_ARCH_MEASURES_STORAGE_FK REFERENCES STORAGES(STORAGE_SID)
 , CUST_TEXT_SID         NUMBER(8)
                         CONSTRAINT DFM_ARCH_MEASURES_CUST_TEXT_FK
                         REFERENCES CUST_STORAGE_TEXTS(CUST_STORAGE_TEXT_SID)
 , MEASURE_SID NUMBER(8)
 , COUNTRY_ID            VARCHAR2(3 CHAR)
                         NOT NULL
                         CONSTRAINT DFM_ARCH_MEASURES_COUNTRY_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
 , STATUS_SID            NUMBER(8)
                         CONSTRAINT DFM_ARCH_MEASURES_STATUS_FK REFERENCES DFM_STATUS(STATUS_SID)
 , NEED_RESEARCH_SID NUMBER(4)
 , TITLE VARCHAR2(100 CHAR)
 , SHORT_DESCR VARCHAR2(4000 CHAR)
 , INFO_SRC VARCHAR2(400 CHAR)
 , ADOPT_DATE_YR NUMBER(4)
 , ADOPT_DATE_MH NUMBER(2)
 , COMMENTS VARCHAR2(4000 CHAR)
 , YEAR NUMBER(8)
 , REV_EXP_SID           NUMBER(4)
                         CONSTRAINT DFM_ARCH_MEASURES_REVEXP_FK REFERENCES DFM_REV_EXP(REV_EXP_SID)
 , ESA_SID NUMBER(8)
 , ESA_COMMENTS VARCHAR2(4000 CHAR)
 , ONE_OFF_SID           NUMBER(8)
                         CONSTRAINT DFM_ARCH_MEASURES_ONE_OFF_FK
                         REFERENCES DFM_ONE_OFF(ONE_OFF_SID)
 , ONE_OFF_TYPE_SID      NUMBER(8)
                         CONSTRAINT DFM_ARCH_MEASURES_OO_TYPE_FK
                         REFERENCES DFM_ONE_OFF_TYPES(ONE_OFF_TYPE_SID)
 , ONE_OFF_DISAGREE_SID NUMBER(4)
 , ONE_OFF_COMMENTS VARCHAR2(4000 CHAR)
 , DATA VARCHAR2(4000 CHAR)
 , START_YEAR NUMBER(4)
 , LOG_DATE DATE
 , QUANT_COMMENTS VARCHAR2(4000 BYTE)
 , FIRST_ROUND_SID       NUMBER(8)
                         CONSTRAINT DFM_ARCH_MEASURES_FST_ROUND_FK REFERENCES ROUNDS(ROUND_SID)
 , OO_PRINCIPLE_SID      NUMBER(8)
                         CONSTRAINT DFM_ARCH_MEASURES_OO_PRINC_FK
                         REFERENCES DFM_OO_PRINCIPLES(OO_PRINCIPLE_SID)
 , IS_PUBLIC             NUMBER(4) DEFAULT -1
 , IS_EU_FUNDED_SID      NUMBER(8)
                         CONSTRAINT DFM_AR_MEASURES_IS_EU_FUND_FK
                         REFERENCES DFM_ONE_OFF(ONE_OFF_SID)
 , EU_FUND_SID           NUMBER(8)
                         CONSTRAINT DFM_AR_MEASURES_EU_FUND_FK REFERENCES DFM_EU_FUNDS(EU_FUND_SID)
);

CREATE SEQUENCE DFM_ARCHIVED_MEASURES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DFM_ARCHIVED_MEASURES_TRG
   BEFORE INSERT
   ON DFM_ARCHIVED_MEASURES
   FOR EACH ROW
BEGIN
   SELECT DFM_ARCHIVED_MEASURES_SEQ.NEXTVAL INTO :NEW.ARCHIVED_MEASURE_SID FROM DUAL;
END;