/* Formatted on 12/3/2019 18:03:02 (QP5 v5.252.13127.32847) */
DROP TABLE DFM_COUNTRIES_INFO CASCADE CONSTRAINTS;

CREATE TABLE DFM_COUNTRIES_INFO
(
   COUNTRY_ID    VARCHAR2 (2 BYTE)
                    NOT NULL
                    CONSTRAINT DFM_COUNTRIES_INFO_UNQ UNIQUE
                    CONSTRAINT DFM_COUNTRIES_INFO_CTY_FK
                        REFERENCES GEO_AREAS (GEO_AREA_ID)
,  MULTI         NUMBER (15) NOT NULL
,  MULTI_DESCR   VARCHAR2 (50 BYTE)
,  SCALE         VARCHAR2 (50 BYTE)
);