/* Formatted on 17-08-2021 15:33:32 (QP5 v5.313) */
ALTER TABLE DFM_EU_FUNDS
   DROP PRIMARY KEY CASCADE;

DROP TABLE DFM_EU_FUNDS CASCADE CONSTRAINTS;

CREATE TABLE DFM_EU_FUNDS(
   EU_FUND_SID  NUMBER(4) CONSTRAINT DFM_EU_FUNDS_PK PRIMARY KEY
 , DESCR VARCHAR2(100 BYTE)
 , ORDER_BY NUMBER(4)
);