ALTER TABLE DFM_LABELS
DROP PRIMARY KEY CASCADE;

DROP TABLE DFM_LABELS CASCADE CONSTRAINTS;
DROP SEQUENCE DFM_LABELS_SEQ;

CREATE TABLE DFM_LABELS
(
    LABEL_SID      NUMBER (4) CONSTRAINT DFM_LABELS_PK PRIMARY KEY
 ,  DESCR          VARCHAR2 (100 BYTE)
);

CREATE SEQUENCE DFM_LABELS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DFM_LABELS_TRG
   BEFORE INSERT
   ON DFM_LABELS
   FOR EACH ROW
BEGIN
SELECT DFM_LABELS_SEQ.NEXTVAL INTO :NEW.LABEL_SID FROM DUAL;
END;
