/* Formatted on 12/3/2019 17:49:37 (QP5 v5.252.13127.32847) */
ALTER TABLE DFM_ONE_OFF_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE DFM_ONE_OFF_TYPES CASCADE CONSTRAINTS;

CREATE TABLE DFM_ONE_OFF_TYPES
(
   ONE_OFF_TYPE_SID   NUMBER (4) CONSTRAINT DFM_ONE_OFF_TYPES_PK PRIMARY KEY
,  DESCR              VARCHAR2 (100 BYTE)
,  ORDER_BY           NUMBER (4)
,  VERSION            NUMBER (4)
);