/* Formatted on 12/3/2019 17:45:55 (QP5 v5.252.13127.32847) */
ALTER TABLE DFM_OO_PRINCIPLES
   DROP PRIMARY KEY CASCADE;

DROP TABLE DFM_OO_PRINCIPLES CASCADE CONSTRAINTS;
DROP SEQUENCE DFM_OO_PRINCIPLES_SEQ;

CREATE TABLE DFM_OO_PRINCIPLES
(
   OO_PRINCIPLE_SID   NUMBER (4) CONSTRAINT DFM_OO_PRINCIPLES_PK PRIMARY KEY
,  OO_PRINCIPLE_ID    VARCHAR2 (50 BYTE)
,  DESCR              VARCHAR2 (4000 BYTE)
,  ORDER_BY           NUMBER (4)
);

CREATE SEQUENCE DFM_OO_PRINCIPLES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DFM_OO_PRINCIPLES_TRG
   BEFORE INSERT
   ON DFM_OO_PRINCIPLES
   FOR EACH ROW
BEGIN
   SELECT DFM_OO_PRINCIPLES_SEQ.NEXTVAL INTO :NEW.OO_PRINCIPLE_SID FROM DUAL;
END;