/* Formatted on 12/3/2019 17:42:15 (QP5 v5.252.13127.32847) */
ALTER TABLE DFM_OVERVIEW
   DROP PRIMARY KEY CASCADE;

DROP TABLE DFM_OVERVIEW CASCADE CONSTRAINTS;
DROP SEQUENCE DFM_OVERVIEW_SEQ;

CREATE TABLE DFM_OVERVIEW
(
   OVERVIEW_SID   NUMBER (4) CONSTRAINT DFM_OVERVIEW_PK PRIMARY KEY
,  DESCR          VARCHAR2 (100 BYTE)
,  CODES          VARCHAR2 (100 BYTE)
,  ORDER_BY       NUMBER (4)
,  OPERATOR       VARCHAR2 (10 BYTE)
,  IS_FILTER      NUMBER (1) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE DFM_OVERVIEW_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DFM_OVERVIEW_TRG
   BEFORE INSERT
   ON DFM_OVERVIEW
   FOR EACH ROW
BEGIN
   SELECT DFM_OVERVIEW_SEQ.NEXTVAL INTO :NEW.OVERVIEW_SID FROM DUAL;
END;

-- Join table for new Overviews with multiple ESA codes
CREATE TABLE DFM_OVERVIEW_ESA 
(
   OVERVIEW_SID   NUMBER(4),
   ESA2010_SID    NUMBER(8)
);
ALTER TABLE DFM_OVERVIEW_ESA ADD CONSTRAINT DFM_OVERVIEW_ESA_PK PRIMARY KEY (OVERVIEW_SID, ESA2010_SID);
ALTER TABLE DFM_OVERVIEW_ESA ADD CONSTRAINT DFM_OVERVIEW_ESA_OVERVIEW_FK FOREIGN KEY (OVERVIEW_SID) REFERENCES DFM_OVERVIEW;
ALTER TABLE DFM_OVERVIEW_ESA ADD CONSTRAINT DFM_OVERVIEW_ESA_ESA2010_FK FOREIGN KEY (ESA2010_SID) REFERENCES DFM_ESA2010;