ALTER TABLE NOTIFICATION_TEMPLATES
    DROP PRIMARY KEY CASCADE;

DROP TABLE NOTIFICATION_TEMPLATES;
DROP SEQUENCE NOTIFICATION_TEMPLATES_SID_SEQ;

CREATE TABLE NOTIFICATION_TEMPLATES
(
       TEMPLATE_SID         NUMBER (8) CONSTRAINT NOTIFICATION_TEMPLATES_PK PRIMARY KEY
    ,  TEMPLATE_ID          VARCHAR2(30) NOT NULL
                                         CONSTRAINT NOTIFICATION_TEMPLATES_ID_UNQ UNIQUE
    ,  RECIPIENTS           VARCHAR2 (1000 BYTE) NOT NULL
    ,  CC_RECIPIENTS        VARCHAR2 (1000 BYTE)
    ,  BCC_RECIPIENTS       VARCHAR2 (1000 BYTE)
    ,  SUBJECT              VARCHAR2 (1000 BYTE)
    ,  BODY                 VARCHAR2 (2000 BYTE)
);

CREATE SEQUENCE NOTIFICATION_TEMPLATES_SID_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER NOTIFICATION_TEMPLATES_TRG
    BEFORE INSERT
    ON NOTIFICATION_TEMPLATES
    FOR EACH ROW
BEGIN
    SELECT NOTIFICATION_TEMPLATES_SID_SEQ.NEXTVAL INTO :NEW.TEMPLATE_SID FROM DUAL;
END;
