CREATE OR REPLACE FORCE VIEW VW_EER_MATRIX_DATA
AS
SELECT M.*
     , G.GEO_GROUP_ID
     , G.IS_ACTIVE    AS GEO_GROUP_ACTIVE
     , G.ALIAS        AS GEO_GROUP_ALIAS
     , P.PROVIDER_ID
FROM EER_MATRIX_DATA M
              JOIN EER_PROVIDERS P
                ON M.PROVIDER_SID = P.PROVIDER_SID
         LEFT JOIN EER_GEO_GROUP G
                   ON M.GEO_GRP_SID = G.GEO_GROUP_SID;

