CREATE OR REPLACE FORCE VIEW VW_EER_INDICATORS_DATA
AS
    SELECT I.*
         , G.GEO_GROUP_ID
         , G.IS_ACTIVE    AS GEO_GROUP_ACTIVE
         , G.ALIAS        AS GEO_GROUP_ALIAS
         , D.COUNTRY_ID
         , D.START_YEAR
         , D.TIMESERIE_DATA
         , D.UPDATE_DATE
         , D.UPDATE_USER
     FROM VW_EER_INDICATORS I
     JOIN EER_INDICATOR_DATA D
       ON D.INDICATOR_SID = I.INDICATOR_SID
LEFT JOIN EER_GEO_GROUP G
       ON D.GEO_GRP_SID = G.GEO_GROUP_SID;
