CREATE OR REPLACE FORCE VIEW VW_EER_GEO_GROUPS
AS
SELECT G.GEO_GROUP_ID
     , G.DESCR AS GROUP_DESCR
     , G.ALIAS
     , G.IS_ACTIVE
     , G.IS_DEFAULT
     , M.GEO_AREA_ID AS GEO_MEMBER
     , A.DESCR       AS MEMBER_DESCR
     , M.ORDER_BY    AS ORDER_BY
FROM EER_GEO_GROUP G
LEFT JOIN EER_GEO_GROUP_MEMBER M
       ON G.GEO_GROUP_SID = M.GEO_GROUP_SID
LEFT JOIN GEO_AREAS A
       ON M.GEO_AREA_ID = A.GEO_AREA_ID;
