CREATE OR REPLACE FORCE VIEW VW_EER_PUBLICATION_GEO_AREAS
AS
   SELECT G.GEO_GROUP_ID
        , A.GEO_AREA_ID
        , M.DESCR
        , G.DESCR AS GROUP_DESCR
        , G.ALIAS AS GROUP_ALIAS
        , A.ORDER_BY
     FROM EER_PUBLICATION_GEO_AREAS A
     JOIN EER_GEO_GROUP G
       ON A.GEO_GROUP_SID = G.GEO_GROUP_SID
     JOIN VW_EER_GEO_MAPPINGS M
       ON A.GEO_AREA_ID = M.GEO_AREA_ID
    WHERE G.IS_ACTIVE = 1;
