ALTER TABLE FPLAKES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FPLAKES CASCADE CONSTRAINTS;
DROP SEQUENCE FPLAKES_SEQ;


CREATE TABLE FPLAKES (
   LAKE_SID            NUMBER(8) CONSTRAINT FPLAKES_PK PRIMARY KEY
 , SERVICE_SID         NUMBER(8)
                       NOT NULL
                       REFERENCES FPLAKE_SERVICES(SERVICE_SID)
 , PROVIDER            VARCHAR2(30)
                       DEFAULT 'ECFIN'
                       NOT NULL
 , DATAFLOW            VARCHAR2(100) NOT NULL
 , CONSTRAINT FPLAKES_UNQ UNIQUE(PROVIDER, DATAFLOW)
);

CREATE SEQUENCE FPLAKES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FPLAKES_TRG
   BEFORE INSERT
   ON FPLAKES
   FOR EACH ROW
BEGIN
   SELECT FPLAKES_SEQ.NEXTVAL INTO :NEW.LAKE_SID FROM DUAL;
END;
