ALTER TABLE FPLAKE_SERVICES
   DROP PRIMARY KEY CASCADE;

DROP TABLE FPLAKE_SERVICES CASCADE CONSTRAINTS;
DROP SEQUENCE FPLAKE_SERVICES_SEQ;


CREATE TABLE FPLAKE_SERVICES (
   SERVICE_SID   NUMBER(8) CONSTRAINT FPLAKE_SERVICES_PK PRIMARY KEY
 , SERVICE_ID    VARCHAR(30) NOT NULL CONSTRAINT FPLAKE_SERVICES_ID_UNQ UNIQUE
 , URL           VARCHAR2(100) NOT NULL CONSTRAINT FPLAKE_SERVICES_URL_UNQ UNIQUE
);

CREATE SEQUENCE FPLAKE_SERVICES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER FPLAKE_SERVICES_TRG
   BEFORE INSERT
   ON FPLAKE_SERVICES
   FOR EACH ROW
BEGIN
   SELECT FPLAKE_SERVICES_SEQ.NEXTVAL INTO :NEW.SERVICE_SID FROM DUAL;
END;
