CREATE OR REPLACE FORCE EDITIONABLE VIEW "FGD_RULE_MULTIPLE_VALUES_VW" ("QUESTIONNAIRE_SID", "RULE_SID", "ATTRIBUTE", "VALUE", "RESPONSE_GROUP_SID") AS 
  SELECT 1,
          RS.RULE_SID,
          'SECTOR_SID',
          RS.SECTOR_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_RULE_SECTORS RS
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = RS.SECTOR_SID
   UNION ALL
   SELECT 1,
          EER.RULE_SID,
          'EXCL_ELEM_SID',
          EER.EXCL_ELEM_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_EXCL_ELEM_RULES EER
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = EER.EXCL_ELEM_SID
   UNION ALL
   SELECT 1,
          I.RULE_SID,
          'ESC_INSTITUTION_SID',
          I.ESC_INSTITUTION_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_RULE_ESC_INST_VW I
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = I.ESC_INSTITUTION_SID
   UNION ALL
   SELECT 1,
          I.RULE_SID,
          'EAM_INSTITUTION_SID',
          I.EAM_INSTITUTION_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_RULE_EAM_INST_VW I
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = I.EAM_INSTITUTION_SID
   UNION ALL
   SELECT 1,
          I.RULE_SID,
          'EPM_INSTITUTION_SID',
          I.EPM_INSTITUTION_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_RULE_EPM_INST_VW I
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = I.EPM_INSTITUTION_SID
   UNION ALL
   SELECT 1,
          I.RULE_SID,
          'DCQ_INSTITUTION_SID',
          I.DCQ_INSTITUTION_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_RULE_DCQ_INST_VW I
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = I.DCQ_INSTITUTION_SID
   UNION ALL
   SELECT 1,
          TR.RULE_SID,
          'DCQ_TRG_SID',
          TR.DCQ_TRG_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_NFR_DCQ_TRG_RULES TR
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = TR.DCQ_TRG_SID
   UNION ALL
   SELECT 2,
          IMR.INSTITUTION_SID,
          'RULE_MON_INST_SID',
          IMR.RULE_MON_INST_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_RULE_MON IMR
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = IMR.RULE_MON_INST_SID
   UNION ALL
   SELECT 2,
          ESC.INSTITUTION_SID,
          'TRIG_ESCC_MON',
          ESC.TRIG_ESCC_MON,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_TRIG_ESCC_MON ESC
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = ESC.TRIG_ESCC_MON
   UNION ALL
   SELECT 2,
          LBI.INSTITUTION_SID,
          'LBI_ACCESS_SID',
          LBI.LBI_ACCESS_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_LBI_ACCESS LBI
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = LBI.LBI_ACCESS_SID
   UNION ALL
   SELECT 2,
          ISM.INSTITUTION_SID,
          'ANBUD_SECTOR_MACRO_SID',
          ISM.ANBUD_SECTOR_MACRO_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_SECTOR_MACRO ISM
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = ISM.ANBUD_SECTOR_MACRO_SID
   UNION ALL
   SELECT 2,
          ISB.INSTITUTION_SID,
          'SECTOR_BUDG_SID',
          ISB.SECTOR_BUDG_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_SECTOR_BUDG ISB
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = ISB.SECTOR_BUDG_SID
   UNION ALL
   SELECT 2,
          VAR.INSTITUTION_SID,
          'VARIABLE_SID',
          VAR.VARIABLE_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_VARIABLE VAR
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = VAR.VARIABLE_SID
   UNION ALL
   SELECT 2,
          IAN.INSTITUTION_SID,
          'ACTIVS_NORMS_SID',
          IAN.ACTIVS_NORMS_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_ACTIVS_NORMS IAN
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = IAN.ACTIVS_NORMS_SID
   UNION ALL
   SELECT 2,
          DT.INSTITUTION_SID,
          'DRAFT_TOPICS_SID',
          DT.DRAFT_TOPICS_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_DRAFT_TOPICS DT
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = DT.DRAFT_TOPICS_SID
   UNION ALL
   SELECT 2,
          IT.INSTITUTION_SID,
          'IMPLEM_TOPICS_SID',
          IT.IMPLEM_TOPICS_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_IMPLEM_TOPICS IT
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = IT.IMPLEM_TOPICS_SID
   UNION ALL
   SELECT 2,
          TCA.INSTITUTION_SID,
          'TIME_COMP_ASSESS_SID',
          TCA.TIME_COMP_ASSESS_SID,
          RC.RESPONSE_GROUP_SID
     FROM FGD_IFI_INST_TIME_COMP_ASSESS TCA
          JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
             ON RC.RESPONSE_SID = TCA.TIME_COMP_ASSESS_SID
    --
    UNION ALL
    SELECT 2,
            TCA.INSTITUTION_SID,
            'EXA_RRP_SID',
            TCA.EXA_RRP_SID,
            RC.RESPONSE_GROUP_SID
        FROM FGD_IFI_EXA_RRP TCA
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = TCA.EXA_RRP_SID
    UNION ALL
    SELECT 2,
            TCA.INSTITUTION_SID,
            'EXP_RRP_SID',
            TCA.EXP_RRP_SID,
            RC.RESPONSE_GROUP_SID
        FROM FGD_IFI_EXP_RRP TCA
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = TCA.EXP_RRP_SID
    UNION ALL
    SELECT 2,
            TCA.INSTITUTION_SID,
            'RRP_CHA_SID',
            TCA.RRP_CHA_SID,
            RC.RESPONSE_GROUP_SID
        FROM FGD_IFI_RPP_CHA TCA
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = TCA.RRP_CHA_SID
   UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'TARGET_REVIS_SID',
        F.TARGET_REVIS_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_TARGET_REVIS F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.TARGET_REVIS_SID
UNION ALL
       SELECT 3,
        F.FRAME_SID,
        'SEC_COV_MTBF_TARG_SID',
        F.SEC_COV_MTBF_TARG_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_SEC_COV_MTBF_TARG F
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.SEC_COV_MTBF_TARG_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'XSEC_COORD_MECH_SID',
        F.XSEC_COORD_MECH_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_XSEC_COORD_MECH F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.XSEC_COORD_MECH_SID

UNION ALL
        SELECT 3,
        F.FRAME_SID,
       'COORD_MECH_INVOLVE_SID',
        F.COORD_MECH_INVOLVE_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_COORD_MECH_INVOLVE F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.COORD_MECH_INVOLVE_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'TARGET_VARIABLES_SID',
       F.TARGET_VARIABLES_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_TARGET_VARIABLES F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.TARGET_VARIABLES_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'DISAGG_EXPEND_SID',
        F.DISAGG_EXPEND_SID,
       RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_DISAGG_EXPEND F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.DISAGG_EXPEND_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'BUDG_BAL_EXCL_SID',
        F.BUDG_BAL_EXCL_SID,
        RC.RESPONSE_GROUP_SID
       FROM FGD_MTBF_BUDG_BAL_EXCL F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.BUDG_BAL_EXCL_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXPEND_EXCL_SID',
        F.EXPEND_EXCL_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXPEND_EXCL F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXPEND_EXCL_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'POL_SCENE_IND_SID',
        F.POL_SCENE_IND_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_POL_SCENE_IND F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.POL_SCENE_IND_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'DISAGG_EXP_PROJ_SID',
        F.DISAGG_EXP_PROJ_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_DISAGG_EXP_PROJ F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.DISAGG_EXP_PROJ_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'DISAGG_LEV_POL_SID',
        F.DISAGG_LEV_POL_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_DISAGG_LEV_POL F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.DISAGG_LEV_POL_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'BUDG_TARG_DIFFER_SID',
        F.BUDG_TARG_DIFFER_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_BUDG_TARG_DIFFER F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.BUDG_TARG_DIFFER_SID
UNION ALL
       SELECT 3,
        F.FRAME_SID,
        'MTBF_PREP_ACTOR_SID',
        F.MTBF_PREP_ACTOR_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_MTBF_PREP_ACTOR F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.MTBF_PREP_ACTOR_SID

UNION ALL
        SELECT 3,
       F.FRAME_SID,
        'IFI_INVOLVE_SID',
        F.IFI_INVOLVE_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_IFI_INVOLVE F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.IFI_INVOLVE_SID

UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXA_CHARGE_BUDG_COMPL_SID',
        F.EXA_CHARGE_BUDG_COMPL_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXA_CHARGE_BUDG_C F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXA_CHARGE_BUDG_COMPL_SID

UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXA_MONIT_SID',
        F.EXA_MONIT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXA_MONIT F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXA_MONIT_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXP_MONIT_REP_SID',
        F.EXP_MONIT_REP_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXP_MONIT_REP F
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXP_MONIT_REP_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'ALT_MACRO_SCENE_SID',
        F.ALT_MACRO_SCENE_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_ALT_MACRO_SCENE F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.ALT_MACRO_SCENE_SID
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXP_BUD_CO_SID',
        F.EXP_BUD_CO_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXP_BUD_CO F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXP_BUD_CO_SID
--
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXA_RESULT_PRES_SID',
        F.EXA_RESULT_PRES_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXA_RESULT_PRES F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXA_RESULT_PRES_SID           
UNION ALL
        SELECT 3,
        F.FRAME_SID,
        'EXP_RESULT_PRES_SID',
        F.EXP_RESULT_PRES_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_MTBF_EXP_RESULT_PRES F 
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = F.EXP_RESULT_PRES_SID         
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'GEN_IN_PLACE_SID',
        G.GEN_IN_PLACE_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_GEN_IN_PLACE G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.GEN_IN_PLACE_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'GEN_PLANS_INTRO_SID',
        G.GEN_PLANS_INTRO_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_GEN_PLANS_INTRO G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.GEN_PLANS_INTRO_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'GEN_CHALLGE_SID',
        G.GEN_CHALLGE_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_GEN_CHALLGE G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.GEN_CHALLGE_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'GEN_MOTIV_SID',
        G.GEN_MOTIV_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_GEN_MOTIV G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.GEN_MOTIV_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVLT_ENV_OBJ_SID',
        G.CVLT_ENV_OBJ_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVLT_ENV_OBJ G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVLT_ENV_OBJ_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVLT_BDGT_ELMT_SID',
        G.CVLT_BDGT_ELMT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVLT_BDGT_ELMT G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVLT_BDGT_ELMT_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVLT_PUB_SECT_SID',
        G.CVLT_PUB_SECT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVLT_PUB_SECT G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVLT_PUB_SECT_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVBT_ENV_OBJ_SID',
        G.CVBT_ENV_OBJ_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVBT_ENV_OBJ G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVBT_ENV_OBJ_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVBT_BGT_ELMT_SID',
        G.CVBT_BGT_ELMT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVBT_BGT_ELMT G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVBT_BGT_ELMT_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVBT_PUB_SECT_SID',
        G.CVBT_PUB_SECT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVBT_PUB_SECT G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVBT_PUB_SECT_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVEI_ENV_OBJ_SID',
        G.CVEI_ENV_OBJ_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVEI_ENV_OBJ G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVEI_ENV_OBJ_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVEI_BDGT_ELMT_SID',
        G.CVEI_BDGT_ELMT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVEI_BDGT_ELMT G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVEI_BDGT_ELMT_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVEI_PUB_SECT_SID',
        G.CVEI_PUB_SECT_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVEI_PUB_SECT G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVEI_PUB_SECT_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'MTBT_TA_MTHD_SID',
        G.MTBT_TA_MTHD_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_MTBT_TA_MTHD G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.MTBT_TA_MTHD_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'MTEI_TA_SID',
        G.MTEI_TA_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_MTEI_TA G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.MTEI_TA_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'LBGB_LEG_BAS_SID',
        G.LBGB_LEG_BAS_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_LBGB_LEG_BAS G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.LBGB_LEG_BAS_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'LBTG_STAKE_LD_SID',
        G.LBTG_STAKE_LD_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_LBTG_STAKE_LD G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.LBTG_STAKE_LD_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'LBTG_STAKE_INV_SID',
        G.LBTG_STAKE_INV_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_LBTG_STAKE_INV G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.LBTG_STAKE_INV_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'TRAC_RPT_GB_SID',
        G.TRAC_RPT_GB_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_TRAC_RPT_GB G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.TRAC_RPT_GB_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'TRAC_AC_GBR_SID',
        G.TRAC_AC_GBR_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_TRAC_AC_GBR G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.TRAC_AC_GBR_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'EIEE_SUP_IMPL_SID',
        G.EIEE_SUP_IMPL_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_EIEE_SUP_IMPL G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.EIEE_SUP_IMPL_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'EIEE_CHAL_IMPL_SID',
        G.EIEE_CHAL_IMPL_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_EIEE_CHAL_IMPL G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.EIEE_CHAL_IMPL_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'EIEE_SUP_EC_SID',
        G.EIEE_SUP_EC_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_EIEE_SUP_EC G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.EIEE_SUP_EC_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'CVRS_MEAS_GB_SID',
        G.CVRS_MEAS_GB_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_CVRS_MEAS_GB G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.CVRS_MEAS_GB_SID
UNION ALL
SELECT 4,
        G.ENTRY_SID,
        'OTTL_OTHR_TOOL_SID',
        G.OTTL_OTHR_TOOL_SID,
        RC.RESPONSE_GROUP_SID
        FROM FGD_GBD_OTTL_OTHR_TOOL G
            JOIN FGD_CFG_RESPONSE_CHOICES_VW RC
                ON RC.RESPONSE_SID = G.OTTL_OTHR_TOOL_SID;