CREATE OR REPLACE VIEW FGD_MTBF_CURRENT_VINTAGE_VW as
SELECT
    DISTINCT 
    R.COUNTRY_ID,
    to_char(r.ENTRY_DATE, 'YYYY-MM-DD') as ENTRY_DATE,
    to_char(r.L_REF_DATEM, 'YYYY-MM-DD') as L_REF_DATEM,
    fgd_cfg_accessors.getattributevintagetext('SCP_FISC_SID', r.frame_sid, 3)||' ' as SCP_FISC_SID,
    fgd_cfg_accessors.getattributevintagetext('LB_DOCS_SID', r.frame_sid, 3)||' ' as LB_DOCS_SID,
    fgd_cfg_accessors.getattributevintagetext('LB_BUDGET_SID', r.frame_sid, 3)||' ' as LB_BUDGET_SID,
    fgd_cfg_accessors.getattributevintagetext('TIMEFRAME_MTBF_SID', r.frame_sid, 3)||' ' as TIMEFRAME_MTBF_SID,
    fgd_cfg_accessors.getattributevintagetext('TARGET_BIND_SID', r.frame_sid, 3)||' ' as TARGET_BIND_SID,
    fgd_cfg_accessors.getattributevintagetext('MTBF_GOV_TERM_SID', r.frame_sid, 3)||' ' as MTBF_GOV_TERM_SID,
    fgd_cfg_accessors.getattributevintagetext('TIMELINE_REVIS_SID', r.frame_sid, 3)||' ' as TIMELINE_REVIS_SID,
    fgd_cfg_accessors.getattributevintagetext('CONDIT_REVIS_SID', r.frame_sid, 3)||' ' as CONDIT_REVIS_SID,
    fgd_cfg_accessors.getattributevintagetext('JUSTIF_REVIS_SID', r.frame_sid, 3)||' ' as JUSTIF_REVIS_SID,
    fgd_cfg_accessors.getattributevintagetext('MTBF_SHARE_GG_SID', r.frame_sid, 3)||' ' as MTBF_SHARE_GG_SID,
    fgd_cfg_accessors.getattributevintagetext('BUDG_BAL_DEF_SID', r.frame_sid, 3)||' ' as BUDG_BAL_DEF_SID,
    fgd_cfg_accessors.getattributevintagetext('BUDG_BAL_UNIT_SID', r.frame_sid, 3)||' ' as BUDG_BAL_UNIT_SID,
    fgd_cfg_accessors.getattributevintagetext('EXPEND_UNIT_SID', r.frame_sid, 3)||' ' as EXPEND_UNIT_SID,
    fgd_cfg_accessors.getattributevintagetext('DEBT_DEF_SID', r.frame_sid, 3)||' ' as DEBT_DEF_SID,
    fgd_cfg_accessors.getattributevintagetext('DEBT_UNIT_SID', r.frame_sid, 3)||' ' as DEBT_UNIT_SID,
    fgd_cfg_accessors.getattributevintagetext('DEBT_EXCL_SID', r.frame_sid, 3)||' ' as DEBT_EXCL_SID,
    fgd_cfg_accessors.getattributevintagetext('REVENUE_UNIT_SID', r.frame_sid, 3)||' ' as REVENUE_UNIT_SID,
    fgd_cfg_accessors.getattributevintagetext('REVENUE_EXCL_SID', r.frame_sid, 3)||' ' as REVENUE_EXCL_SID,
    fgd_cfg_accessors.getattributevintagetext('POL_SCENE_SID', r.frame_sid, 3)||' ' as POL_SCENE_SID,
    fgd_cfg_accessors.getattributevintagetext('COFOG_BREAK_SID', r.frame_sid, 3)||' ' as COFOG_BREAK_SID,
    fgd_cfg_accessors.getattributevintagetext('ANA_PROJ_POL_SID', r.frame_sid, 3)||' ' as ANA_PROJ_POL_SID,
    fgd_cfg_accessors.getattributevintagetext('POLICY_IMPACT_SID', r.frame_sid, 3)||' ' as POLICY_IMPACT_SID,
    fgd_cfg_accessors.getattributevintagetext('ASS_IMP_MTFP_SID', r.frame_sid, 3)||' ' as ASS_IMP_MTFP_SID,
    fgd_cfg_accessors.getattributevintagetext('DESCR_ACC_DRAFT_SID', r.frame_sid, 3)||' ' as DESCR_ACC_DRAFT_SID,
    fgd_cfg_accessors.getattributevintagetext('BUDG_ACC_SYS_SID', r.frame_sid, 3)||' ' as BUDG_ACC_SYS_SID,
    fgd_cfg_accessors.getattributevintagetext('ACC_SYSTEM_SID', r.frame_sid, 3)||' ' as ACC_SYSTEM_SID,
    fgd_cfg_accessors.getattributevintagetext('FP_ADOPT_ANBUD_SID', r.frame_sid, 3)||' ' as FP_ADOPT_ANBUD_SID,
    fgd_cfg_accessors.getattributevintagetext('BO_CONN_ANBUD_SID', r.frame_sid, 3)||' ' as BO_CONN_ANBUD_SID,
    fgd_cfg_accessors.getattributevintagetext('SCP_PROJ_INCL_SID', r.frame_sid, 3)||' ' as SCP_PROJ_INCL_SID,
    fgd_cfg_accessors.getattributevintagetext('PARL_INVOLVE_SID', r.frame_sid, 3)||' ' as PARL_INVOLVE_SID,
    fgd_cfg_accessors.getattributevintagetext('EXA_BUDG_COMPL_SID', r.frame_sid, 3)||' ' as EXA_BUDG_COMPL_SID,
    fgd_cfg_accessors.getattributevintagetext('EXP_BUDG_COMPL_SID', r.frame_sid, 3)||' ' as EXP_BUDG_COMPL_SID,
    fgd_cfg_accessors.getattributevintagetext('CORR_ACT_DEVIATE_SID', r.frame_sid, 3)||' ' as CORR_ACT_DEVIATE_SID,
    fgd_cfg_accessors.getattributevintagetext('SPEC_REV_DO_SID', r.frame_sid, 3)||' ' as SPEC_REV_DO_SID,
    fgd_cfg_accessors.getattributevintagetext('MT_PL_DOC_LAW_SID', r.frame_sid, 3)||' ' as MT_PL_DOC_LAW_SID,
    fgd_cfg_accessors.getattributevintagetext('MT_PL_DOC_PRAC_SID', r.frame_sid, 3)||' ' as MT_PL_DOC_PRAC_SID,
    fgd_cfg_accessors.getattributevintagetext('MTBF_ANN_BGT_PROC_SID', r.frame_sid, 3)||' ' as MTBF_ANN_BGT_PROC_SID,
    fgd_cfg_accessors.getattributevintagetext('MTBF_FWD_EXP_CTRL_SID', r.frame_sid, 3)||' ' as MTBF_FWD_EXP_CTRL_SID,
    fgd_cfg_accessors.getattributevintagetext('MF_AGG_BUDG_PROC_SID', r.frame_sid, 3)||' ' as MF_AGG_BUDG_PROC_SID,
    fgd_cfg_accessors.getattributevintagetext('TARGET_REVIS_SID', r.frame_sid, 3)||' ' as TARGET_REVIS_SID,
    fgd_cfg_accessors.getattributevintagetext('SEC_COV_MTBF_TARG_SID', r.frame_sid, 3)||' ' as SEC_COV_MTBF_TARG_SID,
    fgd_cfg_accessors.getattributevintagetext('XSEC_COORD_MECH_SID', r.frame_sid, 3)||' ' as XSEC_COORD_MECH_SID,
    fgd_cfg_accessors.getattributevintagetext('COORD_MECH_INVOLVE_SID', r.frame_sid, 3)||' ' as COORD_MECH_INVOLVE_SID,
    fgd_cfg_accessors.getattributevintagetext('TARGET_VARIABLES_SID', r.frame_sid, 3)||' ' as TARGET_VARIABLES_SID,
    fgd_cfg_accessors.getattributevintagetext('DISAGG_EXPEND_SID', r.frame_sid, 3)||' ' as DISAGG_EXPEND_SID,
    fgd_cfg_accessors.getattributevintagetext('BUDG_BAL_EXCL_SID', r.frame_sid, 3)||' ' as BUDG_BAL_EXCL_SID,
    fgd_cfg_accessors.getattributevintagetext('EXPEND_EXCL_SID', r.frame_sid, 3)||' ' as EXPEND_EXCL_SID,
    fgd_cfg_accessors.getattributevintagetext('POL_SCENE_IND_SID', r.frame_sid, 3)||' ' as POL_SCENE_IND_SID,
    fgd_cfg_accessors.getattributevintagetext('DISAGG_EXP_PROJ_SID', r.frame_sid, 3)||' ' as DISAGG_EXP_PROJ_SID,
    fgd_cfg_accessors.getattributevintagetext('DISAGG_LEV_POL_SID', r.frame_sid, 3)||' ' as DISAGG_LEV_POL_SID,
    fgd_cfg_accessors.getattributevintagetext('ALT_MACRO_SCENE_SID', r.frame_sid, 3)||' ' as ALT_MACRO_SCENE_SID,
    fgd_cfg_accessors.getattributevintagetext('MTBF_PREP_ACTOR_SID', r.frame_sid, 3)||' ' as MTBF_PREP_ACTOR_SID,
    fgd_cfg_accessors.getattributevintagetext('IFI_INVOLVE_SID', r.frame_sid, 3)||' ' as IFI_INVOLVE_SID,
    fgd_cfg_accessors.getattributevintagetext('EXA_CHARGE_BUDG_COMPL_SID', r.frame_sid, 3)||' ' as EXA_CHARGE_BUDG_COMPL_SID,
    fgd_cfg_accessors.getattributevintagetext('EXA_RESULT_PRES_SID', r.frame_sid, 3)||' ' as EXA_RESULT_PRES_SID,
    fgd_cfg_accessors.getattributevintagetext('EXA_MONIT_SID', r.frame_sid, 3)||' ' as EXA_MONIT_SID,
    fgd_cfg_accessors.getattributevintagetext('EXP_BUD_CO_SID', r.frame_sid, 3)||' ' as EXP_BUD_CO_SID,
    fgd_cfg_accessors.getattributevintagetext('EXP_RESULT_PRES_SID', r.frame_sid, 3)||' ' as EXP_RESULT_PRES_SID,
    fgd_cfg_accessors.getattributevintagetext('EXP_MONIT_REP_SID', r.frame_sid, 3)||' ' as EXP_MONIT_REP_SID,
    r.MTBF_DESCR ,
    r.REF_CHANGES ,
    r.DOCS_LAW_LINK ,
    r.BUDGET_LAW_LINK ,
    r.EXPEND_DEF ,
    r.REVENUE_DEF ,
    r.POLICY_REF ,
    r.REFER_MTFP ,
    r.ANBUD_REF_FP ,
    r.CORR_MECH_LEGAL ,
    r.MF_ADD_INFO ,
    r.REF_FISC_PLAN ,
    r.BND_NAT_ADD_INFO ,
    r.DIS_EXP_AREA_ADD_INFO ,
    r.ADD_INFO_CONN_BUDGET ,
    r.ADD_INFO_EXA_MONIT ,
    r.ADD_INFO_EXP_MONIT ,
    fgd_cfg_accessors.getattributevintagetext('OBJ_COMPL_PREP_18_SID', r.frame_sid, 3)||' ' as  OBJ_COMPL_PREP_18_SID,
    fgd_cfg_accessors.getattributevintagetext('OBJ_COMPL_EXE_18_SID', r.frame_sid, 3)||' ' as  OBJ_COMPL_EXE_18_SID,
    fgd_cfg_accessors.getattributevintagetext('BODY_MAIN_MONITOR_SID', r.frame_sid, 3)||' ' as  BODY_MAIN_MONITOR_SID,
    fgd_cfg_accessors.getattributevintagetext('CORR_MES_TRIG_19_SID', r.frame_sid, 3)||' ' as  CORR_MES_TRIG_19_SID,
    fgd_cfg_accessors.getattributevintagetext('CORR_BUDGET_19_SID', r.frame_sid, 3)||' ' as  CORR_BUDGET_19_SID,
    fgd_cfg_accessors.getattributevintagetext('UPD_FOREC_REV_BUDG_SID', r.frame_sid, 3)||' ' as  UPD_FOREC_REV_BUDG_SID,
    fgd_cfg_accessors.getattributevintagetext('R_COR_BUD_SID', r.frame_sid, 3)||' ' as R_COR_BUD_SID
FROM fgd_mtbf_frames r
    JOIN fgd_mtbf_frame_edit_steps res ON r.frame_sid = res.frame_sid
    JOIN fgd_cfg_edit_steps         es ON res.edit_step_sid = es.edit_step_sid
    LEFT JOIN fgd_mtbf_frame_assessments ra ON r.frame_sid = ra.frame_sid
    WHERE res.round_sid = core_getters.getLatestApplicationRound('FGD', TO_NUMBER(CORE_GETTERS.getParameter('CURRENT_ROUND')), 1)
      and ra.round_sid = core_getters.getLatestApplicationRound('FGD', TO_NUMBER(CORE_GETTERS.getParameter('CURRENT_ROUND')), 1);