ALTER TABLE DWH_INDICATOR_DATA
   DROP PRIMARY KEY CASCADE;

DROP TABLE DWH_INDICATOR_DATA CASCADE CONSTRAINTS;
DROP SEQUENCE DWH_INDICATOR_DATA_SEQ;


CREATE TABLE DWH_INDICATOR_DATA(
   INDICATOR_DATA_SID  NUMBER(12) CONSTRAINT DWH_INDICATOR_DATA_PK PRIMARY KEY
 , INDICATOR_SID       NUMBER(8)
                       NOT NULL
                       REFERENCES DWH_INDICATORS(INDICATOR_SID) ON DELETE CASCADE
 , COUNTRY_ID          VARCHAR2(12)
                       NOT NULL
 , START_YEAR          NUMBER(4) NOT NULL
 , TIMESERIE_DATA      CLOB
 , UPDATE_DATE         DATE DEFAULT CURRENT_TIMESTAMP
 , UPDATE_USER         VARCHAR2(16)
 , CONSTRAINT DWH_INDICATOR_DATA_UNQ UNIQUE(INDICATOR_SID)
);

CREATE SEQUENCE DWH_INDICATOR_DATA_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DWH_INDICATOR_DATA_TRG
   BEFORE INSERT
   ON DWH_INDICATOR_DATA
   FOR EACH ROW
BEGIN
   SELECT DWH_INDICATOR_DATA_SEQ.NEXTVAL INTO :NEW.INDICATOR_DATA_SID FROM DUAL;
END;
