ALTER TABLE DWH_PROVIDERS
    DROP PRIMARY KEY CASCADE;

DROP TABLE DWH_PROVIDERS CASCADE CONSTRAINTS;
DROP SEQUENCE DWH_PROVIDERS_SEQ;

CREATE TABLE DWH_PROVIDERS(
      PROVIDER_SID         NUMBER(8) CONSTRAINT DWH_PROVIDERS_PK PRIMARY KEY
    , PROVIDER_ID          VARCHAR2(30 BYTE) NOT NULL CONSTRAINT DWH_PROVIDERS_ID_UNQ UNIQUE
    , DESCR                VARCHAR2(100 BYTE)
    , DATA_LOCATION        VARCHAR2(30 BYTE)
    , DATA_SOURCE          VARCHAR2(30 BYTE)
);

CREATE SEQUENCE DWH_PROVIDERS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DWH_PROVIDERS_TRG
    BEFORE INSERT
    ON DWH_PROVIDERS
    FOR EACH ROW
BEGIN
    SELECT DWH_PROVIDERS_SEQ.NEXTVAL INTO :NEW.PROVIDER_SID FROM DUAL;
END;
