ALTER TABLE DWH_INDICATORS
   DROP PRIMARY KEY CASCADE;

DROP TABLE DWH_INDICATORS CASCADE CONSTRAINTS;
DROP SEQUENCE DWH_INDICATORS_SEQ;


CREATE TABLE DWH_INDICATORS(
   INDICATOR_SID       NUMBER(8) CONSTRAINT DWH_INDICATORS_PK PRIMARY KEY
 , INDICATOR_CODE_SID  NUMBER(8)
                       NOT NULL
                       CONSTRAINT DWH_INDICATORS_CODE_FK
                       REFERENCES DWH_INDICATOR_CODES(INDICATOR_CODE_SID) ON DELETE CASCADE
 , PROVIDER_SID        NUMBER(8)
                       NOT NULL
                       CONSTRAINT DWH_INDICATORS_PRVDR_FK REFERENCES DWH_PROVIDERS(PROVIDER_SID)
 , PERIODICITY_ID      VARCHAR2(1)
                       NOT NULL
                       CONSTRAINT DWH_INDICATORS_PERIOD_CHECK CHECK
                          (PERIODICITY_ID IN ('A', 'M', 'Q' , 'D' , 'S','W'))
 , CONSTRAINT DWH_INDICATORS_UNQ UNIQUE(INDICATOR_CODE_SID, PROVIDER_SID, PERIODICITY_ID)
);

CREATE SEQUENCE DWH_INDICATORS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER DWH_INDICATORS_TRG
   BEFORE INSERT
   ON DWH_INDICATORS
   FOR EACH ROW
BEGIN
   SELECT DWH_INDICATORS_SEQ.NEXTVAL INTO :NEW.INDICATOR_SID FROM DUAL;
END;
