DROP TABLE DWH_AIRFLOW_RAW;

CREATE TABLE DWH_AIRFLOW_RAW(
      INDICATOR_ID         VARCHAR2(50)
    , PERIODICITY_ID       VARCHAR2(2)
    , START_YEAR           NUMBER(20)
    , TIMESERIE_DATA       CLOB
);
