ALTER TABLE DWH_INDICATOR_CODES
    DROP PRIMARY KEY CASCADE;

DROP TABLE DWH_INDICATOR_CODES CASCADE CONSTRAINTS;
DROP SEQUENCE DWH_INDICATOR_CODES_SEQ;

CREATE TABLE DWH_INDICATOR_CODES(
    INDICATOR_CODE_SID  NUMBER(8) CONSTRAINT DWH_INDICATOR_CODES PRIMARY KEY
  , INDICATOR_ID        VARCHAR2(35 BYTE)
                        NOT NULL
  , DESCR               CLOB
);

CREATE SEQUENCE DWH_INDICATOR_CODES_SEQ;

CREATE OR REPLACE TRIGGER DWH_INDICATOR_CODES_TRG
    BEFORE INSERT
    ON DWH_INDICATOR_CODES
    FOR EACH ROW
BEGIN
    SELECT DWH_INDICATOR_CODES_SEQ.NEXTVAL INTO :NEW.INDICATOR_CODE_SID FROM DUAL;
END;
