/* Formatted on 12-05-2020 17:21:33 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_ST_CTY_STATUS_CURR
AS
   SELECT A.APP_ID
        , CS.*
        , S.STORAGE_ID
        , SR.STATUS_ID
     FROM ST_CTY_STATUS_CURR  CS
          JOIN APPLICATIONS A ON A.APP_SID = CS.APP_SID
          JOIN ST_STATUS_REPO SR ON SR.STATUS_SID = CS.STATUS_SID
          LEFT JOIN STORAGES S ON S.STORAGE_SID = CS.STORAGE_SID