/* Formatted on 17-08-2020 13:56:49 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_ST_MAIL_RECIPIENTS
AS
   SELECT A.APP_ID
        , N.*
        , AC.ACTION_ID
        , R.RECIPIENT_EMAIL
     FROM ST_MAIL_NOTIFICATIONS  N
          JOIN APPLICATIONS A ON A.APP_SID = N.APP_SID
          JOIN ST_ACTIONS AC ON AC.ACTION_SID = N.ACTION_SID
          JOIN ST_MAIL_RECIPIENTS R ON R.MAIL_NOTIFICATION_SID = N.MAIL_NOTIFICATION_SID