SET DEFINE OFF

INSERT INTO NOTIFICATION_TEMPLATES (TEMPLATE_ID, RECIPIENTS, CC_RECIPIENTS, BCC_RECIPIENTS, SUBJECT, BODY)
     VALUES ('AMECO_TRANSFER'
           , 'Daniel.GRENOUILLEAU@ec.europa.eu;Antonio.FUSO@ec.europa.eu'
           , 'Hubert.Droulez@ec.europa.eu;Ingo.Kuhnert@ec.europa.eu;Cedric.VIGUIE@ec.europa.eu'
           , 'Tomasz.ZDRODOWSKI@ec.europa.eu;Susanne.HOFFMANN@ec.europa.eu'
           , 'Ameco transfer files for {ROUND_DESC} / {STORAGE_DESC}'
           , 'Dear colleagues<br>
Please find attached the transfer file containing forecast data of agreed series in the agreed format. Please treat those information as <b><u>confidential</u></b>.<br>
This message concerns the forecast round <b>{ROUND_DESC} {STORAGE_DESC}</b>.<br>
PS: this message is automatically generated by the FDMSSTAR system. Please contact the usual A3 counterpart colleagues, should you require further assistance.<br><br>
Best Regards,<br>
<b>The Forecast team</b>');


INSERT INTO NOTIFICATION_TEMPLATES (TEMPLATE_ID, RECIPIENTS, CC_RECIPIENTS, BCC_RECIPIENTS, SUBJECT, BODY)
     VALUES ('FMDS_AGG_ACCEPTATION'
           , 'ECFIN-LIST-A1@nomail.ec.europa.eu;ECFIN-LIST-A3@nomail.ec.europa.eu;ECFIN-LIST-C1@nomail.ec.europa.eu;ECFIN-LIST-C2@nomail.ec.europa.eu;ECFIN-LIST-B3@nomail.ec.europa.eu'
           , NULL
           , 'Hubert.Droulez@ec.europa.eu;'
           , 'Forecast closed {ROUND_DESC} / {STORAGE_DESC}'
           , 'Dear colleagues<br>
The Forecast Round ({ROUND_DESC}) Storage ({STORAGE_DESC}) is now closed. You cannot upload  data anymore.<br><br>
Link to FASTOP : <a href="https://intragate.ec.europa.eu/fastop">https://intragate.ec.europa.eu/fastop</a><br>
Link to FASTOP documentation on the ECFIN wiki : <a href="https://www.cc.cec/wikis/display/ecfin/FASTOP+-+fdmsstar%2C+scopax%2C+add-in">https://www.cc.cec/wikis/display/ecfin/FASTOP+-+fdmsstar%2C+scopax%2C+add-in</a><br><br>
PS: this message is automatically generated by the FDMSSTAR system. Please contact the usual A3 counterpart colleagues, should you require further assistance.<br><br>
Best Regards,<br>
<b>The Forecast team</b>');

COMMIT;
