/* Formatted on 1/17/2019 17:29:31 (QP5 v5.252.13127.32847) */
DROP TABLE MN_APP_MENUS;

CREATE TABLE MN_APP_MENUS
(
   APPLICATION_SID   NUMBER (4) NOT NULL CONSTRAINT MN_APP_MENUS_APP_FK
       REFERENCES APPLICATIONS (APP_SID)
,  MENU_REPO_SID     NUMBER (8) NOT NULL CONSTRAINT MN_APP_MENUS_MENU_FK
       REFERENCES MN_MENU_REPO (MENU_REPO_SID)
,  ORDER_BY          NUMBER (2)
,  CONSTRAINT MN_APP_MENUS_UNQ UNIQUE (APPLICATION_SID, MENU_REPO_SID)
);
