/* Formatted on 12/2/2019 13:24:39 (QP5 v5.252.13127.32847) */
ALTER TABLE MN_MENU_REPO_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE MN_MENU_REPO_TYPES;

CREATE TABLE MN_MENU_REPO_TYPES
(
   MENU_REPO_TYPE_SID   NUMBER (4) CONSTRAINT MENU_REPO_TYPES_PK PRIMARY KEY
,  MENU_REPO_TYPE_ID    VARCHAR2 (32)
                           NOT NULL
                           CONSTRAINT MN_MENU_REPO_TYPES_ID_UNQ UNIQUE
,  DESCR                VARCHAR2 (32)
);

DROP SEQUENCE MN_MENU_REPO_TYPES_SEQ;

CREATE SEQUENCE MN_MENU_REPO_TYPES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER MN_MENU_REPO_TYPES_TRG
   BEFORE INSERT
   ON MN_MENU_REPO_TYPES
   FOR EACH ROW
BEGIN
   SELECT MN_MENU_REPO_TYPES_SEQ.NEXTVAL
     INTO :NEW.MENU_REPO_TYPE_SID
     FROM DUAL;
END;