/* Formatted on 12/2/2019 13:47:31 (QP5 v5.252.13127.32847) */
ALTER TABLE MN_MENU_REPO
   DROP PRIMARY KEY CASCADE;

DROP TABLE MN_MENU_REPO;

CREATE TABLE MN_MENU_REPO
(
   MENU_REPO_SID        NUMBER (8) CONSTRAINT MN_MENU_REPO_PK PRIMARY KEY
,  MENU_REPO_ID         VARCHAR2 (32)
                           NOT NULL
                           CONSTRAINT MN_MENU_REPO_ID_UNQ UNIQUE
,  TITLE                VARCHAR2 (64)
,  ICON                 VARCHAR2 (32)
,  LINK                 VARCHAR2 (200)
,  LINK_PARAMS          VARCHAR2 (128)
,  HELP_MSG_SID         NUMBER (8)
                           CONSTRAINT MN_MENU_REPO_HELP_FK
                               REFERENCES HELP_MSGS (HELP_MSG_SID)
,  MENU_REPO_TYPE_SID   NUMBER (4)
                           NOT NULL
                           CONSTRAINT MN_MENU_REPO_TYPE_FK
                              REFERENCES MN_MENU_REPO_TYPES (MENU_REPO_TYPE_SID)
);

DROP SEQUENCE MN_MENU_REPO_SEQ;

CREATE SEQUENCE MN_MENU_REPO_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER MN_MENU_REPO_TRG
   BEFORE INSERT
   ON MN_MENU_REPO
   FOR EACH ROW
BEGIN
   SELECT MN_MENU_REPO_SEQ.NEXTVAL INTO :NEW.MENU_REPO_SID FROM DUAL;
END;
