/* Formatted on 12/2/2019 13:25:46 (QP5 v5.252.13127.32847) */
ALTER TABLE MN_PERMISSION_TYPES
   DROP PRIMARY KEY CASCADE;

DROP TABLE MN_PERMISSION_TYPES;

CREATE TABLE MN_PERMISSION_TYPES
(
   PERMISSION_TYPE_SID   NUMBER (4)
                            CONSTRAINT MN_PERMISSION_TYPES_PK PRIMARY KEY
,  PERMISSION_TYPE_ID    VARCHAR2 (32)
                            NOT NULL
                            CONSTRAINT MN_PERMISSION_TYPES_ID_UNQ UNIQUE
,  DESCR                 VARCHAR2 (32)
);

DROP SEQUENCE MN_PERMISSION_TYPES_SEQ;

CREATE SEQUENCE MN_PERMISSION_TYPES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER MN_PERMISSION_TYPES_TRG
   BEFORE INSERT
   ON MN_PERMISSION_TYPES
   FOR EACH ROW
BEGIN
   SELECT MN_PERMISSION_TYPES_SEQ.NEXTVAL
     INTO :NEW.PERMISSION_TYPE_SID
     FROM DUAL;
END;