/* Formatted on 1/16/2019 15:32:47 (QP5 v5.252.13127.32847) */
DROP TABLE MN_SECTION_RESTRICTIONS;

CREATE TABLE MN_SECTION_RESTRICTIONS
(
   MENU_SID               NUMBER (8) NOT NULL
,  SECTION_ID             VARCHAR2 (32) NOT NULL
,  USER_GROUP_SID         NUMBER (8) NOT NULL
,  RESTRICTION_TYPE_SID   NUMBER (2) NOT NULL
,  CONSTRAINT MN_SECTION_RESTR_ID_UNQ UNIQUE
      (MENU_SID
,      SECTION_ID
,      USER_GROUP_SID
,      RESTRICTION_TYPE_SID)
,  CONSTRAINT MN_SECTION_RESTR_MENU_FK FOREIGN KEY
      (MENU_SID)
       REFERENCES MN_MENUS (SID)
,  CONSTRAINT MN_SECTION_RESTR_UG_FK FOREIGN KEY
      (USER_GROUP_SID)
       REFERENCES UM_GROUPS (GROUP_SID)
,  CONSTRAINT MN_SECTION_RESTR_RT_FK FOREIGN KEY
      (RESTRICTION_TYPE_SID)
       REFERENCES MN_RESTRICTION_TYPES (SID)
);
