CREATE TABLE APP_GROUP_DETAILS(
    APP_GROUP_SID NUMBER(8) CONSTRAINT APP_GROUP_DETS_FK1 REFERENCES APP_GROUPS(APP_GROUP_SID)
,   APP_SID       NUMBER(8) CONSTRAINT APP_GROUP_DETS_FK2 REFERENCES APPLICATIONS(APP_SID)
,   MENU_REPO_ID  VARCHAR2 (32)
,   DESCR         VARCHAR2 (100 BYTE)
);
