ALTER TABLE APP_GROUPS
   DROP PRIMARY KEY CASCADE;

DROP TABLE APP_GROUPS;

CREATE TABLE APP_GROUPS(
    APP_GROUP_SID     NUMBER(8)
                      CONSTRAINT APP_GROUPS_PK PRIMARY KEY,
    NAME              VARCHAR2(32) NOT NULL,
    DESCR             VARCHAR2(60),
    PARENT_GROUP_SID  NUMBER(8)
                      CONSTRAINT APP_GROUPS_PARENT_FK REFERENCES APP_GROUPS(APP_GROUP_SID),
    ORDER_BY          NUMBER(1) NOT NULL,
    IS_PUBLIC         NUMBER(1)
);

CREATE SEQUENCE APP_GROUPS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER APP_GROUPS_TRG
    BEFORE INSERT
    ON APP_GROUPS
    FOR EACH ROW
BEGIN
    SELECT APP_GROUPS_SEQ.NEXTVAL INTO :NEW.APP_GROUP_SID FROM DUAL;
END;

COMMENT ON COLUMN APP_GROUPS.IS_PUBLIC IS 'When group is public then no secunda rights are needed';
