/* Formatted on 17-06-2021 11:58:20 (QP5 v5.313) */
ALTER TABLE SECUNDA_ROLES
   DROP PRIMARY KEY CASCADE;

DROP TABLE SECUNDA_ROLES CASCADE CONSTRAINTS;

CREATE TABLE SECUNDA_ROLES(
   ROLE_SID  NUMBER(8) CONSTRAINT SECUNDA_ROLES_PK PRIMARY KEY
 , ROLE_ID   VARCHAR2(16 BYTE) NOT NULL CONSTRAINT SECUNDA_ROLES_ID_UNQ UNIQUE
 , DESCR     VARCHAR2(100 BYTE) NOT NULL
);