DROP TABLE UM_AUTHZ_CTY_GRP;

CREATE TABLE UM_AUTHZ_CTY_GRP
(
    CTY_GRP_ID         VARCHAR2(30 BYTE) NOT NULL
,   COUNTRY_ID         VARCHAR2(8 BYTE)  NOT NULL
                                         CONSTRAINT UM_AUTHZ_CTY_GRP_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
,   CONSTRAINT UM_AUTHZ_CTY_GRP_UNQ UNIQUE (CTY_GRP_ID, COUNTRY_ID)
);
