ALTER TABLE UM_AUTHZS
DROP PRIMARY KEY CASCADE;

DROP TABLE UM_AUTHZS;

CREATE TABLE UM_AUTHZS
(
    AUTHZ_SID      NUMBER (8)       CONSTRAINT UM_AUTHZS_PK PRIMARY KEY
,   USER_SID       NUMBER (8)       NOT NULL CONSTRAINT UM_AUTHZS_USER_FK    REFERENCES UM_USERS(USER_SID)
,   ROLE_SID       NUMBER (8)       NOT NULL CONSTRAINT UM_AUTHZS_ROLE_FK    REFERENCES SECUNDA_ROLES(ROLE_SID)
,   APP_SID        NUMBER (8)       NOT NULL CONSTRAINT UM_AUTHZS_APP_FK     REFERENCES APPLICATIONS(APP_SID)
,   CTY_GRP_ID     VARCHAR2(30 BYTE)
,   COUNTRY_ID     VARCHAR2(8 BYTE) CONSTRAINT UM_AUTHZS_FK REFERENCES GEO_AREAS(GEO_AREA_ID)
,   CONSTRAINT UM_AUTHZS_UNQ UNIQUE (USER_SID, ROLE_SID, APP_SID)
);

DROP SEQUENCE UM_AUTHZS_SEQ;

CREATE SEQUENCE UM_AUTHZS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER UM_AUTHZS_TRG
   BEFORE INSERT
   ON UM_AUTHZS
   FOR EACH ROW
BEGIN
    SELECT UM_AUTHZS_SEQ.NEXTVAL INTO :NEW.AUTHZ_SID FROM DUAL;
END;
