ALTER TABLE UM_USER_TYPES
DROP PRIMARY KEY CASCADE;

DROP TABLE UM_USER_TYPES;

CREATE TABLE UM_USER_TYPES
(
    USER_TYPE_SID        NUMBER (8)    CONSTRAINT UM_USER_TYPES_PK PRIMARY KEY
,   USER_TYPE_ID         VARCHAR2 (20 BYTE) NOT NULL
,   DESCR                VARCHAR2 (20 BYTE)
);

DROP SEQUENCE UM_USER_TYPES_SEQ;

CREATE SEQUENCE UM_USER_TYPES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER UM_USER_TYPES_TRG
   BEFORE INSERT
   ON UM_USER_TYPES
   FOR EACH ROW
BEGIN
    SELECT UM_USER_TYPES_SEQ.NEXTVAL INTO :NEW.USER_TYPE_SID FROM DUAL;
END;
