ALTER TABLE UM_USERS
DROP PRIMARY KEY CASCADE;

DROP TABLE UM_USERS;

CREATE TABLE UM_USERS
(
    USER_SID        NUMBER (8)    CONSTRAINT UM_USERS_PK PRIMARY KEY
,   LDAP_LOGIN      VARCHAR2 (20) NOT NULL
,   USER_TYPE_SID   NUMBER (8)    NOT NULL
);

DROP SEQUENCE UM_USERS_SEQ;

CREATE SEQUENCE UM_USERS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER UM_USERS_TRG
   BEFORE INSERT
   ON UM_USERS
   FOR EACH ROW
BEGIN
    SELECT UM_USERS_SEQ.NEXTVAL INTO :NEW.USER_SID FROM DUAL;
END;
