/* Formatted on 12/2/2019 16:26:30 (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW VW_CALCULATED_INDIC_DATA
AS
   SELECT D.*
,         R.YEAR
,         I.INDICATOR_ID
,         I.DESCR
,         I.SOURCE INDICATOR_SOURCE
     FROM CALCULATED_INDIC_DATA D
          JOIN ROUNDS R ON R.ROUND_SID = D.ROUND_SID
          JOIN INDICATORS I ON I.INDICATOR_SID = D.INDICATOR_SID