/* Formatted on 26-05-2020 10:36:19 (QP5 v5.313) */
CREATE OR REPLACE FORCE VIEW VW_CYCLICAL_ADJUSTMENTS
AS
   SELECT CA.*, T.DESCR
     FROM CYCLICAL_ADJUSTMENTS  CA
          JOIN CYCLICAL_ADJUSTMENT_TYPES T
             ON T.CYCLICAL_ADJUSTMENT_TYPE_SID = CA.CYCLICAL_ADJUSTMENT_TYPE_SID;