/* Formatted on 12/2/2019 16:27:42 (QP5 v5.252.13127.32847) */
CREATE OR REPLACE FORCE VIEW VW_FP_TPL_DEFINITIONS
AS
   SELECT FW.WORKSHEET_SID AS "WORKSHEET_SID"
,         FW.NAME AS "WORKSHEET_NAME"
,         FW.TITLE AS "WORKSHEET_HEADER"
,         FW.START_YEAR AS "START_YEAR"
,         FW.END_YEAR AS "END_YEAR"
,         I.INDICATOR_SID AS "INDICATOR_SID"
,         I.INDICATOR_ID AS "INDICATOR_ID"
,         FG.DESCR AS "GLOSSARY_DESC"
,         FG.SECTION_NAME AS "GLOSSARY_LOCATION"
,         FG.EXPLANATION AS "GLOSSARY_EXPLANATION"
,         FI.TITLE AS "EXCEL_IND_TITLE"
,         FW.ORDER_BY AS "WORKSHEET_ORDER"
,         FI.ORDER_BY AS "INDICATOR_ORDER"
     FROM FP_TPL_INDICATORS FI
          JOIN FP_TPL_WORKSHEET FW ON FI.WORKSHEET_SID = FW.WORKSHEET_SID
          JOIN INDICATORS I ON FI.INDICATOR_SID = I.INDICATOR_SID
          LEFT OUTER JOIN FP_TPL_GLOSSARY FG
             ON FI.GLOSSARY_SID = FG.GLOSSARY_SID;