/* Formatted on 12/17/2019 13:33:00 (QP5 v5.252.13127.32847) */
INSERT INTO DBP_CTY_ROUND_SCALES (ROUND_SID, CTY_VERSION_SID, SCALE_SID)
   SELECT S.ROUND_SID, V.CTY_VERSION_SID, S.SCALE_SID
     FROM DRM_CTY_ROUND_SCALES@SCOPAX S
          JOIN ROUNDS R ON R.ROUND_SID = S.ROUND_SID
          JOIN COUNTRIES C ON C.COUNTRY_ID = S.CTY_ID
          JOIN GD_CTY_VERSIONS V ON V.COUNTRY_ID = S.CTY_ID;