ALTER TABLE ADDIN_DASHBOARD
DROP PRIMARY KEY CASCADE;

DROP TABLE ADDIN_DASHBOARD;

CREATE TABLE ADDIN_DASHBOARD
(
    DASHBOARD_SID        NUMBER (8)                   CONSTRAINT ADDIN_DASHBOARD_PK PRIMARY KEY
 ,  DASHBOARD_ID         VARCHAR2(30 BYTE)  NOT NULL  CONSTRAINT ADDIN_DASHBOARD_ID_UNQ UNIQUE
 ,  TITLE                VARCHAR2 (64)      NOT NULL
 ,  LINK                 VARCHAR2 (64)      NOT NULL
 ,  IS_ACTIVE            NUMBER (1)         NOT NULL
 ,  OWNER_APP_ID         VARCHAR2(10 BYTE)
 ,  ORDER_BY             NUMBER (3)
);

DROP SEQUENCE ADDIN_DASHBOARD_SEQ;

CREATE SEQUENCE ADDIN_DASHBOARD_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ADDIN_DASHBOARD_TRG
   BEFORE INSERT
   ON ADDIN_DASHBOARD
   FOR EACH ROW
BEGIN
    SELECT ADDIN_DASHBOARD_SEQ.NEXTVAL INTO :NEW.DASHBOARD_SID FROM DUAL;
END;
