ALTER TABLE ADDIN_TREE
DROP PRIMARY KEY CASCADE;

DROP TABLE ADDIN_TREE;
CREATE TABLE ADDIN_TREE
(
	PARENT_TREE_SID NUMBER(8)
,   DASHBOARD_SID   NUMBER(8)      CONSTRAINT ADDIN_TREE_DASHBOARD_FK
                                   REFERENCES ADDIN_DASHBOARD (DASHBOARD_SID)
,   TREE_SID        NUMBER(8)      CONSTRAINT ADDIN_TREE_PK PRIMARY KEY
,   TITLE           VARCHAR2(64)
,   JSON_DATA       VARCHAR2(1000)
);



