INSERT INTO CFG_INDICES_ATTRIBUTES(INDEX_SID, ACCESSOR, ATTR_ID) VALUES (1, 'ENTRY_NO', 'ENTRY_NO');
INSERT INTO CFG_INDICES_ATTRIBUTES(INDEX_SID, ACCESSOR, ATTR_ID) VALUES (1, 'ENTRY_VERSION', 'ENTRY_VERSION');
INSERT INTO CFG_INDICES_ATTRIBUTES(INDEX_SID, ACCESSOR, ATTR_ID) VALUES (1, 2, 'SECTOR');
INSERT INTO CFG_INDICES_ATTRIBUTES(INDEX_SID, ACCESSOR, ATTR_ID) VALUES (2, 'ENTRY_NO', 'ENTRY_NO');
INSERT INTO CFG_INDICES_ATTRIBUTES(INDEX_SID, ACCESSOR, ATTR_ID) VALUES (2, 'ENTRY_VERSION', 'ENTRY_VERSION');
INSERT INTO CFG_INDICES_ATTRIBUTES(INDEX_SID, ACCESSOR, ATTR_ID) VALUES (2, 2, 'SECTOR');
COMMIT;