Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (1,'VFY','Verify',1);
Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (2,'UPD','Update',2);
Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (3,'RFM','Reform',3);
Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (4,'CPL','Complete',4);
Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (5,'NEW','New Rule',3);
Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (6,'NOC','No Change',3);
Insert into CFG_EDIT_STEPS (EDIT_STEP_SID,EDIT_STEP_ID,DESCR,ORDER_BY) values (7,'RFF','Reform in Future',3);
COMMIT;