DECLARE
    CURSOR c_data IS
    SELECT * FROM FGD_IDX_INDEXES ORDER BY INDEX_SID;
BEGIN
    FOR rec IN c_data LOOP
        INSERT INTO CFG_INDEXES(QUESTIONNAIRE_SID, INDEX_ID, DESCR, IS_ANNUAL, IN_MAIL_TEXT)
        VALUES (rec.QUESTIONNAIRE_SID, rec.INDEX_ID, rec.DESCR, rec.IS_ANNUAL, rec.IN_MAIL_TEXT);
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        log_fail('CFG_INDEXES failure', SYSDATE, SQLERRM(), -1);
END;