DECLARE

    CURSOR c_data IS
    SELECT get_question_version_sid(A.ATTR_SID) AS QUESTION_VERSION_SID
          ,NVL(get_lov_sid(A.RESPONSE_SID),0) AS LOV_SID
          ,A.CRITERION_SID
          ,A.SCORE
      FROM fgd_idx_attr_resp_criteria A;
BEGIN
    FOR rec IN c_data LOOP
        INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE)
        VALUES (rec.QUESTION_VERSION_SID, rec.LOV_SID, rec.CRITERION_SID, rec.SCORE);
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        log_fail('CFG_INDEX_CHOICES_SCORES', SYSDATE, SQLERRM(), 0);
END;
/
--ExAnte Compliance
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 208, 12, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 209, 12, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 210, 12, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 211, 12, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 208, 12, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 209, 12, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 210, 12, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 211, 12, 0);
--ExPost Compliance
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 208, 13, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 209, 13, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 210, 13, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 211, 13, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 208, 13, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 209, 13, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 210, 13, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (1, 211, 13, 0);
--Escape Clauses Triggered
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (57, 3, 14, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (57, 4, 14, 0);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (68, 3, 14, 1);
INSERT INTO CFG_INDEX_CHOICES_SCORES(QUESTION_VERSION_SID, LOV_SID, CRITERION_SID, SCORE) VALUES (68, 4, 14, 0);
COMMIT;