INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID,  COND_LOV_SID, CUSTOM_CONDITION)
VALUES (7, 92, 49, 280, NULL);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (7, 92, 50, NULL, 'SELECT COUNT(RESPONSE) FROM ENTRY_CHOICES WHERE ENTRY_SID = {ENTRY_SID} AND QUESTION_VERSION_SID = {QUESTION_VERSION_SID} > 0');

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 166,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) <= {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 167,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) >= {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 168,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) <= {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 169,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) <= {TARGET}');

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 170,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) > {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 171,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) < {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 172,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID})) > {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (12, 173,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) > {TARGET}');

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 174,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) <= {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 175,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID})) >= {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 176,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) <= {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 177,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) <= {TARGET}');

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 178,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) > {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 179,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) < {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 180,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) > {TARGET}');
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (13, 181,52, NULL, '(SELECT TO_NUMBER(DETAILS) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) > {TARGET}');

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (14, 182,68, 3,NULL, 184);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (14, 182,68, 4,NULL, 185);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, AND_CHOICE_SCORE_SID)
VALUES (14, 183,68, 4,NULL, 185);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (14, 184,57, 3,NULL, 182);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (14, 184,57, 4,NULL, 183);

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (17, 90, 120, NULL, '(SELECT COUNT(*) FROM CFG_SPECIAL_LOVS L, ENTRY_CHOICES EC, CFG_LOV_TYPES LT WHERE LT.LOV_TYPE_ID LIKE ' || CHR(39) || 'MONITRULES'|| CHR(37) || CHR(39) || ' AND LT.LOV_TYPE_SID = L.LOV_TYPE_SID AND L.IS_GG = 1 AND TO_NUMBER(EC.RESPONSE) = L.LOV_SID AND EC.QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND EC.ENTRY_SID = {ENTRY_SID}) = (SELECT COUNT(*) FROM CFG_SPECIAL_LOVS SL, ENTRIES E, CFG_LOVS L, CFG_LOV_TYPES LT WHERE E.COUNTRY_ID = L.DESCR AND LT.LOV_TYPE_ID LIKE '|| chr(39) || 'MONITRULES'|| CHR(37) || CHR(39) || ' AND LT.LOV_TYPE_SID = SL.LOV_TYPE_SID AND L.LOV_SID = TO_NUMBER(SUBSTR(TO_CHAR(SL.LOV_SID), 3 ,4)) AND E.ENTRY_SID = {ENTRY_SID} AND SL.IS_GG = 1)');

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION)
VALUES (20, 118,127, 647, NULL);

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (24, 130, 147, 680, NULL, 65);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (24, 130, 147, 681, NULL, 64);

INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (36, NULL, 250, NULL, '(SELECT COUNT(*) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) >= 2', NULL);
INSERT INTO CFG_SCORE_CONDITIONS(CRITERION_SID, CHOICE_SCORE_SID, COND_QUESTION_VERSION_SID, COND_LOV_SID, CUSTOM_CONDITION, OR_CHOICE_SCORE_SID)
VALUES (36, NULL, 252, NULL, '(SELECT COUNT(*) FROM ENTRY_CHOICES WHERE QUESTION_VERSION_SID = {QUESTION_VERSION_SID} AND ENTRY_SID = {ENTRY_SID}) >= 2', NULL);
COMMIT;