DECLARE 
    CURSOR c_data IS
         SELECT T.* FROM FGD_NFR_COMPLIANCE_REFS T;
BEGIN
    FOR rec IN c_data LOOP
        INSERT INTO CFG_COMPLIANCE_REFS(ENTRY_TYPE_SID, BUDG_AGG_SID, TARGET_UNIT_SID, COVERAGE_SID, PERIOD_SID, COMPLIANCE_SOURCE_SID, DESCR, INDICATOR_SID, LINE_ID)
        VALUES (get_lov_sid(rec.RULE_TYPE_SID), get_lov_sid(rec.BUDG_AGG_SID), get_lov_sid(rec.TARGET_UNIT_SID), get_lov_sid(rec.COVERAGE_SID), rec.PERIOD_SID, rec.COMPLIANCE_SOURCE_SID, rec.DESCR, rec.INDICATOR_SID, rec.LINE_ID);
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        LOG_FAIL('CFG_COMPLIANCE_REFS', sysdate, sqlerrm(), 0);
END;