DECLARE
    CURSOR c_data IS
    SELECT b.QSTNNR_VERSION_SID
          ,a.QSTNNR_SECTION_SID AS SECTION_VERSION_SID
          ,d.new_question_version_sid as question_version_sid 
          ,FCQ.SHORT
          ,a.WIDTH
          ,a.MAPPING_TYPE
          ,a.ORDER_BY
          ,a.IN_QUESTIONNAIRE
          ,a.IN_SCORES
          ,a.IN_INDEXES
     FROM fgd_cfg_header_attributes a,
          CFG_QSTNNR_VERSIONS b,
          QUESTION_VERSIONS_MIG d,
          FGD_CFG_ATTRIBUTES ATTR,
          FGD_CFG_QUESTIONS FCQ
    WHERE a.QUESTIONNAIRE_SID = b.QUESTIONNAIRE_SID
      AND a.ATTR_sid = d.OLD_ATTR_SID
      AND A.ATTR_SID = ATTR.ATTR_SID
      AND ATTR.QUESTION_SID = FCQ.QUESTION_SID
    ;
    
    
BEGIN
    FOR rec IN c_data LOOP
        INSERT INTO CFG_HEADERS(QSTNNR_VERSION_SID, SECTION_VERSION_SID, QUESTION_VERSION_SID, SHORT, WIDTH, MAPPING_TYPE, ORDER_BY, IN_QUESTIONNAIRE, IN_SCORES, IN_INDEXES)
        VALUES (rec.QSTNNR_VERSION_SID, rec.SECTION_VERSION_SID, rec.QUESTION_VERSION_SID, rec.SHORT, rec.WIDTH, rec.MAPPING_TYPE, rec.ORDER_BY, rec.IN_QUESTIONNAIRE, rec.IN_SCORES, rec.IN_INDEXES);
    END LOOP;
    

EXCEPTION
     WHEN OTHERS THEN
        LOG_FAIL('MIG CFG_HEADERS FAIL', sysdate, sqlerrm(), 0);
END;