DECLARE
    CURSOR c_data IS
    SELECT a.CUSTOM_ATTR_ID
          ,b.QSTNNR_VERSION_SID
          ,a.WIDTH
          ,a.ORDER_BY
          ,a.IN_QUESTIONNAIRE
          ,a.IN_SCORES
          ,a.IN_INDEXES
     FROM FGD_CFG_CUSTOM_HEADERS a,
          CFG_QSTNNR_VERSIONS b
    WHERE a.QUESTIONNAIRE_SID = b.QUESTIONNAIRE_SID;
BEGIN
    FOR rec IN c_data LOOP
        INSERT INTO CFG_CUSTOM_HEADERS(CUSTOM_HEADER_ID, QSTNNR_VERSION_SID, WIDTH, ORDER_BY, IN_QUESTIONNAIRE, IN_SCORES, IN_INDEXES)
        VALUES (rec.CUSTOM_ATTR_ID, rec.QSTNNR_VERSION_SID, rec.WIDTH, rec.ORDER_BY, rec.IN_QUESTIONNAIRE, rec.IN_SCORES, rec.IN_INDEXES);
    END LOOP;
EXCEPTION
     WHEN OTHERS THEN
        LOG_FAIL('MIG CFG_CUSTOM_HEADERS FAIL', sysdate, sqlerrm(), 0);
END;
/