INSERT INTO CFG_SCORE_TYPES(SCORE_TYPE_SID, DESCR, ACCESSOR) VALUES (1, 'Score calculated on the answer of one single choice question', 'calcSingleScore');
INSERT INTO CFG_SCORE_TYPES(SCORE_TYPE_SID, DESCR, ACCESSOR) VALUES (2, 'Score calculated on the answers of one multiple choice question', 'calcMultiScore');
INSERT INTO CFG_SCORE_TYPES(SCORE_TYPE_SID, DESCR, ACCESSOR) VALUES (3, 'Score based on the sum of scores of at least 2 questions', 'calcSumScore');
INSERT INTO CFG_SCORE_TYPES(SCORE_TYPE_SID, DESCR, ACCESSOR) VALUES (4, 'Score based on the mean of scores of at least 2 questions', 'calcMeanScore');
INSERT INTO CFG_SCORE_TYPES(SCORE_TYPE_SID, DESCR, ACCESSOR) VALUES (5, 'Conditional score calculated on the answer of single choice question(s)', 'calcCondSingleScore');
INSERT INTO CFG_SCORE_TYPES(SCORE_TYPE_SID, DESCR, ACCESSOR) VALUES (6, 'Conditional score calculated on the answers of multiple choice question(s)', 'calcCondMultiScore');
COMMIT;

--FRSI scores
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 1;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 2;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 2 WHERE CRITERION_SID = 3;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 3 WHERE CRITERION_SID = 4;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 2 WHERE CRITERION_SID = 5;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 6; 
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 7; --VERIFY THE SCORE_CHOICES ARE CORRECT
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 8;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 9;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 10;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 2 WHERE CRITERION_SID = 11;
--FRCI scores
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 5 WHERE CRITERION_SID = 12;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 5 WHERE CRITERION_SID = 13;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 6 WHERE CRITERION_SID = 14;
--SIFI scores
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 3 WHERE CRITERION_SID = 15;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 16;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 5 WHERE CRITERION_SID = 17;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 4 WHERE CRITERION_SID = 18;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 19;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 5 WHERE CRITERION_SID = 20;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 21;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 22;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 23;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 5 WHERE CRITERION_SID = 24;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 25;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 26;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 27;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 28;
--MTBFI scores
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 29;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 30;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 2 WHERE CRITERION_SID = 31;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 32;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 33;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 34;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 2 WHERE CRITERION_SID = 35;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 6 WHERE CRITERION_SID = 36;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 37;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 1 WHERE CRITERION_SID = 38;
UPDATE CFG_INDEX_CRITERIA SET SCORE_TYPE_SID = 2 WHERE CRITERION_SID = 39;
COMMIT;