DECLARE

    CURSOR c_section_attrs IS
    SELECT A.QSTNNR_SECTION_SID as OLD_QSTNNR_SECTION_SID,
           A.ATTR_SID as OLD_ATTR_SID,
           A.ORDER_BY,
           m.section_version_sid,
           QVM.NEW_QUESTION_VERSION_SID AS QUESTION_VERSION_SID
      FROM FGD_CFG_QSTNNR_SEC_ATTRIBUTES A,
           SECTIONS_MIG M,
           QUESTION_VERSIONS_MIG QVM
     WHERE M.OLD_SECTION_SID = A.QSTNNR_SECTION_SID
       AND A.ATTR_SID = QVM.OLD_ATTR_SID
       ORDER BY 1, 3
      ;
    

BEGIN
    FOR r_rec IN c_section_attrs LOOP
        BEGIN
            INSERT INTO CFG_QSTNNR_SECTION_QUESTIONS(SECTION_VERSION_SID, QUESTION_VERSION_SID, ORDER_BY)
            VALUES (r_rec.SECTION_VERSION_SID, r_rec.QUESTION_VERSION_SID, r_rec.ORDER_BY)
            ;
        EXCEPTION
            WHEN OTHERS THEN
                LOG_FAIL('CFG_QSTNNR_SECTION_QUESTIONS', sysdate, sqlerrm(), 0);
        END;
            INSERT INTO SECTION_QUESTIONS_MIG(OLD_SECTION_SID, OLD_ATTR_SID, SECTION_VERSION_SID, QUESTION_VERSION_SID, ORDER_BY)
            VALUES (r_rec.old_qstnnr_section_sid, r_rec.OLD_ATTR_SID, r_rec.SECTION_VERSION_SID, r_rec.QUESTION_VERSION_SID, r_rec.ORDER_BY);
    END LOOP;
    
    
    
 EXCEPTION 
    WHEN OTHERS THEN
        LOG_FAIL('MIG section questions FAIL', sysdate, sqlerrm(), 0);
END;
/
DELETE CFG_QSTNNR_SECTION_QUESTIONS
WHERE  SECTION_VERSION_SID = 2
AND QUESTION_VERSION_SID = 409 AND ORDER_BY = 0;
COMMIT;
/   