DECLARE
    l_question NUMBER;
BEGIN
    SELECT NEW_QUESTION_VERSION_SID
      INTO l_question
      FROM QUESTION_VERSIONS_MIG
     WHERE OLD_ATTR_SID IN (SELECT ATTR_SID FROM FGD_CFG_ATTRIBUTES WHERE ATTR_NAME = 'RULE_TYPE_SID') ;
    
    INSERT INTO CFG_COMPLIANCE_QUESTIONS(COMPLIANCE_ATTR, QUESTION_VERSION_SID) VALUES ('ENTRY_TYPE_SID', l_question);
    
    SELECT NEW_QUESTION_VERSION_SID
      INTO l_question
      FROM QUESTION_VERSIONS_MIG
     WHERE OLD_ATTR_SID IN (SELECT ATTR_SID FROM FGD_CFG_ATTRIBUTES WHERE ATTR_NAME = 'BUDG_AGG_SID') ;
     
    INSERT INTO CFG_COMPLIANCE_QUESTIONS(COMPLIANCE_ATTR, QUESTION_VERSION_SID) VALUES ('BUDG_AGG_SID', l_question);
    
    SELECT NEW_QUESTION_VERSION_SID
      INTO l_question
      FROM QUESTION_VERSIONS_MIG
     WHERE OLD_ATTR_SID IN (SELECT ATTR_SID FROM FGD_CFG_ATTRIBUTES WHERE ATTR_NAME = 'TARGET_UNIT_SID') ;
     
     INSERT INTO CFG_COMPLIANCE_QUESTIONS(COMPLIANCE_ATTR, QUESTION_VERSION_SID) VALUES ('TARGET_UNIT_SID', l_question);
     SELECT NEW_QUESTION_VERSION_SID
      INTO l_question
      FROM QUESTION_VERSIONS_MIG
     WHERE OLD_ATTR_SID IN (SELECT ATTR_SID FROM FGD_CFG_ATTRIBUTES WHERE ATTR_NAME = 'SECTOR_SID' AND MASTER_SID IS NULL) ;
    
    INSERT INTO CFG_COMPLIANCE_QUESTIONS(COMPLIANCE_ATTR, QUESTION_VERSION_SID) VALUES ('COVERAGE_SID', l_question);
EXCEPTION
    WHEN OTHERS THEN
        LOG_FAIL('CFG_COMPLIANCE_QUESTIONS', sysdate, sqlerrm(), 0);
END;