DECLARE
    CURSOR c_data IS
    SELECT S.SECTION_VERSION_SID,
           Q.WORKFLOW_STEP_SID
      FROM FGD_CFG_UPDATABLE_SECTIONS Q
          ,SECTIONS_MIG S
     WHERE Q.QSTNNR_SECTION_SID = s.old_section_sid;
     
BEGIN
    FOR r_rec IN c_data LOOP
        INSERT INTO CFG_UPDATABLE_SECTION_VERSIONS(SECTION_VERSION_SID, EDIT_STEP_SID)
        VALUES (r_rec.SECTION_VERSION_SID, r_rec.WORKFLOW_STEP_SID);
    END LOOP;
END;