INSERT INTO CFG_INDEX_STAGES SELECT SCORE_VERSION_SID, SCORE_VERSION_ID, ORDER_BY, AUTOMATIC, ITERABLE, MS_SHARED, READ_ONLY, FILL_BLANKS  FROM FGD_IDX_SCORE_VERSIONS;
COMMIT;
DECLARE
    CURSOR c_data IS 
        SELECT A.SCORE_VERSION_SID,
               A.DESCR,
               B.INDEX_SID
          FROM FGD_IDX_SCORE_VERSIONS A,
               CFG_INDEXES B;
BEGIN
    FOR rec IN c_data LOOP
        INSERT INTO CFG_INDEX_STAGE_VERSIONS VALUES (rec.SCORE_VERSION_SID, rec.INDEX_SID, rec.DESCR);
        
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        LOG_FAIL('MIG CFG_INDEX_STAGE_VERSIONS FAIL', sysdate, sqlerrm(), 0);
END;
/