/* Formatted on 12/17/2019 13:33:00 (QP5 v5.252.13127.32847) */
INSERT INTO DRM_ARCHIVED_CTY_SCALES (ROUND_SID, COUNTRY_ID, SCALE_SID)
   SELECT S.ROUND_SID, S.CTY_ID, S.SCALE_SID
     FROM DRM_CTY_ROUND_SCALES@SCOPAX S
          JOIN ROUNDS R ON R.ROUND_SID = S.ROUND_SID
          JOIN COUNTRIES C ON C.COUNTRY_ID = S.CTY_ID;

COMMIT;