/* Formatted on 14/08/2020 12:16:19 (QP5 v5.313) */
--CREATE DATABASE LINK "SCOPAX_UM"
--CONNECT TO "SCOPAX" IDENTIFIED BY "password"
--USING 'EX1UECFD';


CREATE OR REPLACE SYNONYM UM_APPLICATIONS FOR SCOPAX.UM_APPLICATIONS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_APP_GROUPS FOR SCOPAX.UM_APP_GROUPS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_APP_GROUP_DETAILS FOR SCOPAX.UM_APP_GROUP_DETAILS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_AUTHZS FOR SCOPAX.UM_AUTHZS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_AUTHZS_COUNTRIES FOR SCOPAX.UM_AUTHZS_COUNTRIES@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_COUNTRIES FOR SCOPAX.UM_COUNTRIES@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_GROUPS FOR SCOPAX.UM_GROUPS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_USERS FOR SCOPAX.UM_USERS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_USERS_GROUPS_APPS FOR SCOPAX.UM_USERS_GROUPS_APPS@SCOPAX_UM;


CREATE OR REPLACE SYNONYM UM_USER_TYPES FOR SCOPAX.UM_USER_TYPES@SCOPAX_UM;