/* Formatted on 11-02-2020 16:30:40 (QP5 v5.313) */

DROP TABLE MIGR_LINES CASCADE CONSTRAINTS;

CREATE TABLE MIGR_LINES(
    LINE_SID NUMBER(8)
  , GRID_SID NUMBER(8)
  , LINE_TYPE_SID NUMBER(8)
  , DESCR VARCHAR2(100 BYTE)
  , ORDER_BY NUMBER(2)
  , ESA_CODE VARCHAR2(50 BYTE)
  , HELP_MSG_SID NUMBER
  , MANDATORY NUMBER
  , RATS_ID VARCHAR2(20 BYTE)
  , LINE_ID VARCHAR2(10 BYTE)
  , EB_ID VARCHAR2(20 BYTE)
  , IN_AGG VARCHAR2(1 BYTE)
  , IN_LT VARCHAR2(1 BYTE)
  , IS_MANDATORY VARCHAR2(1 BYTE)
  , INDICATOR_ID VARCHAR2(20 BYTE)
  , WEIGHT VARCHAR2(3 BYTE)
  , WEIGHT_YEAR NUMBER(1)
  , IN_DD VARCHAR2(1 BYTE)
  , AGG_DESCR VARCHAR2(500 BYTE)
  , CALC_RULE VARCHAR2(500 BYTE)
  , COPY_LINE_ID VARCHAR2(10 BYTE)
  , NEW_LINE_SID NUMBER(8)
);

CREATE UNIQUE INDEX MIGR_LINES_UNQ
    ON MIGR_LINES(LINE_SID);

DROP TABLE MIGR_COLS CASCADE CONSTRAINTS;

CREATE TABLE MIGR_COLS(
    COL_SID NUMBER(8)
  , GRID_SID NUMBER(8)
  , COL_TYPE_SID NUMBER(8)
  , DESCR VARCHAR2(500 BYTE)
  , ORDER_BY NUMBER(2)
  , DATA_TYPE_SID NUMBER(8)
  , YEAR_VALUE NUMBER
  , ABSOLUTE NUMBER
  , HELP_MSG_SID NUMBER
  , MANDATORY NUMBER
  , NEW_COL_SID NUMBER(8)
);

CREATE UNIQUE INDEX MIGR_COLS_UNQ
    ON MIGR_COLS(COL_SID);

DROP TABLE MIGR_ROUNDS;

CREATE TABLE MIGR_ROUNDS(
    ROUND_SID  NUMBER(8) NOT NULL
  , APP_SID    NUMBER(8) NOT NULL
  , YEAR       NUMBER(4) NOT NULL
  , FORECAST_PERIOD_SID NUMBER(8)
  , STATUS_SID NUMBER(8)
  , TITLE VARCHAR2(100 BYTE)
  , DESCR VARCHAR2(4000 BYTE)
  , VERSION NUMBER(8)
  , NEW_ROUND_SID NUMBER(8)
  , NEW_STORAGE_ID VARCHAR2(20)
  , NEW_CUST_TEXT_SID NUMBER(8)
);
