CREATE OR REPLACE FORCE VIEW VW_DSLOAD_VALID_STATUSES
AS
    SELECT VS.STATUS_SID
         , DS.STATUS_ID AS VALID_STATUS_ID
    FROM DSLOAD_VALID_STATUSES VS
    JOIN DSLOAD_STATUSES DS
      ON VS.VALID_STATUS_SID = DS.STATUS_SID;
