ALTER TABLE ACCESS_INFO
DROP PRIMARY KEY CASCADE;

DROP TABLE ACCESS_INFO;
DROP SEQUENCE ACCESS_INFO_SID_SEQ;

CREATE TABLE ACCESS_INFO
(
       ACCESS_SID           NUMBER (8) CONSTRAINT ACCESS_INFO_PK PRIMARY KEY
    ,  USER_ID              VARCHAR2 (30 BYTE) NOT NULL
    ,  APP                  VARCHAR2 (30 BYTE) NOT NULL
    ,  URI                  CLOB
    ,  INTRAGATE            NUMBER(1)
                            CONSTRAINT ACCESS_INFO_INTRAGATE_CHK CHECK(INTRAGATE IN (0, 1))
    ,  LATEST_IP            VARCHAR2 (30 BYTE) NOT NULL
    ,  LATEST_ACCESS_DATE   DATE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE ACCESS_INFO_SID_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER ACCESS_INFO_TRG
   BEFORE INSERT
   ON ACCESS_INFO
   FOR EACH ROW
BEGIN
SELECT ACCESS_INFO_SID_SEQ.NEXTVAL INTO :NEW.ACCESS_SID FROM DUAL;
END;
