UPDATE HELP_MSGS SET HELP_MSG_TYPE_ID = 'LINE'
WHERE HELP_MSG_SID IN (SELECT HELP_MSG_SID FROM GD_LINES);

UPDATE HELP_MSGS SET HELP_MSG_TYPE_ID = 'COLUMN'
WHERE HELP_MSG_SID IN (SELECT HELP_MSG_SID FROM GD_COLS);

UPDATE HELP_MSGS SET HELP_MSG_TYPE_ID = 'GRID'
WHERE HELP_MSG_SID IN (SELECT HELP_MSG_SID FROM GD_GRIDS);

COMMIT;
