/* Formatted on 12/12/2019 15:16:34 (QP5 v5.252.13127.32847) */
INSERT INTO SEMI_ELASTICS (COUNTRY_ID
,                          VALUE
,                          ROUND_SID)
   SELECT S.COUNTRY_ID
,         S.VALUE
,         R.ROUND_SID
     FROM SEMI_ELASTICS@SCOPAX S
          JOIN FORECAST_PERIODS@SCOPAX FP
             ON FP.FORECAST_PERIOD_SID = S.FORECAST_PERIOD_SID
          JOIN ROUNDS R
             ON R.YEAR = FP.FORECAST_YEAR AND R.PERIOD_SID = FP.PERIOD_SID;
COMMIT;
