CREATE OR REPLACE FORCE VIEW VW_DWH_INDICATOR_DATA
AS
    SELECT V.INDICATOR_ID
         , V.PERIODICITY_ID
         , V.PROVIDER_ID
         , D.START_YEAR
         , D.TIMESERIE_DATA
         , D.UPDATE_DATE
         , D.UPDATE_USER
      FROM DWH_INDICATOR_DATA D
      JOIN VW_DWH_INDICATORS V ON D.INDICATOR_SID = V.INDICATOR_SID;
